import {fireNightmareWeapon,updateNightmareShot} from './NightmareWeapons';
import {weaponCooldown,weaponEnergy} from './WeaponSettings';
import {nightmareAttackers,nightmarePreferredRange,bossPhase} from './NightmareTactics';
import {updateNightmareBoss} from './NightmareBoss';
import {attackPower,invincible,nightmareHealth} from './PowerEffects';
import {shotDirection} from '../input/Aim';
import {decorateProjectile} from '../effects/ProjectileLook';
import {infantrySpeed,puniShoots} from './CombatRules';
import {enemyPressure,enemyRecovery} from './EnemyPressure';
import {supportHeight} from '../world/CastleFloors';
import {thunderbolt} from './Thunderbolt';
import {enemySizeMultiplier} from './EnemyScale';
import {challenges} from './Challenge';
import * as T from 'three';
import {updateSamurai} from './SamuraiCombat';
import {slash} from './Katana';
import {noticesPlayer} from '../ai/Awareness';
import type {Game,Shot} from './Game';
import {Enemy} from './Enemy';
import {difficulty} from './Difficulty';
import {mesh} from '../world/World';
import {canMove,lineOfSight,wall,canMoveAt,wallAt,sightAt} from '../world/layout';
import {doors} from '../world/Threats';
import {patrolTarget} from '../ai/Patrol';
import {route} from '../world/Navigation';
export function fire(g:Game){const w=g.input.weapon;if(w===3){slash(g);return;}if(g.time<g.shotTime||g.energy<weaponEnergy(w)||w>=4&&(g.challenge!==3||!g.arsenal.nightmareWeapons.has(w)))return;g.shotTime=g.time+weaponCooldown(w,g.arsenal.levels[w]??0);g.energy-=weaponEnergy(w);g.recoil=.07;if(w<4)g.sound.effect([850,430,1200][w]+g.arsenal.levels[w]*140);const aim=g.input.tapAim;const d=shotDirection(g.camera,g.input);
 if(g.input.touch){let best=.965-Math.min(.01,g.failures*.003);for(const e of g.enemies)if(e.alive&&(e.kind!=='KING PUNI'||g.gate)&&sightAt(g.position.x,g.position.z,g.position.y,e.group.position.x,e.group.position.z,e.group.position.y+e.baseScale,g.gate)){const dir=e.group.position.clone().add(new T.Vector3(0,e.kind==='KING PUNI'?2.2*e.baseScale:e.baseScale,0)).sub(g.position).normalize(),dot=dir.dot(d);if(dot>best){best=dot;d.lerp(dir,aim?1:.18).normalize();}}}
 if(w>=4){fireNightmareWeapon(g,d);return;}if(w===2){thunderbolt(g,d);return;}
 const m=mesh(w===2?new T.OctahedronGeometry(.25,1):new T.SphereGeometry(w===1?.38:.1,12,8),[0xffdd79,0x8ef3e2,0xe2acff][w]);decorateProjectile(m,false,w,g.input.touch,d);m.position.copy(g.position).addScaledVector(d,.8);g.scene.add(m);g.shots.push({m,v:d.multiplyScalar(w===1?19:48),life:3,damage:[18,42,95][w]*(g.arsenal.levels[w]?1.65:1)*attackPower(g),enemy:false,kind:w,pierced:new Set()});}
export function updateEnemies(g:Game,dt:number){const attackers=g.challenge===3?nightmareAttackers(g):null;for(const e of g.enemies){if(!e.alive||e.kind==='SAMURAI'&&!doors[5]?.open||e.kind==='KING PUNI'&&!g.gate)continue;const p=e.group.position,dist=Math.hypot(g.position.x-p.x,g.position.z-p.z),t=difficulty[e.tier];e.cooldown-=dt*enemyPressure;const allowed=!attackers||attackers.has(e);const speedFactor=(g.challenge===3&&e.kind==='SAMURAI'?1.2:g.challenge===3&&e.kind==='KING PUNI'?[1,1.18,1.32][bossPhase(e.hp,e.maxHp)]:1)*(e.kind==='INFANTRY'?infantrySpeed(g.challenge):1);const walk=(x:number,z:number)=>g.stageIndex!==2?canMove(x,z,g.gate):canMoveAt(x,z,e.floorY+1.65,g.gate)&&Math.abs(supportHeight(x,z,e.floorY)-e.floorY)<.65;
 const visible=g.stageIndex===2?Math.hypot(g.position.x-p.x,g.position.z-p.z,g.position.y-p.y)<32&&sightAt(p.x,p.z,p.y+e.baseScale,g.position.x,g.position.z,g.position.y,g.gate):noticesPlayer(p.x,p.z,e.group.rotation.y,g.position.x,g.position.z,t.detect,e.brain.state!=='Idle',g.gate);if(visible)e.lastPlayerFloor=g.position.y-1.65;let target=e.brain.update(p.x,p.z,visible,{x:g.position.x,z:g.position.z},g.time,e.cooldown);e.state=e.brain.state;e.animate(g.time,e.state==='Chase'||e.state==='Search');e.group.scale.setScalar(e.baseScale*(g.time<e.brain.surprisedUntil?.92:1));
 if(g.stageIndex===2)e.floorY=supportHeight(p.x,p.z,e.floorY);if(e.kind!=='BALLOONER'&&e.kind!=='KING PUNI')p.y=e.floorY;
 if(!target){if(e.kind!=='KING PUNI'){const wander=patrolTarget(e.home.x,e.home.z,g.time,e.home.x*.3+e.home.z),dx=wander.x-p.x,dz=wander.z-p.z,d=Math.hypot(dx,dz);if(d>.25){const speed=dt*enemyPressure*speedFactor*(.7+g.stageIndex*.25),nx=p.x+dx/d*speed,nz=p.z+dz/d*speed;if(walk(nx,nz)){p.x=nx;p.z=nz;e.animate(g.time,true);}}}continue;}if(g.challenge===3&&e.kind==='INFANTRY'&&visible&&dist>8){const side=(Math.floor(e.home.x+e.home.z)%2)?1:-1,x=g.position.x+(p.z-g.position.z)/dist*side*3,z=g.position.z-(p.x-g.position.x)/dist*side*3;if(walk(x,z))target={x,z};}e.group.rotation.y=Math.atan2(p.x-target.x,p.z-target.z);if(e.kind==='BALLOONER')p.y=e.floorY+1.5+Math.sin(g.time*2)*.4;if(g.time<e.stunned||g.time<e.brain.surprisedUntil)continue;
 if(g.challenge===3&&!allowed&&visible&&e.telegraph&&e.kind!=='SAMURAI'&&e.kind!=='KING PUNI'){e.telegraph=0;e.group.userData.meleeTell=false;e.cooldown=Math.max(e.cooldown,.3);}
 if(e.kind==='SAMURAI'&&updateSamurai(g,e,dt,visible,dist,allowed))continue;
 const approachDistance=g.challenge===3?nightmarePreferredRange(e,allowed):e.kind==='PUNI'||e.kind==='LAVA HOPPER'?2.1:2.6;const held=g.challenge===3&&e.kind==='KING PUNI'&&(e.telegraph>0||g.time<e.dashUntil||g.time<(e.group.userData.bossRecovery??0));if(!held&&(dist>approachDistance||!visible||g.stageIndex===2&&Math.abs(g.position.y-1.65-(e.floorY??0))>1)){if(g.time>(g.routeTimes.get(e)??0)){g.routeTimes.set(e,g.time+(g.stageIndex===2?.9:.45));g.routes.set(e,route(p.x,p.z,target.x,target.z,g.gate,g.stageIndex===2?e.floorY:undefined,e.lastPlayerFloor));}const next=g.routes.get(e);if(next){const dx=next.x-p.x,dz=next.z-p.z,d=Math.hypot(dx,dz),speed=(e.kind==='PUNI'?4.4:e.kind==='KING PUNI'?4.6:e.kind==='SAMURAI'?8.5:e.kind==='INFANTRY'?3.6:e.kind==='LAVA HOPPER'?5.8:e.kind==='BALLOONER'?4.2:3)*t.speed*dt*enemyPressure*speedFactor;const step=Math.min(speed,d),nx=p.x+dx/Math.max(.0001,d)*step,nz=p.z+dz/Math.max(.0001,d)*step;if(walk(nx,p.z))p.x=nx;if(walk(p.x,nz))p.z=nz;if(Math.hypot(next.x-p.x,next.z-p.z)<.08){g.routes.delete(e);g.routeTimes.delete(e);}}else{const nx=p.x+Math.sin(g.time+e.tier)*dt*enemyPressure,nz=p.z+Math.cos(g.time)*dt*enemyPressure;if(walk(nx,nz)){p.x=nx;p.z=nz;}}}
 for(const other of g.enemies)if(other!==e&&other.alive){const dx=p.x-other.group.position.x,dz=p.z-other.group.position.z,d=Math.hypot(dx,dz);if(d>.01&&d<1.3&&Math.abs(e.floorY-other.floorY)<1.5){const nx=p.x+dx/d*dt,nz=p.z+dz/d*dt;if(walk(nx,nz)){p.x=nx;p.z=nz;}}}
 if(e.kind==='SAMURAI')continue;
 if(g.challenge===3&&e.kind==='KING PUNI'){if(!held&&dist<approachDistance-1&&!e.telegraph){const nx=p.x+(p.x-g.position.x)/Math.max(1,dist)*dt*2.5,nz=p.z+(p.z-g.position.z)/Math.max(1,dist)*dt*2.5;if(walk(nx,nz)){p.x=nx;p.z=nz;}}updateNightmareBoss(g,e,dt,visible,allowed);continue;}
 if(g.challenge===3&&!visible&&e.telegraph&&g.time>e.telegraph+.3)e.telegraph=0;
 if(e.kind==='INFANTRY'){const armed=!!e.sword,reach=armed?3.6:2.9,windup=armed?.8:.55;if(e.sword)e.sword.rotation.z=e.telegraph?-1.3:e.cooldown>.7?1.15:-.5;if(e.telegraph&&g.time>=e.telegraph){e.telegraph=0;e.cooldown=enemyRecovery(armed?1.6:1.35,windup);if(visible&&dist<reach&&Math.abs(g.position.y-1.65-(e.floorY??0))<2)g.hurt(armed?Math.min(44,Math.max(28,(t.damage+3)*2.5)):t.damage+3);}else if(allowed&&visible&&dist<reach&&Math.abs(g.position.y-1.65-(e.floorY??0))<2&&e.cooldown<=0&&!e.telegraph)e.telegraph=g.time+windup;continue;}
 if(visible&&(e.kind==='BOTTY'||e.kind==='BALLOONER'||e.kind==='TOX MUNCHER')&&dist>5){const side=Math.sin(g.time*1.7+e.home.x)>0?1:-1,dx=(g.position.z-p.z)/dist*side*dt*1.8*enemyPressure,dz=-(g.position.x-p.x)/dist*side*dt*1.8*enemyPressure;if(walk(p.x+dx,p.z+dz)){p.x+=dx;p.z+=dz;}}
 if(g.challenge===3&&visible&&['BOTTY','BALLOONER','TOX MUNCHER'].includes(e.kind)&&dist<6&&!e.telegraph){const nx=p.x+(p.x-g.position.x)/Math.max(1,dist)*dt*3.2,nz=p.z+(p.z-g.position.z)/Math.max(1,dist)*dt*3.2;if(walk(nx,nz)){p.x=nx;p.z=nz;}}
 if(!visible)continue;const melee=e.kind==='PUNI'||e.kind==='LAVA HOPPER';if(g.challenge===3&&melee&&(e.group.userData.meleeTell||allowed&&dist<2.4&&e.cooldown<=0)){if(!e.group.userData.meleeTell){e.group.userData.meleeTell=true;e.telegraph=g.time+.5;}else if(g.time>=e.telegraph){e.group.userData.meleeTell=false;e.telegraph=0;e.cooldown=t.melee;if(dist<2.4&&Math.abs(g.position.y-1.65-e.floorY)<2)g.hurt(t.damage);}continue;}if(melee&&allowed&&dist<2.4&&Math.abs(g.position.y-1.65-(e.floorY??0))<2&&e.cooldown<=0){g.hurt(t.damage);e.cooldown=t.melee+Math.min(1,g.failures*.15);}else if(allowed&&(!melee||e.kind==='PUNI'&&puniShoots(g.challenge)&&dist>=2.4)&&e.cooldown<=0){if(!e.telegraph){e.telegraph=g.time+t.warning;e.state='Alert';}else if(g.time>=e.telegraph){e.telegraph=0;e.cooldown=enemyRecovery((e.kind==='KING PUNI'?t.attack*.5:t.attack)+Math.min(1,g.failures*.15),t.warning);const bossPattern=e.kind==='KING PUNI'?e.attackCycle++%4:-1;const origin=p.clone().add(new T.Vector3(0,e.kind==='KING PUNI'?2.2*e.baseScale:e.baseScale,0));const angles=bossPattern===3?Array.from({length:12+g.stageIndex*4},(_,n)=>n*Math.PI*2/(12+g.stageIndex*4)):e.kind==='KING PUNI'?(g.stageIndex===0?[-.15,0,.15]:g.stageIndex===1?[-.12,.12]:[-.2,0,.2]):e.kind==='BOTTY'&&g.stageIndex===2?[-.16,0,.16]:[0];for(const angle of angles){const m=mesh(new T.SphereGeometry(e.kind==='TOX MUNCHER'?.34:.24,12,8),bossPattern===2?0x8de6ff:e.kind==='TOX MUNCHER'||bossPattern===1?0x98d969:0xffa1cb);decorateProjectile(m,true,bossPattern===2?4:e.kind==='TOX MUNCHER'||bossPattern===1?3:0,g.input.touch,g.position.clone().sub(origin).normalize().applyAxisAngle(new T.Vector3(0,1,0),angle));m.position.copy(origin);g.scene.add(m);g.shots.push({m,v:g.position.clone().sub(origin).normalize().applyAxisAngle(new T.Vector3(0,1,0),angle).multiplyScalar(t.projectile),life:4,damage:e.kind==='KING PUNI'?t.damage*1.5:t.damage,enemy:true,kind:bossPattern===2?4:e.kind==='TOX MUNCHER'||bossPattern===1?3:0});}g.sound.effect(e.kind==='TOX MUNCHER'?310:470);if(bossPattern===1)g.notify('みどりの たま！ どくに きをつけて');if(bossPattern===2)g.notify('あおい たま！ まひに きをつけて');
 if(e.kind==='KING PUNI'){p.y=e.floorY+(g.stageIndex===0?1:1.7);if(g.stageIndex>0){const wave=mesh(new T.TorusGeometry(1,.09,6,48),0xf9b576,p.x,e.floorY+.15,p.z);wave.rotation.x=-Math.PI/2;g.scene.add(wave);g.shockwaves.push({m:wave,r:1,hit:false});if(g.enemies.filter(a=>a.alive&&a.kind==='PUNI').length<(g.stageIndex===1?1:3)){const minion=new Enemy('PUNI',p.x-4,p.z-3);minion.hp=nightmareHealth(minion.kind,g.challenge,minion.hp*challenges[g.challenge].hp);minion.maxHp=minion.hp;minion.tier=2;minion.baseScale=1.2*enemySizeMultiplier;minion.floorY=e.floorY;minion.group.position.y=e.floorY;minion.group.scale.setScalar(minion.baseScale);minion.brain.hit(g.position.x,g.position.z,g.time);g.enemies.push(minion);g.scene.add(minion.group);}}}}}
 if(e.kind==='KING PUNI')p.y=Math.max(e.floorY,p.y-dt*3);
 }}
export function updateShots(g:Game,dt:number){for(let n=g.shots.length-1;n>=0;n--){const s=g.shots[n];s.life-=dt;const previous=s.m.position.clone();s.m.position.addScaledVector(s.v,dt);s.m.rotation.z+=dt*8;if(!s.enemy&&s.kind>=4){if(updateNightmareShot(g,s,previous)){g.dispose(s.m);g.shots.splice(n,1);}continue;}if(!sightAt(previous.x,previous.z,previous.y,s.m.position.x,s.m.position.z,s.m.position.y,g.gate)||wallAt(s.m.position.x,s.m.position.z,s.m.position.y,g.gate)){g.dispose(s.m);g.shots.splice(n,1);continue;}let hit=false;if(s.enemy){if(s.m.position.distanceTo(g.position)<.8){g.hurt(s.damage);if(!invincible(g)&&s.kind===3&&!(g.buffs.get('ANTIDOTE')!>g.time))g.poisonUntil=g.time+5;if(!invincible(g)&&s.kind===4&&g.time>=g.paralysisImmuneUntil){g.paralyzedUntil=g.time+3;g.paralysisImmuneUntil=g.time+9;g.notify('まひ！ 3びょう · うつことは できるよ');}hit=true;}}else for(const e of g.enemies)if(e.alive&&!s.pierced?.has(e)&&(e.kind!=='KING PUNI'||g.gate)&&sightAt(s.m.position.x,s.m.position.z,s.m.position.y,e.group.position.x,e.group.position.z,e.group.position.y+e.baseScale,g.gate)){const center=e.group.position.clone().add(new T.Vector3(0,e.kind==='KING PUNI'?2.2*e.baseScale:e.baseScale,0));if(s.m.position.distanceTo(center)<e.radius*e.baseScale+(g.input.touch?.55:.3)){g.damage(e,s.damage);if(s.kind===1){e.stunned=g.time+.5;g.burst(e.group.position,0x8ef3e2);}if(s.kind>0)for(const other of g.enemies)if(other!==e&&other.alive&&lineOfSight(e.group.position.x,e.group.position.z,other.group.position.x,other.group.position.z,g.gate)&&other.group.position.distanceTo(e.group.position)<(s.kind===1?4:6))g.damage(other,s.damage*.65);if(s.kind===2&&g.arsenal.levels[2])s.pierced?.add(e);else hit=true;break;}}
 if(hit||s.life<=0||wallAt(s.m.position.x,s.m.position.z,s.m.position.y,g.gate)){g.dispose(s.m);g.shots.splice(n,1);}}
 for(let n=g.shockwaves.length-1;n>=0;n--){const w=g.shockwaves[n];w.r+=dt*7;w.m.scale.set(w.r,w.r,1);const d=Math.hypot(w.m.position.x-g.position.x,w.m.position.z-g.position.z);if(!w.hit&&Math.abs(d-w.r)<.65&&g.position.y>w.m.position.y+.8&&g.position.y<w.m.position.y+2.2){g.hurt(g.stageIndex===1?8:14);w.hit=true;}if(w.r>(w.m.userData.maxRadius??16)){g.dispose(w.m);g.shockwaves.splice(n,1);}}
}
