import {enemySizeMultiplier} from './EnemyScale';
import {challenges} from './Challenge';
import * as T from 'three';
import {updateSamurai} from './SamuraiCombat';
import {slash} from './Katana';
import {noticesPlayer} from '../ai/Awareness';
import type {Game,Shot} from './Game';
import {Enemy} from './Enemy';
import {difficulty} from './Difficulty';
import {mesh} from '../world/World';
import {canMove,lineOfSight,wall} from '../world/layout';
import {doors} from '../world/Threats';
import {patrolTarget} from '../ai/Patrol';
import {route} from '../world/Navigation';
export function fire(g:Game){const w=g.input.weapon;if(w===3){slash(g);return;}if(g.time<g.shotTime||w===2&&g.energy<12)return;g.shotTime=g.time+[.19,.65,.48][w]*(g.arsenal.levels[w]?.75:1);if(w===2)g.energy-=12;g.recoil=.07;g.sound.effect([850,430,1200][w]+g.arsenal.levels[w]*140);const aim=g.input.tapAim;const d=aim?new T.Vector3(aim.x,aim.y,.5).unproject(g.camera).sub(g.camera.position).normalize():new T.Vector3(0,0,-1).applyQuaternion(g.camera.quaternion);g.input.tapAim=null;
 if(g.input.touch){let best=.965-Math.min(.01,g.failures*.003);for(const e of g.enemies)if(e.alive&&(e.kind!=='KING PUNI'||g.gate)&&lineOfSight(g.position.x,g.position.z,e.group.position.x,e.group.position.z,g.gate)){const dir=e.group.position.clone().add(new T.Vector3(0,e.kind==='KING PUNI'?2.2*e.baseScale:e.baseScale,0)).sub(g.position).normalize(),dot=dir.dot(d);if(dot>best){best=dot;d.lerp(dir,aim?1:.18).normalize();}}}
 const m=mesh(w===2?new T.OctahedronGeometry(.25,1):new T.SphereGeometry(w===1?.38:.1,12,8),[0xffdd79,0x8ef3e2,0xe2acff][w]);m.position.copy(g.position).addScaledVector(d,.8);g.scene.add(m);g.shots.push({m,v:d.multiplyScalar(w===1?19:48),life:3,damage:[18,42,95][w]*(g.arsenal.levels[w]?1.65:1)*(g.buffs.has('RAINBOW')?1.6:1),enemy:false,kind:w,pierced:new Set()});}
export function updateEnemies(g:Game,dt:number){for(const e of g.enemies){if(!e.alive||e.kind==='SAMURAI'&&!doors[5]?.open||e.kind==='KING PUNI'&&!g.gate)continue;const p=e.group.position,dist=Math.hypot(g.position.x-p.x,g.position.z-p.z),t=difficulty[e.tier];e.cooldown-=dt;
 const visible=noticesPlayer(p.x,p.z,e.group.rotation.y,g.position.x,g.position.z,t.detect,e.brain.state!=='Idle',g.gate);const target=e.brain.update(p.x,p.z,visible,{x:g.position.x,z:g.position.z},g.time,e.cooldown);e.state=e.brain.state;e.animate(g.time,e.state==='Chase'||e.state==='Search');e.group.scale.setScalar(e.baseScale*(g.time<e.brain.surprisedUntil?.92:1));
 if(!target){if(e.kind!=='KING PUNI'){const wander=patrolTarget(e.home.x,e.home.z,g.time,e.home.x*.3+e.home.z),dx=wander.x-p.x,dz=wander.z-p.z,d=Math.hypot(dx,dz);if(d>.25){const speed=dt*(.7+g.stageIndex*.25),nx=p.x+dx/d*speed,nz=p.z+dz/d*speed;if(canMove(nx,nz,g.gate)){p.x=nx;p.z=nz;e.animate(g.time,true);}}}continue;}e.group.rotation.y=Math.atan2(p.x-target.x,p.z-target.z);if(e.kind==='BALLOONER')p.y=1.5+Math.sin(g.time*2)*.4;if(g.time<e.stunned||g.time<e.brain.surprisedUntil)continue;
 if(e.kind==='SAMURAI'&&updateSamurai(g,e,dt,visible,dist))continue;
 if(dist>2.6||!visible){if(g.time>(g.routeTimes.get(e)??0)){g.routeTimes.set(e,g.time+.45);g.routes.set(e,route(p.x,p.z,target.x,target.z,g.gate));}const next=g.routes.get(e);if(next){const dx=next.x-p.x,dz=next.z-p.z,d=Math.max(.05,Math.hypot(dx,dz)),speed=(e.kind==='PUNI'?4.4:e.kind==='KING PUNI'?4.6:e.kind==='SAMURAI'?8.5:e.kind==='INFANTRY'?3.6:e.kind==='LAVA HOPPER'?5.8:e.kind==='BALLOONER'?4.2:3)*t.speed*dt;const nx=p.x+dx/d*speed,nz=p.z+dz/d*speed;if(canMove(nx,p.z,g.gate))p.x=nx;if(canMove(p.x,nz,g.gate))p.z=nz;}else{const nx=p.x+Math.sin(g.time+e.tier)*dt,nz=p.z+Math.cos(g.time)*dt;if(canMove(nx,nz,g.gate)){p.x=nx;p.z=nz;}}}
 for(const other of g.enemies)if(other!==e&&other.alive){const dx=p.x-other.group.position.x,dz=p.z-other.group.position.z,d=Math.hypot(dx,dz);if(d>.01&&d<1.3){const nx=p.x+dx/d*dt,nz=p.z+dz/d*dt;if(canMove(nx,nz,g.gate)){p.x=nx;p.z=nz;}}}
 if(e.kind==='SAMURAI')continue;
 if(e.kind==='INFANTRY'){if(e.telegraph&&g.time>=e.telegraph){e.telegraph=0;e.cooldown=1.35;if(visible&&dist<2.9)g.hurt(t.damage+3);}else if(visible&&dist<2.9&&e.cooldown<=0&&!e.telegraph)e.telegraph=g.time+.55;continue;}
 if(visible&&(e.kind==='BOTTY'||e.kind==='BALLOONER'||e.kind==='TOX MUNCHER')&&dist>5){const side=Math.sin(g.time*1.7+e.home.x)>0?1:-1,dx=(g.position.z-p.z)/dist*side*dt*1.8,dz=-(g.position.x-p.x)/dist*side*dt*1.8;if(canMove(p.x+dx,p.z+dz,g.gate)){p.x+=dx;p.z+=dz;}}
 if(!visible)continue;const melee=e.kind==='PUNI'||e.kind==='LAVA HOPPER';if(melee&&dist<2.4&&e.cooldown<=0){g.hurt(t.damage);e.cooldown=t.melee+Math.min(1,g.failures*.15);}else if(!melee&&e.cooldown<=0){if(!e.telegraph){e.telegraph=g.time+t.warning;e.state='Alert';}else if(g.time>=e.telegraph){e.telegraph=0;e.cooldown=(e.kind==='KING PUNI'?t.attack*.5:t.attack)+Math.min(1,g.failures*.15);const bossPattern=e.kind==='KING PUNI'?e.attackCycle++%4:-1;const origin=p.clone().add(new T.Vector3(0,e.kind==='KING PUNI'?2.2*e.baseScale:e.baseScale,0));const angles=bossPattern===3?Array.from({length:12+g.stageIndex*4},(_,n)=>n*Math.PI*2/(12+g.stageIndex*4)):e.kind==='KING PUNI'?(g.stageIndex===0?[-.15,0,.15]:g.stageIndex===1?[-.12,.12]:[-.2,0,.2]):e.kind==='BOTTY'&&g.stageIndex===2?[-.16,0,.16]:[0];for(const angle of angles){const m=mesh(new T.SphereGeometry(e.kind==='TOX MUNCHER'?.34:.24,12,8),bossPattern===2?0x8de6ff:e.kind==='TOX MUNCHER'||bossPattern===1?0x98d969:0xffa1cb);m.position.copy(origin);g.scene.add(m);g.shots.push({m,v:g.position.clone().sub(origin).normalize().applyAxisAngle(new T.Vector3(0,1,0),angle).multiplyScalar(t.projectile),life:4,damage:e.kind==='KING PUNI'?t.damage*1.5:t.damage,enemy:true,kind:bossPattern===2?4:e.kind==='TOX MUNCHER'||bossPattern===1?3:0});}g.sound.effect(e.kind==='TOX MUNCHER'?310:470);if(bossPattern===1)g.notify('みどりの たま！ どくに きをつけて');if(bossPattern===2)g.notify('あおい たま！ まひに きをつけて');
 if(e.kind==='KING PUNI'){p.y=g.stageIndex===0?1:1.7;if(g.stageIndex>0){const wave=mesh(new T.TorusGeometry(1,.09,6,48),0xf9b576,p.x,.15,p.z);wave.rotation.x=-Math.PI/2;g.scene.add(wave);g.shockwaves.push({m:wave,r:1,hit:false});if(g.enemies.filter(a=>a.alive&&a.kind==='PUNI').length<(g.stageIndex===1?1:3)){const minion=new Enemy('PUNI',p.x-4,p.z-3);minion.hp*=challenges[g.challenge].hp;minion.maxHp=minion.hp;minion.tier=2;minion.baseScale=1.2*enemySizeMultiplier;minion.group.scale.setScalar(minion.baseScale);minion.brain.hit(g.position.x,g.position.z,g.time);g.enemies.push(minion);g.scene.add(minion.group);}}}}}
 if(e.kind==='KING PUNI')p.y=Math.max(0,p.y-dt*3);
 }}
export function updateShots(g:Game,dt:number){for(let n=g.shots.length-1;n>=0;n--){const s=g.shots[n];s.life-=dt;s.m.position.addScaledVector(s.v,dt);s.m.rotation.z+=dt*8;if(wall(s.m.position.x,s.m.position.z,g.gate)){g.dispose(s.m);g.shots.splice(n,1);continue;}let hit=false;if(s.enemy){if(s.m.position.distanceTo(g.position)<.8){g.hurt(s.damage);if(s.kind===3)g.poisonUntil=g.time+5;if(s.kind===4&&g.time>=g.paralysisImmuneUntil){g.paralyzedUntil=g.time+3;g.paralysisImmuneUntil=g.time+9;g.notify('まひ！ 3びょう · うつことは できるよ');}hit=true;}}else for(const e of g.enemies)if(e.alive&&!s.pierced?.has(e)&&(e.kind!=='KING PUNI'||g.gate)&&lineOfSight(s.m.position.x,s.m.position.z,e.group.position.x,e.group.position.z,g.gate)){const center=e.group.position.clone().add(new T.Vector3(0,e.kind==='KING PUNI'?2.2*e.baseScale:e.baseScale,0));if(s.m.position.distanceTo(center)<e.radius*e.baseScale+(g.input.touch?.55:.3)){g.damage(e,s.damage);if(s.kind===1){e.stunned=g.time+.5;g.burst(e.group.position,0x8ef3e2);}if(s.kind>0)for(const other of g.enemies)if(other!==e&&other.alive&&lineOfSight(e.group.position.x,e.group.position.z,other.group.position.x,other.group.position.z,g.gate)&&other.group.position.distanceTo(e.group.position)<(s.kind===1?4:6))g.damage(other,s.damage*.65);if(s.kind===2&&g.arsenal.levels[2])s.pierced?.add(e);else hit=true;break;}}
 if(hit||s.life<=0||wall(s.m.position.x,s.m.position.z,g.gate)){g.dispose(s.m);g.shots.splice(n,1);}}
 for(let n=g.shockwaves.length-1;n>=0;n--){const w=g.shockwaves[n];w.r+=dt*7;w.m.scale.set(w.r,w.r,1);const d=Math.hypot(w.m.position.x-g.position.x,w.m.position.z-g.position.z);if(!w.hit&&Math.abs(d-w.r)<.65&&g.position.y<2.35){g.hurt(g.stageIndex===1?8:14);w.hit=true;}if(w.r>16){g.dispose(w.m);g.shockwaves.splice(n,1);}}
}
