import {contactShadow} from '../effects/ContactShadow';
import {dressCreature} from './CreatureDetails';
import {buildInfantry} from './Infantry';
import {glossyPupil,batchCreatureEyes,updateCreatureEyes} from './CreatureEyes';
import {CreatureMotion, type CreatureEye} from './CreatureMotion';
import {creatureMaterial,shareCreatureResources} from './CreatureSurface';
import {Brain} from '../ai/Brain';
import * as T from 'three';import {mesh} from '../world/World';import {glow} from '../world/Art';import {mergeStaticModel} from './MergeModel';import {creatureSkin,applyCreatureTextures} from './CreatureSkin';
export type EnemyKind='INFANTRY'|'PUNI'|'BOTTY'|'BALLOONER'|'KING PUNI'|'TOX MUNCHER'|'LAVA HOPPER'|'SAMURAI';
export class Enemy {
 visualEyeBatches:T.InstancedMesh[]=[];eyes:CreatureEye[]=[];visualWings:T.Object3D[]=[];visualRotors:T.Object3D[]=[];visualDetail=true;private motion=new CreatureMotion(this);private groundShadow:T.Mesh;floorY=0;lastPlayerFloor=0;dashUntil=0;dashX=0;dashZ=0;dashHit=false;sword:T.Object3D|null=null;attackCycle=0;home:{x:number;z:number};brain=new Brain();baseScale=1;group=new T.Group();body=new T.Group();arms:T.Object3D[]=[];legs:T.Object3D[]=[];hp:number;state='Idle';cooldown=0;alive=true;telegraph=0;stunned=0;radius:number;alert=false;encountered=false;tier=0;maxHp=0;
 constructor(public kind:EnemyKind,x:number,z:number){this.home={x,z};const boss=kind==='KING PUNI';this.hp=boss?750:kind==='BOTTY'?85:55;this.radius=boss?2.3:.85;this.maxHp=this.hp;this.groundShadow=contactShadow(boss?2.5:.8);this.group.add(this.body,this.groundShadow);if(kind==='INFANTRY'){const limbs=buildInfantry(this.body);this.legs=limbs.legs;this.arms=limbs.arms;}else if(kind==='SAMURAI')this.samurai();else if(kind==='TOX MUNCHER')this.tox();else if(kind==='LAVA HOPPER')this.hopper();else if(kind==='BOTTY')this.scarab();else if(kind==='BALLOONER')this.manta();else this.jester(boss);dressCreature(this);batchCreatureEyes(this);applyCreatureTextures(this.body);mergeStaticModel(this.body,[...this.legs,...this.arms,...this.visualWings,...this.visualRotors,...(this.sword?[this.sword]:[])]);shareCreatureResources(this.kind,this.body);this.group.position.set(x,0,z);this.group.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;}});this.groundShadow.castShadow=false;this.groundShadow.receiveShadow=false;}
 part(g:T.BufferGeometry,c:number,x=0,y=0,z=0){const m=mesh(g,c,x,y,z);this.body.add(m);return m;}
 eye(x:number,y:number,z:number,size:number){const face=new T.Group();face.position.set(x,y,z);this.body.add(face);
 const gold=creatureMaterial(0xf4d294,'metal'),white=creatureMaterial(0xfff0cd,'enamel');
 const rim=new T.Mesh(new T.TorusGeometry(size,.045,8,24),gold);face.add(rim);
 const core=new T.Mesh(new T.SphereGeometry(size*.79,16,12),white);core.position.z=-.025;core.scale.z=.5;face.add(core);
 const iris=new T.Mesh(new T.SphereGeometry(size*.46,16,12),creatureMaterial(this.kind==='TOX MUNCHER'?0x98df67:this.kind==='SAMURAI'?0x65dae0:0xe8b04e,'enamel'));iris.position.z=-size*.43;iris.scale.z=.4;face.add(iris);
 const pupil=glossyPupil(size);pupil.position.z=-size*.57;pupil.scale.y=1.4;pupil.scale.z=.5;face.add(pupil);
 const lid=new T.Mesh(new T.TorusGeometry(size*.88,.055,8,20,Math.PI),gold);lid.position.z=-size*.35;face.add(lid);
 const highlight=new T.Object3D();
 mergeStaticModel(face,[pupil,lid,highlight]);this.eyes.push({group:face,pupil,lid,highlight});return rim;}

 limb(points:T.Vector3[],color:number,width=.1){return this.part(new T.TubeGeometry(new T.CatmullRomCurve3(points),16,width,6,false),color);}
 jester(boss:boolean){const s=boss?2.7:1;const points=[new T.Vector2(.1,0),new T.Vector2(.75,.1),new T.Vector2(.9,.5),new T.Vector2(.78,1),new T.Vector2(.4,1.5),new T.Vector2(.06,1.8)];const b=this.part(new T.LatheGeometry(points,40),boss?0x6c248e:0xdf538b,0,.22,0);b.scale.setScalar(s);b.material=creatureMaterial(0xffffff,'gel',creatureSkin(this.kind));
 for(const a of [-1,1]){this.eye(a*.3*s,1.3*s,-.68*s,.21*s);const horn=this.part(new T.ConeGeometry(.2*s,.85*s,8),0xf4c078,a*.63*s,1.75*s,.02);horn.rotation.z=-a*.6;const foot=this.part(new T.CapsuleGeometry(.15*s,.5*s,4,10),0x2ba9a9,a*.56*s,.26*s,-.15*s);foot.rotation.z=a*.5;this.legs.push(foot);this.limb([new T.Vector3(a*.6*s,.7*s,0),new T.Vector3(a*1.1*s,.4*s,-.3*s),new T.Vector3(a*1.35*s,.7*s,-.5*s)],0x73307e,.1*s);}
 const mouth=this.part(new T.TorusGeometry(.3*s,.095*s,10,24,Math.PI),0x341547,0,.92*s,-.81*s);mouth.rotation.z=Math.PI;for(let n=0;n<5;n++){const tooth=this.part(new T.ConeGeometry(.07*s,.18*s,3),0xffefd4,(n-2)*.115*s,.91*s,-.91*s);tooth.rotation.z=Math.PI;}
 const collar=this.part(new T.TorusGeometry(.8*s,.15*s,8,12),0xffca6b,0,.53*s,0);collar.rotation.x=Math.PI/2;for(let n=0;n<8;n++){const bead=this.part(new T.ConeGeometry(.11*s,.28*s,5),0x52d5d2,Math.cos(n*Math.PI/4)*.83*s,.4*s,Math.sin(n*Math.PI/4)*.83*s);bead.rotation.z=Math.PI;}
 if(boss){for(let n=0;n<5;n++){const crown=this.part(new T.ConeGeometry(.18,.7,4),0xffd87b,(n-2)*.35,5.1,0);crown.rotation.z=(n-2)*-.14;}for(const a of [-1,1]){this.part(new T.DodecahedronGeometry(.65),0xc89b50,a*2.1,2.1,0);this.part(new T.TorusGeometry(.4,.12,8,18),0x77e5dc,a*2.1,2.1,-.5);}}}
 scarab(){const shell=this.part(new T.SphereGeometry(.8,28,20),0x298f97,0,1.2,0);shell.scale.set(1,.8,1.3);(shell.material as T.MeshStandardMaterial).map=creatureSkin('BOTTY');this.part(new T.CylinderGeometry(.5,.65,.4,8),0xa97446,0,.7,0);this.eye(0,1.35,-.86,.31);for(const a of [-1,1]){this.limb([new T.Vector3(a*.2,1.8,0),new T.Vector3(a*.5,2.25,-.1),new T.Vector3(a*.8,2.1,-.3)],0xdcc184,.04);for(const z of [-.5,.55]){const leg=new T.Group();const upper=mesh(new T.CylinderGeometry(.09,.12,.8,8),0xd8aa73,a*.7,.65,z);upper.rotation.z=a*-.9;leg.add(upper);const lower=mesh(new T.ConeGeometry(.18,.55,6),0x194350,a*1,.25,z-.15);lower.rotation.z=a*.35;leg.add(lower);this.body.add(leg);this.legs.push(leg);}}for(let n=0;n<5;n++)this.part(new T.BoxGeometry(.08,.06,1.3),0xf2c15b,(n-2)*.16,1.84,0);}
 manta(){const shape=new T.Shape();shape.moveTo(0,.8);shape.bezierCurveTo(.6,.6,1.4,1.1,1.9,.3);shape.lineTo(1,-.5);shape.quadraticCurveTo(.45,-.15,0,-.6);shape.quadraticCurveTo(-.45,-.15,-1,-.5);shape.lineTo(-1.9,.3);shape.bezierCurveTo(-1.4,1.1,-.6,.6,0,.8);const wing=this.part(new T.ExtrudeGeometry(shape,{depth:.18,bevelEnabled:true,bevelThickness:.1,bevelSize:.09,bevelSegments:2,steps:1}),0x8e65cd,0,1.1,.1);wing.rotation.x=.18;(wing.material as T.MeshStandardMaterial).map=creatureSkin('BALLOONER');this.eye(0,1.45,-.14,.28);for(let n=-1;n<=1;n++){this.limb([new T.Vector3(n*.3,1,0),new T.Vector3(n*.6,.3,.2),new T.Vector3(n*.8,-.35,.55),new T.Vector3(n*.9,-.75,.1)],0x5de3d5,.045);this.part(new T.OctahedronGeometry(.1),0xffca6b,n*.9,-.75,.1);}for(const a of [-1,1]){this.limb([new T.Vector3(a*.25,1.6,-.08),new T.Vector3(a*1,1.8,-.08),new T.Vector3(a*1.6,1.45,-.08)],0xffc877,.03);}}
 tox(){const shell=this.part(new T.CapsuleGeometry(.65,.6,6,20),0x576438,0,.85,0);shell.rotation.z=Math.PI/2;(shell.material as T.MeshStandardMaterial).map=creatureSkin('TOX MUNCHER');(shell.material as T.MeshStandardMaterial).roughness=.65;this.eye(-.27,1.28,-.55,.17);this.eye(.27,1.28,-.55,.17);const jaw=this.part(new T.TorusGeometry(.38,.12,8,18,Math.PI),0xae76cb,0,.83,-.65);jaw.rotation.z=Math.PI;for(let n=0;n<5;n++){const spine=this.part(new T.ConeGeometry(.12,.55,5),0xbc82dc,(n-2)*.25,1.65,0);spine.rotation.z=(n-2)*-.15;}for(const a of [-1,1]){this.limb([new T.Vector3(a*.6,.7,0),new T.Vector3(a*1.1,.4,.1),new T.Vector3(a*1.25,.1,-.3)],0x9bbb5c,.12);}}
 hopper(){const body=this.part(new T.IcosahedronGeometry(.6,2),0x723448,0,1.3,0);(body.material as T.MeshStandardMaterial).map=creatureSkin('LAVA HOPPER');const core=this.part(new T.OctahedronGeometry(.35),0xffb958,0,1.4,-.45);core.material=glow(0xff882b);this.eye(0,1.4,-.7,.2);for(const a of [-1,1]){this.limb([new T.Vector3(a*.3,1.3,0),new T.Vector3(a*.9,.65,.35),new T.Vector3(a*.7,.15,-.25)],0xdeb87b,.1);const foot=this.part(new T.ConeGeometry(.16,.55,5),0x8b4356,a*.7,.22,-.3);foot.rotation.x=.5;this.legs.push(foot);const exhaust=this.part(new T.ConeGeometry(.14,.45,8),0xffb576,a*.3,1.9,.1);exhaust.material=glow(0xff8c38);}}
 samurai(){
  const torso=this.part(new T.CapsuleGeometry(.65,.7,8,20),0x294f76,0,1.5,0);(torso.material as T.MeshStandardMaterial).map=creatureSkin('SAMURAI');
  this.part(new T.SphereGeometry(.48,24,16),0x28344d,0,2.55,0);this.eye(-.2,2.55,-.4,.12);this.eye(.2,2.55,-.4,.12);
  const helmet=this.part(new T.SphereGeometry(.62,24,16,0,Math.PI*2,0,Math.PI/2),0x35b7bd,0,2.75,0);
  for(const a of [-1,1]){this.limb([new T.Vector3(a*.15,3,0),new T.Vector3(a*.55,3.4,0),new T.Vector3(a*.8,3.65,0)],0xffd76c,.08);
   for(let n=0;n<3;n++)this.part(new T.CylinderGeometry(.78+n*.07,.85+n*.07,.19,12),n%2?0x337ca0:0x35aab0,0,.85+n*.23,0);
   const shoulder=this.part(new T.CapsuleGeometry(.25,.5,6,12),0xffc779,a*.9,1.95,0);shoulder.rotation.z=a*.7;
   const leg=this.part(new T.CapsuleGeometry(.2,.65,6,12),0x273852,a*.4,.45,0);this.legs.push(leg);
  }
  const sword=this.part(new T.CylinderGeometry(.06,.11,2.8,4),0xb1fff1,1.2,1.7,-.55);this.sword=sword;sword.rotation.z=-.45; sword.material=glow(0x77e6dc);
  const guard=this.part(new T.TorusGeometry(.2,.05,8,20),0xffdb86,.7,.6,-.55);guard.rotation.x=Math.PI/2;
 }
 setVisualDetail(distance:number,low=false){this.visualDetail=!low&&distance<18;for(const eye of this.eyes){eye.lid.visible=this.visualDetail;eye.highlight.visible=this.visualDetail;}for(const detail of this.visualRotors)detail.visible=distance<36;}
 animate(t:number,moving:boolean){this.motion.update(t,moving);updateCreatureEyes(this);const lifted=Math.max(0,this.body.position.y);this.groundShadow.scale.setScalar(1+lifted*.1);(this.groundShadow.material as T.MeshBasicMaterial).opacity=this.kind==='BALLOONER'?.55:Math.max(.45,1-lifted*.28);}
}
