import {topHeight} from '../world/CastleFloors';
import {Practice} from './Practice';
import {LightningEffects} from '../effects/Lightning';
import {enemySizeMultiplier} from './EnemyScale';
import {challenges,challengeSpawns,nightmareUnlocked,unlockNightmare} from './Challenge';
import {RailRide} from '../rail/RailRide';
import {canBoard} from '../rail/RailCourse';
import {confirmSamurai,warningSign} from './Samurai';
import {DefeatEffects} from '../effects/Defeat';
import {showPreview} from '../ui/Preview';
import * as T from 'three';
import {Input} from '../input/Input';
import {keyboard} from '../input/KeyboardInput';
import {touch} from '../input/TouchInput';
import {World,mesh} from '../world/World';
import {configureStage,canMove} from '../world/layout';
import {doors,switches,toxic,lava} from '../world/Threats';
import {Fog} from '../map/Fog';
import {Sound} from '../audio/Sound';
import {Enemy} from './Enemy';
import {Arsenal} from './Progression';
import {Supplies} from './Supplies';
import {difficulty} from './Difficulty';
import {stages} from '../stages/Stages';
import {Atmosphere} from '../effects/Atmosphere';
import {Ending} from '../effects/Ending';
import {Card} from '../ui/Card';
import {names} from '../ui/Text';
import {el,updateHud,drawMap} from '../ui/Hud';
import {movePlayer} from './Player';
import {fire,updateEnemies,updateShots} from './Combat';
export type Shot={m:T.Mesh;v:T.Vector3;life:number;damage:number;enemy:boolean;kind:number;pierced?:Set<Enemy>};
type Particle={m:T.Mesh;v:T.Vector3;life:number};
export class Game {
 practice?:Practice;challenge=0;nightmare=nightmareUnlocked();
 railTest=new URLSearchParams(location.search).get('train');
 ride?:RailRide;battery=false;scene=new T.Scene();worldScene=new T.Scene();camera=new T.PerspectiveCamera(72,1,.1,240);renderer:T.WebGLRenderer;world!:World;atmosphere:Atmosphere;card:Card;ending?:Ending;
 lightning=new LightningEffects();defeat=new DefeatEffects();deathReadyAt=0;input=new Input();fog=new Fog();sound=new Sound();arsenal=new Arsenal();supplies=new Supplies();enemies:Enemy[]=[];shots:Shot[]=[];particles:Particle[]=[];shockwaves:{m:T.Mesh;r:number;hit:boolean}[]=[];
 routes=new Map<Enemy,{x:number;z:number}|null>();routeTimes=new Map<Enemy,number>();buffs=new Map<string,number>();state='title';stageIndex=0;stageFragment=false;stageTime=0;lightTime=0;keyCount=0;hp=100;energy=100;score=0;gate=false;coreEnabled=false;bossClear=false;
 position=new T.Vector3(10,1.65,42);safe=this.position.clone();velocity=new T.Vector3();vy=0;yaw=0;pitch=0;time=0;last=0;shotTime=0;hurtTime=0;mapTime=0;hudTime=0;toastTime=0;paralyzedUntil=0;paralysisImmuneUntil=0;shakeUntil=0;poisonUntil=0;poisonTick=0;purgeUntil=0;bridgeUntil=0;lavaTick=0;
 gun=new T.Group();gunStamp='';recoil=0;quality='auto';fps=60;frameCount=0;frameTime=0;selectedItem=0;failures=0;endingTime=0;encounters=0;orientationBlocked=false;mapOpen=false;
 constructor(){this.renderer=new T.WebGLRenderer({canvas:el('scene') as HTMLCanvasElement,antialias:!this.input.touch});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.atmosphere=new Atmosphere(this.scene);this.scene.add(this.camera);this.camera.add(this.gun);this.gun.rotation.set(-.08,.22,-.03);this.card=new Card(()=>this.hold(),()=>this.resume());this.loadStage(0);
 document.body.classList.toggle('touch',this.input.touch);keyboard(this.input,this.renderer.domElement,()=>this.pause());touch(this.input,()=>this.input.weapon=this.arsenal.next(this.input.weapon));this.bindUI();this.renderChallenges();this.resize();this.camera.position.set(12,4,48);this.camera.lookAt(30,2,28);if(this.railTest==='outdoor'||this.railTest==='space')this.prepareRailTest();requestAnimationFrame(t=>this.frame(t));}
 renderChallenges(){const panel=el('challenge');panel.hidden=this.railTest==='outdoor'||this.railTest==='space';el('challenge-options').replaceChildren();challenges.forEach((mode,n)=>{if(n===3&&!this.nightmare)return;const button=document.createElement('button');button.type='button';button.textContent=mode.name;button.setAttribute('aria-pressed',String(this.challenge===n));button.onclick=()=>{if(this.state!=='title'&&this.state!=='clear')return;this.challenge=n;this.loadStage(0);this.renderChallenges();};el('challenge-options').append(button);});}

 prepareRailTest(){this.loadStage(this.railTest==='space'?1:0);this.ride=new RailRide(this);this.state='title';el('overlay').querySelector('h1')!.textContent=this.railTest==='space'?'ほしぞら レール':'そらいろ レール';el('description').textContent='れっしゃだけ あそべるよ！ タップして てきを うとう。れっしゃは じどうで はしるよ。';el('overlay').querySelector('.chips')!.textContent='えきまで いこう！';el('overlay').querySelector('.instructions')!.textContent='みぎを よこへ なぞって むきを かえる・タップで うつ。れっしゃは じどうで はしるよ。';el('overlay').querySelector('footer')!.textContent='みぎを よこへ なぞって むきを かえる・タップで うつ';el('start').textContent='のる！ ↗';}
 bindUI(){el('practice').onclick=()=>{el('practice-menu').hidden=!el('practice-menu').hidden;};for(let n=0;n<5;n++)el(`practice-lesson-${n}`).onclick=()=>{el('practice-menu').hidden=true;this.practice=new Practice(this);this.practice.begin(n);};el('practice-exit').onclick=()=>this.practice?.stop();el('practice-next').onclick=()=>{const p=this.practice;if(!p)return;if(p.lesson<4)p.begin(p.lesson+1);else{p.stop();this.start();}};el('start').onclick=()=>this.start();el('quit').onclick=()=>{if(this.state!=='over'||performance.now()<this.deathReadyAt)return;this.reset();el('overlay').style.display='flex';el('hud').style.display='none';this.sound.music?.setMode('title');};el('restart').onclick=()=>{this.reset();this.start();};el('title-return').onclick=()=>{this.input.reset();document.exitPointerLock?.();this.reset();el('overlay').style.display='flex';el('hud').style.display='none';this.sound.music?.setMode('title');};el('pause').onclick=()=>this.pause();el('interact').onclick=()=>this.input.interact=true;el('item-select').onclick=()=>{el('item-picker').hidden=!el('item-picker').hidden;};for(const [id,value]of [['pick-potion',0],['pick-antidote',1]]as const)el(id).onclick=()=>{this.selectedItem=value;el('item-picker').hidden=true;updateHud(this);};el('item-use').onclick=()=>{if(this.selectedItem===0)this.input.heal=true;else this.input.antidote=true;};
 el('mapbutton').onclick=()=>{this.mapOpen=!this.mapOpen;el('mapbutton').classList.toggle('expanded',this.mapOpen);this.input.reset();};window.addEventListener('resize',()=>this.resize());window.addEventListener('contextmenu',e=>e.preventDefault());
 document.addEventListener('visibilitychange',()=>{if(document.hidden){if(this.state==='playing')this.pause();void this.sound.ctx?.suspend();}});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&this.state==='playing'&&!this.input.touch)this.pause();});}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setPixelRatio(this.quality==='low'?1:Math.min(devicePixelRatio,this.input.touch?1.25:1.75));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=this.quality==='high'||this.quality==='auto'&&!this.input.touch;const blocked=this.input.touch&&innerHeight>innerWidth;this.orientationBlocked=blocked;el('orientation').hidden=!blocked;if(blocked)this.input.reset();}
 loadStage(n:number){this.ride?.dispose();this.ride=undefined;this.battery=false;this.clearTransient();for(const e of this.enemies)this.disposeGroup(e.group);this.enemies=[];if(this.world){this.world.disposed=true;this.scene.remove(this.worldScene);this.disposeGroup(this.worldScene,true);}this.worldScene=new T.Scene();this.scene.add(this.worldScene);configureStage(n);this.stageIndex=n;this.world=new World(this.worldScene,this.challenge);this.worldScene.background=null;this.stageTime=this.lightTime=0;this.stageFragment=false;this.gate=false;this.coreEnabled=false;this.bossClear=false;this.encounters=0;el('toast').textContent='';el('danger').className='';el('threat').textContent='';this.routes.clear();this.routeTimes.clear();this.fog.reset();this.paralyzedUntil=this.paralysisImmuneUntil=this.shakeUntil=0;this.poisonUntil=this.purgeUntil=this.bridgeUntil=0;this.buffs.clear();this.position.set(stages[n].start[0],1.65,stages[n].start[1]);this.safe.copy(this.position);this.velocity.set(0,0,0);this.vy=0;this.yaw=this.pitch=0;this.hp=Math.max(80,this.hp);this.energy=100;this.supplies.potions=Math.max(1,this.supplies.potions);if(n>0)this.arsenal.upgrade(0);this.spawn();if(n===1)warningSign(this.world.group);this.atmosphere.group.visible=true;this.scene.fog=new T.Fog(0xb1dce7,45,150);this.atmosphere.update(n,0);if(this.sound.music?.fanfare)this.sound.music.restart();this.sound.music?.setStage(n);this.updateHud();this.drawMap();}
 spawn(){for(const [kind,x,z,yaw=0]of challengeSpawns(stages[this.stageIndex],this.challenge)){const e=new Enemy(kind,x,z);e.group.rotation.y=yaw;e.tier=kind==='KING PUNI'?[0,2,4][this.stageIndex]:this.stageIndex===0?0:this.stageIndex===1?1:3;e.baseScale=kind==='KING PUNI'?stages[this.stageIndex].boss.scale:[.84,1.26,1.74][this.stageIndex];e.hp=kind==='KING PUNI'?stages[this.stageIndex].boss.hp:e.hp*difficulty[e.tier].hp;if(kind==='SAMURAI'){e.hp=900;e.baseScale=1.5;e.tier=4;}e.baseScale*=enemySizeMultiplier;e.hp*=challenges[this.challenge].hp;e.maxHp=e.hp;e.group.scale.setScalar(e.baseScale);if(this.stageIndex>0&&kind==='PUNI'){for(const a of [-1,1])e.body.add(mesh(new T.ConeGeometry(.25,.7,8),0xe6c07d,a*.6,2,.1));const armor=mesh(new T.TorusGeometry(.85,.1,8,24),0x7bd9ee,0,.7,0);armor.rotation.x=Math.PI/2;e.body.add(armor);}if(this.stageIndex===2){e.floorY=topHeight(x,z);e.group.position.y=e.floorY;}this.enemies.push(e);this.scene.add(e.group);}}
 start(){if(this.state==='title'&&this.ride){this.resume();return;}if(this.state==='title'){this.sound.start();this.sound.music?.setMode('stage');el('overlay').style.display='none';el('hud').style.display='block';this.card.show('おもちゃのせかいへ ようこそ！',stages[0].story+(this.input.touch?'\nうえ・したで いどう・ひだりで カニあるき・みぎで むきを かえる\nタップした ところへ うつ\nいどうしながら べつの ゆびで うてるよ':''),'🧸');}else if(this.state==='over'){if(performance.now()<this.deathReadyAt)return;el('quit').hidden=true;if(this.ride){this.ride.restart();this.resume();}else{this.keyCount=this.stageIndex;this.loadStage(this.stageIndex);this.resume();}}else if(this.state==='clear'){this.reset();this.start();}else this.resume();}
 resume(){el('title-return').hidden=true;el('pause-controls').hidden=true;el('overlay').classList.remove('game-over');el('challenge').hidden=true;this.state='playing';el('overlay').style.display='none';el('hud').style.display='block';this.input.reset();this.sound.start();if(this.ride){this.sound.music?.setMode('boss');this.sound.music?.setCombat(4);}else if(this.gate&&!this.bossClear)this.sound.music?.setMode('boss');else this.sound.music?.setStage(this.stageIndex);this.sound.music?.setPaused(false);if(!this.input.touch)this.renderer.domElement.requestPointerLock?.()?.catch(()=>{});}
 hold(){this.state='card';this.input.reset();this.sound.music?.setPaused(true);document.exitPointerLock?.();}
 pause(){el('challenge').hidden=true;if(this.state==='playing'){this.state='paused';this.input.reset();this.sound.music?.setPaused(true);document.exitPointerLock?.();el('overlay').style.display='flex';el('start').textContent='つづける ↗';el('description').textContent='ひとやすみ。ぼうけんは ここから つづくよ。';el('restart').hidden=false;el('title-return').hidden=false;el('pause-controls').hidden=false;el('pause-controls').textContent=this.input.touch?'ゆびで そうさ\nどちらがわでも うえ・した：まえ・うしろ\nひだりを よこへ：カニあるき\nみぎを よこへ：むきを かえる\nどこでも タップ：いどうしながら うつ\nアイテムを おして えらぶ → つかう':'キーボードと マウス\nダブリュー・エー・エス・ディー：いどう\nマウス：みまわす ／ ひだりクリック：うつ\nシフト：ダッシュ\nイー：スイッチ ／ キュー：ポーション\nアール：どくけし ／ 1〜4：ぶき\nエスケープ：ひとやすみ';}else if(this.state==='paused')this.resume();}
 reset(){el('title-return').hidden=true;el('ending-story').hidden=true;el('ending-caption').hidden=true;el('pause-controls').hidden=true;this.practice=undefined;document.body.classList.remove('practicing');el('practice-hud').hidden=true;el('practice-menu').hidden=true;el('overlay').classList.remove('game-over');this.ending?.dispose();this.ending=undefined;this.sound.music?.restart();this.card.seen.clear();this.card.open=false;el('card').hidden=true;this.arsenal.reset();this.supplies.reset();this.hp=100;this.input.weapon=0;this.selectedItem=0;this.keyCount=this.score=0;this.failures=0;this.gunStamp='';this.loadStage(0);this.state='title';el('quit').hidden=true;el('restart').hidden=true;el('start').textContent='はじめる ↗';el('description').textContent='みっつの ほしを みつけて おもちゃのせかいを たすけよう！';this.renderChallenges();if(this.railTest==='outdoor'||this.railTest==='space')this.prepareRailTest();}
 update(dt:number){if(this.state!=='playing'||this.orientationBlocked||this.mapOpen)return;this.time+=dt;if(this.practice){this.practice.update(dt);return;}if(this.ride){this.ride.update(dt);return;}this.stageTime+=dt;this.energy=Math.min(100,this.energy+dt*6);if(!this.arsenal.unlocked[this.input.weapon])this.input.weapon=0;movePlayer(this,dt);if(this.input.fire)fire(this);for(const [k,t]of this.buffs)if(this.time>t)this.buffs.delete(k);this.collect();if(this.state!=='playing')return;updateEnemies(this,dt);updateShots(this,dt);this.updateThreats(dt);if(this.state!=='playing'||this.ride)return;this.world.update(this.time);this.lightTime=Math.max(this.lightTime+dt,T.MathUtils.lerp(this.lightTime,Math.max(this.stageTime,this.stageFragment?115:0,this.gate?150:0),1-Math.exp(-dt*.25)));this.atmosphere.update(this.stageIndex,this.lightTime);this.updateParticles(dt);
 if(this.time>this.mapTime){this.mapTime=this.time+.16;this.fog.reveal(this.position.x,this.position.z,this.gate,this.position.y);this.drawMap();}if(this.time>this.hudTime){this.hudTime=this.time+.1;this.updateHud();}if(this.time>this.toastTime)el('toast').textContent='';this.sound.music?.setCombat(this.enemies.filter(e=>e.alive&&e.brain.state!=='Idle').length);if(this.gate&&!this.bossClear)this.sound.music?.setMode('boss');}
 collect(){for(const item of this.world.items)if(!item.taken&&Math.hypot(item.x-this.position.x,item.z-this.position.z)<1.7&&Math.abs(item.mesh.position.y-this.position.y)<2){item.taken=true;item.mesh.visible=false;this.score+=50;this.sound.effect(1100);this.burst(item.mesh.position,0x9affe1);
 if(item.kind==='KEY'){this.stageFragment=true;this.keyCount=this.stageIndex+1;this.world.portal.visible=this.bossClear;this.notify('ほしのかけらを みつけた！');}else this.takeSupply(item.kind);if(this.card.item(item.kind,this.input.touch))showPreview(this.renderer,item.mesh,item.kind==='BUBBLE MODULE'?1:item.kind==='STAR MODULE'?2:-1);if(this.card.open)return;}}
 takeSupply(k:string){switch(k){case 'BATTERY':this.battery=true;break;case 'POTION':this.supplies.potions++;break;case 'BIG POTION':this.supplies.bigPotions++;break;case 'ANTIDOTE':this.supplies.antidotes++;this.selectedItem=1;break;case 'ARMOR CELL':this.supplies.armor=Math.min(100,this.supplies.armor+50);break;case 'AMMO CELL':this.energy=Math.min(100,this.energy+60);break;case 'BUBBLE MODULE':this.arsenal.unlock(1);this.input.weapon=1;break;case 'KATANA':this.arsenal.unlock(3);this.input.weapon=3;break;case 'STAR MODULE':this.arsenal.unlock(2);this.input.weapon=2;break;case 'BUBBLE UPGRADE':this.arsenal.upgrade(1);break;case 'NOVA UPGRADE':this.arsenal.upgrade(2);break;default:this.buffs.set(k,this.time+(k==='LAVA CHARM'?35:18));}this.notify(`${names[k]??'アイテム'}を ひろった`);return true;}
 updateThreats(_dt:number){const exit=stages[this.stageIndex].exit,nearTrain=this.bossClear&&Math.hypot(this.position.x-exit[0],this.position.z-exit[1])<3.3&&(this.stageIndex!==2||this.position.y>12);const boarding=nearTrain&&canBoard(this.bossClear,this.stageFragment,this.battery);if(nearTrain){el('interact').hidden=false;el('interact').textContent=boarding?'🔋 でんちを セット':!this.battery?'でんちを ひろおう':'ほしを ひろおう';if(this.input.interact&&boarding){this.input.interact=false;this.boardTrain();return;}this.input.interact=false;}const nearest=switches.map(s=>({s,d:Math.hypot(this.position.x-s.x,this.position.z-s.z,this.stageIndex===2?this.position.y-1.65-topHeight(s.x,s.z):0)})).sort((a,b)=>a.d-b.d)[0];if(!nearTrain)el('interact').hidden=!nearest||nearest.d>3;if(!nearTrain)el('interact').textContent=nearest?.s.kind==='samurai'?'⚠ とびらを あける':'◎ おす';if(this.input.interact&&nearest?.d<=3)this.activateSwitch(nearest.s);this.input.interact=false;
 const poison=toxic(this.position.x,this.position.z)&&this.position.y<2.3&&this.time>this.purgeUntil;if(poison&&!this.buffs.has('ANTIDOTE'))this.poisonUntil=this.time+5;if(this.poisonUntil>this.time&&this.time>this.poisonTick){this.poisonTick=this.time+1;this.hurt(3);}
 const burning=lava(this.position.x,this.position.z)&&this.position.y<2.3&&this.time>this.purgeUntil;if(burning&&this.time>this.lavaTick){this.lavaTick=this.time+.8;this.hurt(this.buffs.has('LAVA CHARM')?2:10);}
 if(this.input.heal){const before=this.hp;this.hp=this.supplies.heal(this.hp);this.notify(this.hp>before?'たいりょくが もどった！':'ポーションが ない / たいりょく まんたん');}this.input.heal=false;
 if(this.input.antidote){if(this.supplies.antidote()){this.poisonUntil=0;this.buffs.set('ANTIDOTE',this.time+4);this.notify('どくが なおった！');}else this.notify('どくけしを さがそう');}this.input.antidote=false;
 for(const b of this.world.bridges)b.visible=this.time<this.bridgeUntil;el('danger').className=this.poisonUntil>this.time?'poison':burning?'lava':this.hp<30?'active':'';el('threat').textContent=this.paralyzedUntil>this.time?'⚡ まひ · '+Math.ceil(this.paralyzedUntil-this.time):this.poisonUntil>this.time?'☣ どく · 🌿で なおそう':burning?'♨ ようがん · とんで よけよう':'';}
 activateSwitch(s:typeof switches[number]){if(this.stageIndex===2&&Math.abs(this.position.y-1.65-topHeight(s.x,s.z))>2)return;if(s.kind==='samurai'){confirmSamurai(this);return;}if(s.kind==='bridge'){this.bridgeUntil=this.time+25;this.notify('あしばが うごいた！ · 25');}else if(s.kind==='purge'){this.purgeUntil=this.time+30;this.poisonUntil=0;this.notify('あぶない あわが とまった！');}else if(s.kind==='core'){{this.gate=this.coreEnabled=true;this.world.gate.visible=false;this.notify('ほしの とびらが ひらいた！');}}else{const d=doors[s.door];if(!d)return;if(d.open&&d.cells.some(([c,r])=>Math.floor(this.position.x/4)===c&&Math.floor(this.position.z/4)===r)){this.notify('とびらから はなれて おそう');return;}d.open=!d.open;this.notify(d.open?'どこかで とびらが ひらいた！':'とびらが とじた！');}if((this.stageIndex===0&&s.door===3||this.stageIndex===1&&s.door===2)&&doors[s.door]?.open||s.kind==='core')this.startBoss();this.sound.effect(550);}
 startBoss(){if(this.bossClear)return;this.gate=true;const e=this.enemies.find(e=>e.kind==='KING PUNI'&&e.alive);if(e){e.brain.hit(this.position.x,this.position.z,this.time);e.brain.surprisedUntil=this.time+.35;e.alert=true;e.cooldown=0;}this.notify('ボスが くる！ よけながら たたかおう');}
 damage(e:Enemy,n:number){if(!e.alive||e.kind==='SAMURAI'&&!doors[5]?.open)return;e.brain.hit(this.position.x,this.position.z,this.time);e.alert=true;e.state='Alert';e.cooldown=Math.max(e.cooldown,.4);if(e.kind==='LAVA HOPPER'&&this.input.weapon===0)n*=.7;e.hp-=n;this.burst(e.group.position.clone().add(new T.Vector3(0,e.baseScale,0)));if(e.hp<=0){e.alive=false;this.defeat.add(this,e);this.score+=100;this.sound.effect(980);if(e.kind==='SAMURAI'){this.world.item('KATANA',e.group.position.x,e.group.position.z,0x99ffee);this.notify('さむらいを たおした！ カタナが あらわれた！');}if(e.kind==='KING PUNI'){this.bossClear=true;this.world.item('BATTERY',e.group.position.x,e.group.position.z,0x80e8ab);doors[stages[this.stageIndex].boss.exitDoor].open=true;this.world.portal.visible=true;this.sound.music?.clear();this.notify('ボスを たおした！ でんちを ひろって れっしゃへ！');}}}
 hurt(n:number){if(this.practice)n=Math.min(n,Math.max(0,this.hp-40));if(this.time<this.hurtTime||this.state!=='playing')return;this.hurtTime=this.time+.65;this.shakeUntil=this.time+.32;this.hp=Math.max(0,this.hp-this.supplies.absorb(n));this.sound.impact();if(this.hp<=0){this.failures++;this.state='over';el('overlay').classList.add('game-over');el('challenge').hidden=true;this.input.reset();this.sound.music?.setPaused(true);document.exitPointerLock?.();el('overlay').style.display='flex';this.deathReadyAt=performance.now()+700;el('hud').style.display='none';el('start').textContent='もういっかい';el('description').textContent='ざんねん！もういっかい！';el('quit').hidden=false;el('restart').hidden=true;}}
 boardTrain(){if(this.ride||!canBoard(this.bossClear,this.stageFragment,this.battery))return;this.card.show('でんちを セットした！',this.stageIndex===0?'そらの レールを かけぬけよう！\nタップか クリックで てきを うとう。\nえきに ついたら ステージクリア！':this.stageIndex===1?'ほしぞらの トンネルへ しゅっぱつ！\nタップか クリックで てきを うとう。\nえきに ついたら ステージクリア！':'にじの レールで おもちゃばこへ！\nタップか クリックで てきを うとう。','🚂',()=>{this.battery=false;this.ride=new RailRide(this);this.resume();});}
 arriveTrain(){if(this.railTest==='outdoor'||this.railTest==='space'){this.card.show('えきに とうちゃく！','コースクリア！\nもういちど れっしゃで あそぼう！','🚂',()=>{this.ride?.restart();this.resume();});return;}const next=this.stageIndex+1;this.card.show('えきに とうちゃく！',next<3?`ステージクリア！\nつぎは ${stages[next].name}`:'ステージクリア！\nにじのほしを もとに もどそう！','🚂',()=>{this.ride?.dispose();this.ride=undefined;if(next<3){this.loadStage(next);this.resume();}else this.beginEnding();});}
 beginEnding(){if(this.challenge===2){unlockNightmare();this.nightmare=true;}this.state='ending';this.input.reset();this.endingTime=0;this.sound.music?.clear();this.ending=new Ending(this.scene,this.camera,new T.Vector3(stages[this.stageIndex].boss.x,this.stageIndex===2?12:0,stages[this.stageIndex].boss.z));el('hud').style.display='none';document.exitPointerLock?.();const b=stages[this.stageIndex].boss;this.camera.position.set(b.x-7,this.stageIndex===2?16:4,b.z+12);this.camera.lookAt(b.x,this.stageIndex===2?20:8,b.z);}
 finish(win:boolean){if(win)this.beginEnding();else{this.hp=0;this.hurtTime=0;this.hurt(1);}}
 updateEnding(dt:number){this.endingTime+=dt;el('ending-story').hidden=this.endingTime<13||this.endingTime>=38;el('ending-story').classList.toggle('school',this.endingTime>=23);el('ending-caption').hidden=false;el('ending-caption').textContent=this.endingTime<6?'みっつの ほしが ひとつに…':this.endingTime<13?'にじのほしが もどった！':this.endingTime<20?'おもちゃばこでの ぼうけん。わすれないよ。':this.endingTime<23?'また あそぼうね':this.endingTime<38?'いってきます！':' ';this.ending?.update(this.endingTime);if(this.ending?.returned&&this.worldScene.visible){this.worldScene.visible=false;for(const e of this.enemies)e.group.visible=false;this.atmosphere.group.visible=false;this.atmosphere.update(0,0);this.scene.background=new T.Color(0xc4e8f4);this.scene.fog=null;}if(this.endingTime>=38){this.state='clear';el('ending-story').hidden=true;el('ending-caption').hidden=true;this.renderChallenges();el('overlay').style.display='flex';el('start').textContent='また あそぶ ↻';el('description').textContent='にじのほしが もどった！\nおもちゃのせかいを たすけたよ！\nおへやでは じかんが ほとんど たっていない。\nおもちゃばこから「また あそぼうね」';if(this.challenge===2)el('description').textContent+='\nあくむが あそべるように なった！';}}
 notify(s:string){el('toast').textContent=s;this.toastTime=this.time+3;}
 burst(pos:T.Vector3,color=0xffdf79){const count=this.input.touch?5:9;for(let n=0;n<count;n++){if(this.particles.length>90)break;const m=mesh(new T.OctahedronGeometry(.08),color);m.position.copy(pos);this.scene.add(m);this.particles.push({m,v:new T.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),life:.6});}}
 updateParticles(dt:number){this.lightning.update(dt);this.defeat.update(this,dt);for(let n=this.particles.length-1;n>=0;n--){const p=this.particles[n];p.life-=dt;p.v.y-=8*dt;p.m.position.addScaledVector(p.v,dt);p.m.scale.setScalar(Math.max(.01,p.life));if(p.life<=0){this.dispose(p.m);this.particles.splice(n,1);}}}
 clearTransient(){this.lightning.clear();this.defeat.clear(this);for(const p of [...this.shots,...this.particles])this.dispose(p.m);for(const w of this.shockwaves)this.dispose(w.m);this.shots=[];this.particles=[];this.shockwaves=[];}
 dispose(m:T.Mesh){this.scene.remove(m);m.geometry.dispose();(m.material as T.Material).dispose();}
 disposeGroup(group:T.Object3D,textures=false){group.removeFromParent();const geos=new Set<T.BufferGeometry>(),mats=new Set<T.Material>();group.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points){geos.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])mats.add(m);}});for(const x of geos)x.dispose();const maps=new Set<T.Texture>();for(const x of mats){if(textures&&x instanceof T.MeshStandardMaterial)for(const t of [x.map,x.bumpMap,x.normalMap,x.roughnessMap,x.metalnessMap,x.emissiveMap])if(t)maps.add(t);x.dispose();}for(const x of maps)x.dispose();}
 updateHud(){updateHud(this);}drawMap(){drawMap(this);}
 frame(ms:number){const elapsed=Math.max(.001,(ms-this.last)/1000),dt=Math.min(elapsed,.04);this.last=ms;if(this.state==='playing')this.update(dt);else if(this.state==='ending')this.updateEnding(dt);else if(this.state==='title'&&this.ride){this.ride.pose(0);}else if(this.state==='title'){this.world.update(ms/1000);this.camera.position.x=12+Math.sin(ms*.0002)*2;this.camera.lookAt(30,2,28);}this.gun.visible=this.state==='playing'||this.state==='review'&&!this.ending;this.renderer.render(this.scene,this.camera);this.frameCount++;this.frameTime+=elapsed;if(this.frameTime>3){this.fps=this.frameCount/this.frameTime;if(this.quality==='auto'&&this.fps<32){this.renderer.setPixelRatio(1);this.renderer.shadowMap.enabled=false;}this.frameCount=this.frameTime=0;}requestAnimationFrame(t=>this.frame(t));}
}
