import {test,expect,type Page,type CDPSession} from '@playwright/test';
async function run<T>(page:Page,fn:(g:any)=>T|Promise<T>):Promise<T>{return page.evaluate(async source=>{const {game}=await import(Array.from(document.scripts).find(s=>s.src.includes('/src/main.ts'))!.src);return (0,eval)(`(${source})`)(game);},fn.toString());}
test('nightmare durability, samurai reward, cursed swing and boss exception',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#start').click();await page.locator('#card-close').click();await expect(page.locator('#render-loading')).toBeHidden({timeout:30000});
 const health=await run(page,g=>{g.challenge=3;g.state='paused';const results=[];for(let n=0;n<3;n++){g.loadStage(n);results.push({ordinary:[...new Set(g.enemies.filter((e:any)=>!['SAMURAI','KING PUNI'].includes(e.kind)).map((e:any)=>e.hp))],samurai:g.enemies.find((e:any)=>e.kind==='SAMURAI')?.hp,boss:g.enemies.find((e:any)=>e.kind==='KING PUNI')?.hp});}g.loadStage(1);for(const e of g.enemies)if(e.kind!=='SAMURAI'){e.alive=false;e.group.visible=false;}return results;});expect(health.map(h=>h.ordinary)).toEqual([[570],[570],[570]]);expect(health[1].samurai).toBe(5700);expect(health.map(h=>h.boss)).toEqual([4275,6412.5,8550]);
 const hits=await run(page,async g=>{const {doors}=await import('/src/world/Threats.ts');const {thunderbolt}=await import('/src/game/Thunderbolt.ts');doors[5].open=true;g.gate=true;g.arsenal.unlock(2);g.arsenal.upgrade(2);g.input.weapon=2;g.position.set(22,1.65,20);const sam=g.enemies.find((e:any)=>e.kind==='SAMURAI');sam.alert=true;sam.group.position.set(22,0,14);const hp=[];for(let n=0;n<20;n++){thunderbolt(g,g.position.clone().set(0,0,-1));hp.push(sam.hp);}return {hp,alive:sam.alive,drop:g.world.items.some((i:any)=>i.kind==='MURASAME')};});expect(hits.hp[18]).toBe(285);expect(hits.hp[19]).toBe(0);expect(hits.alive).toBe(false);expect(hits.drop).toBe(true);
 await run(page,g=>{for(const i of g.world.items)if(i.kind!=='MURASAME'){i.taken=true;i.mesh.visible=false;}const item=g.world.items.find((i:any)=>i.kind==='MURASAME');g.position.set(item.x,1.65,item.z);g.collect();g.camera.position.copy(g.position);g.updateHud();});
 await expect(page.locator('#card')).toContainText('むらさめ');await expect(page.locator('#card')).toContainText('たいりょくを 1');await page.screenshot({path:'screenshots/cursed/PC-acquisition.png'});await page.locator('#card-close').click();
 await run(page,g=>{g.state='playing';g.hp=60;g.shotTime=0;g.input.weapon=3;g.updateHud();});await expect(page.locator('#weaponname')).toHaveText('むらさめ');await expect(page.locator('#shot-status')).toHaveText('ふるたび たいりょく -1');await expect(page.locator('#render-loading')).toBeHidden({timeout:30000});await page.mouse.move(640,350);await page.mouse.down();await expect.poll(()=>run(page,g=>g.hp)).toBe(59);await page.mouse.up();
 const mist=await run(page,g=>{const m=g.gun.userData.murasameMist;return {count:m.puffs.length,opacity:m.puffs.map((p:any)=>p.material.opacity),points:m.puffs.map((p:any)=>p.position.toArray()),map:m.puffs[0].material.map.image.width};});expect(mist.count).toBe(6);expect(mist.map).toBe(64);expect(mist.opacity.every((v:number)=>v>=0&&v<=.66)).toBe(true);await page.waitForTimeout(700);expect(await run(page,g=>g.gun.userData.murasameMist.puffs.map((p:any)=>p.position.toArray()))).not.toEqual(mist.points);await page.screenshot({path:'screenshots/cursed/PC-murasame.png'});
 const result=await run(page,g=>{g.state='paused';g.loadStage(0);g.gate=true;g.input.weapon=3;g.position.set(26,1.65,38);const puni=g.enemies.find((e:any)=>e.kind==='PUNI'),boss=g.enemies.find((e:any)=>e.kind==='KING PUNI');for(const e of g.enemies){e.alive=e===puni||e===boss;e.group.visible=e.alive;}puni.group.position.set(26,0,34);boss.group.position.set(27,0,34);boss.hp=boss.maxHp=5600;g.hp=10;g.shotTime=0;return Promise.all([import('/src/game/Katana.ts')]).then(([k])=>{k.slash(g);return {puni:puni.alive,boss:boss.hp,hp:g.hp};});});expect(result).toEqual({puni:false,boss:5240,hp:9});expect(errors).toEqual([]);
});
type Finger={id:number;x:number;y:number};
test('parupun explains the half-chance effect on a phone',async({browser})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true}),page=await context.newPage();await page.goto('/');await page.locator('#start').click();await page.locator('#card-close').click();await expect(page.locator('#render-loading')).toBeHidden({timeout:30000});
 await run(page,g=>{g.world.item('PARUPUN',g.position.x,g.position.z,0xd3a8ff);g.collect();});await expect(page.locator('#card')).toContainText('はんぶんの かくりつで');await expect(page.locator('#card')).toContainText('でも もうはんぶんは');await expect(page.locator('#card')).toContainText('ボスには きかないよ');await expect(page.locator('#card-icon img')).toBeVisible({timeout:30000});expect(await page.locator('#card-icon img').evaluate((img:HTMLImageElement)=>{const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);return [...ctx.getImageData(0,0,256,256).data].filter((v,n)=>n%4===3&&v>20).length;})).toBeGreaterThan(100);await page.screenshot({path:'screenshots/cursed/parupun-half-chance-phone.png'});await page.locator('#card-close').click();await expect(page.locator('#card')).toBeHidden();await context.close();
});
for(const mobile of [false,true])test(`murasame mist rendering budget ${mobile?'phone':'PC'}`,async({browser})=>{
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},hasTouch:mobile,isMobile:mobile}),page=await context.newPage();await page.goto('/');await page.locator('#start').click();await page.locator('#card-close').click();await expect(page.locator('#render-loading')).toBeHidden({timeout:30000});
 await run(page,g=>{g.arsenal.unlock(3);g.arsenal.murasame=true;g.input.weapon=3;for(const e of g.enemies){e.alive=false;e.group.visible=false;}for(const i of g.world.items){i.taken=true;i.mesh.visible=false;}g.position.set(26,1.65,38);g.camera.position.copy(g.position);g.updateHud();});await page.waitForTimeout(300);
 const metrics=await run(page,async g=>{const mist=g.gun.userData.murasameMist,geometries=new Set(mist.puffs.map((p:any)=>p.geometry)),textures=new Set(mist.puffs.map((p:any)=>p.material.map));g.renderer.info.reset();g.renderer.render(g.scene,g.camera);const withMist=g.renderer.info.render.calls;for(const p of mist.puffs)p.visible=false;g.renderer.info.reset();g.renderer.render(g.scene,g.camera);const without=g.renderer.info.render.calls;for(const p of mist.puffs)p.visible=true;
  const gaps:number[]=[],start=performance.now();let last=start;return await new Promise(resolve=>{const frame=(t:number)=>{gaps.push(t-last);last=t;if(t-start<3000)requestAnimationFrame(frame);else{gaps.sort((a,b)=>a-b);resolve({extraCalls:withMist-without,geometries:geometries.size,textures:textures.size,frames:gaps.length,p95:gaps[Math.floor(gaps.length*.95)]});}};requestAnimationFrame(frame);});});
 console.log('mist rendering',mobile?'phone':'PC',metrics);expect(metrics).toMatchObject({extraCalls:6,geometries:1,textures:1});expect((metrics as any).p95).toBeLessThan(75);await page.screenshot({path:`screenshots/cursed/${mobile?'phone':'PC'}-mist-confirmed.png`});await context.close();
});
test('rail still supports selected potion and elixir',async({page})=>{
 await page.goto('/?train=outdoor');await page.locator('#start').click();await run(page,g=>{g.hp=35;g.supplies.potions=2;g.supplies.elixirs=1;g.selectedItem=0;g.updateHud();});await page.locator('#item-use').click();await expect.poll(()=>run(page,g=>g.supplies.potions)).toBe(1);expect(await run(page,g=>g.hp)).toBe(65);
 await page.locator('#item-select').click();await page.locator('#pick-elixir').click();await page.locator('#item-use').click();await expect.poll(()=>run(page,g=>g.supplies.elixirs)).toBe(0);expect(await run(page,g=>g.hp)).toBe(100);expect(await run(page,g=>!!g.ride)).toBe(true);
});
async function touch(cdp:CDPSession,type:string,points:Finger[]){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});}
async function press(page:Page,cdp:CDPSession,held:Finger,id:string,n:number){const r=(await page.locator(`#${id}`).boundingBox())!,p={id:n,x:r.x+r.width/2,y:r.y+r.height/2};await touch(cdp,'touchStart',[held,p]);await touch(cdp,'touchEnd',[p]);}
for(const [name,w,h]of [['small-phone',360,800],['phone',390,844],['landscape',844,390],['tablet',1024,768],['large-tablet',1366,1024]]as const)test(`rare selection while moving and purple mist ${name}`,async({browser})=>{
 test.setTimeout(120000);const context=await browser.newContext({viewport:{width:w,height:h},hasTouch:true,isMobile:true}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');if(h>w)await page.setViewportSize({width:h,height:w});await page.locator('#start').click();await page.locator('#card-close').click();await expect(page.locator('#render-loading')).toBeHidden({timeout:30000});
 await run(page,g=>{g.hp=35;g.supplies.elixirs=2;g.supplies.parupuns=2;g.arsenal.unlock(3);g.arsenal.murasame=true;g.input.weapon=3;for(const e of g.enemies){e.alive=false;e.group.visible=false;}for(const i of g.world.items){i.taken=true;i.mesh.visible=false;}g.updateHud();});const cdp=await context.newCDPSession(page),size=page.viewportSize()!,origin={id:7,x:size.width*.33,y:size.height*.6},held={...origin,x:origin.x+40};await touch(cdp,'touchStart',[origin]);await touch(cdp,'touchMove',[held]);await expect.poll(()=>run(page,g=>g.input.mx)).toBeGreaterThan(.4);
 await press(page,cdp,held,'item-select',8);await expect(page.locator('#item-picker')).toBeVisible();const boxes=await page.locator('#item-picker button').evaluateAll(buttons=>buttons.map(b=>{const r=b.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:r.width,h:r.height};}));expect(boxes.every(b=>b.x>=0&&b.y>=0&&b.right<=size.width&&b.bottom<=size.height&&b.h>=48)).toBe(true);await page.screenshot({path:`screenshots/cursed/${name}-picker.png`});await press(page,cdp,held,'pick-elixir',9);await run(page,g=>{g.poisonUntil=g.time+5;g.paralyzedUntil=g.time+3;});await press(page,cdp,held,'item-use',10);await expect.poll(()=>run(page,g=>g.supplies.elixirs)).toBe(1);expect(await run(page,g=>({hp:g.hp,poison:g.poisonUntil,paralyzed:g.paralyzedUntil}))).toEqual({hp:100,poison:0,paralyzed:0});expect(await run(page,g=>g.input.mx)).toBeGreaterThan(.4);
 await press(page,cdp,held,'item-select',11);await press(page,cdp,held,'pick-parupun',12);await press(page,cdp,held,'item-use',13);await expect.poll(()=>run(page,g=>g.supplies.parupuns)).toBe(1);expect(await run(page,g=>g.input.mx)).toBeGreaterThan(.4);await touch(cdp,'touchEnd',[]);await page.screenshot({path:`screenshots/cursed/${name}-murasame.png`});expect(errors).toEqual([]);await context.close();
});
