import {test,expect} from '@playwright/test';
for(const [name,w,h,touch]of [['desktop',1280,720,false],['small-phone',360,800,true],['phone',390,844,true],['landscape',844,390,true],['tablet',1024,768,true],['large-tablet',1366,1024,true]] as const){test(name,async({browser})=>{const context=await browser.newContext({viewport:{width:w,height:h},hasTouch:touch,isMobile:touch});const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(`${e.text()} ${e.location().url}`);});await page.goto('/');if(touch&&h>w){await expect(page.locator('#orientation')).toBeVisible();await page.screenshot({path:`screenshots/v3/${name}-orientation.png`});await page.setViewportSize({width:h,height:w});}await expect(page.locator('#start')).toHaveText(/はじめる/);await page.screenshot({path:`screenshots/v3/${name}-title.png`});await page.locator('#start').click();await expect(page.locator('#card')).toBeVisible();await page.locator('#card-close').click();await expect(page.locator('#hud')).toBeVisible();await page.screenshot({path:`screenshots/v3/${name}-stage1.png`});if(touch)await page.locator('#pause').click();else await page.keyboard.press('Escape');await expect(page.locator('#title-return')).toBeVisible();await page.screenshot({path:`screenshots/v3/${name}-pause.png`});await page.locator('#title-return').click();await expect(page.locator('#challenge')).toBeVisible();await expect(page.locator('#hud')).toBeHidden();await page.locator('#practice').click();await page.locator('#practice-lesson-0').click();await page.locator('#card-close').click();if(touch)await page.locator('#practice-exit').click();else{await page.keyboard.press('Escape');await page.locator('#title-return').click();}await expect(page.locator('#challenge')).toBeVisible();await page.goto('/tests-runner.html');await expect(page.locator('#testresults')).toContainText(/\d+ CHECKS COMPLETE/,{timeout:30000});await expect(page.locator('#testresults')).not.toContainText('FAIL');expect(errors).toEqual([]);await context.close();});}

test('mobile without pointer-lock API can start, move and finish the campaign checks',async({browser})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true});
 await context.addInitScript(()=>{Object.defineProperty(document,'exitPointerLock',{value:undefined,configurable:true});Object.defineProperty(HTMLElement.prototype,'requestPointerLock',{value:undefined,configurable:true});});
 const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.locator('#start').click();await expect(page.locator('#card')).toBeVisible();await page.locator('#card-close').click();await expect(page.locator('#look')).toBeVisible();
 await page.goto('/tests-runner.html?nopointerlock');await expect(page.locator('#testresults')).toContainText(/\d+ CHECKS COMPLETE/,{timeout:30000});expect(errors).toEqual([]);await context.close();
});
