import {test,expect,type Page} from '@playwright/test';
async function run<T>(page:Page,fn:(g:any)=>T|Promise<T>):Promise<T>{return page.evaluate(async source=>{const {game}=await import(Array.from(document.scripts).find(s=>s.src.includes('/src/main.ts'))!.src);return (0,eval)(`(${source})`)(game);},fn.toString());}
for(const [name,width,height,mobile]of [['PC',1280,720,false],['phone',844,390,true],['tablet',1024,768,true]]as const)test(`nightmare boss phases and safe arena ${name}`,async({browser})=>{
 test.setTimeout(150000);const context=await browser.newContext({viewport:{width,height},hasTouch:mobile,isMobile:mobile}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#start').click();await page.locator('#card-close').click();
 await run(page,async g=>{g.challenge=3;g.loadStage(2);await g.visuals.ready;for(const e of g.enemies){e.alive=e.kind==='KING PUNI';e.group.visible=e.alive;}const boss=g.enemies.find((e:any)=>e.kind==='KING PUNI');g.position.set(90,13.65,28);g.safe.copy(g.position);g.camera.position.copy(g.position);g.camera.lookAt(boss.group.position.clone().add(g.position.clone().set(0,boss.baseScale*2.2,0)));g.yaw=g.camera.rotation.y;g.pitch=g.camera.rotation.x;g.gate=g.coreEnabled=g.bossRoomEntered=true;g.state='playing';boss.brain.hit(g.position.x,g.position.z,g.time);g.card.seen.add('POTION');g.card.seen.add('AMMO CELL');});
 for(const [phase,ratio]of [[0,1],[1,.5],[1,.2]]as const){await page.evaluate(async r=>{const {game:g}=await import(Array.from(document.scripts).find(s=>s.src.includes('/src/main.ts'))!.src);const b=g.enemies.find((e:any)=>e.kind==='KING PUNI');b.hp=b.maxHp*r;b.cooldown=0;b.telegraph=0;b.attackCycle=0;g.clearTransient();},ratio);
  await expect.poll(()=>run(page,g=>g.enemies.find((e:any)=>e.kind==='KING PUNI').group.userData.bossPhase)).toBe(phase);await page.waitForTimeout(1200);if(ratio===.5)await expect.poll(()=>run(page,g=>g.enemies.filter((e:any)=>e.alive&&e.kind!=='KING PUNI').length),{timeout:4000}).toBeGreaterThanOrEqual(1);await page.screenshot({path:`screenshots/nightmare-tactics/${name}-boss-phase-${phase}.png`});expect(await run(page,g=>g.hp)).toBeGreaterThan(0);
 }
 await page.waitForTimeout(400);const counts=await run(page,g=>({summons:g.enemies.filter((e:any)=>e.alive&&e.kind!=='KING PUNI').length,hp:g.enemies.find((e:any)=>e.kind==='KING PUNI').maxHp}));expect(counts.hp).toBe(8550);expect(counts.summons).toBeGreaterThanOrEqual(1);expect(counts.summons).toBeLessThanOrEqual(3);expect(errors).toEqual([]);await context.close();
});
test('intro composition and deterministic healing remain bounded',async({page})=>{
 await page.goto('/');await page.locator('#start').click();await page.locator('#card-close').click();const result=await run(page,async g=>{g.challenge=3;g.loadStage(0);await g.visuals.ready;g.state='review';const intro=g.enemies.filter((e:any)=>e.group.userData.nightmareIntro),before=g.world.items.filter((i:any)=>i.kind==='POTION').length;for(const e of g.enemies.filter((e:any)=>!['KING PUNI','SAMURAI'].includes(e.kind)).slice(0,9))g.damage(e,10000);return {count:intro.length,kinds:[...new Set(intro.map((e:any)=>e.kind))],nearest:Math.min(...intro.map((e:any)=>Math.hypot(e.home.x-10,e.home.z-42))),healing:g.world.items.filter((i:any)=>i.kind==='POTION').length-before};});expect(result.count).toBeLessThanOrEqual(16);expect(result.kinds.length).toBeGreaterThanOrEqual(2);expect(result.nearest).toBeGreaterThan(12);expect(result.healing).toBeGreaterThanOrEqual(1);
});
