import {test,expect,type Page} from '@playwright/test';
async function run<T>(page:Page,fn:(g:any)=>T|Promise<T>):Promise<T>{return page.evaluate(async source=>{const {game}=await import(Array.from(document.scripts).find(s=>s.src.includes('/src/main.ts'))!.src);return (0,eval)(`(${source})`)(game);},fn.toString());}
async function start(page:Page){await page.goto('/');await page.locator('#start').click();await page.locator('#card-close').click();await run(page,g=>{g.state='review';});}
for(const [name,width,height,touch]of [['PC',1280,720,false],['phone',844,390,true],['tablet',1024,768,true]]as const)test(`pickup selection and automatic equipment ${name}`,async({browser})=>{
 const context=await browser.newContext({viewport:{width,height},isMobile:touch,hasTouch:touch}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);
 expect(await run(page,g=>{const results=[];for(let selected=0;selected<4;selected++){g.selectedItem=selected;for(const kind of ['POTION','BIG POTION','ANTIDOTE','ELIXIR','PARUPUN','ARMOR CELL','AMMO CELL','CANDY','RAINBOW','LAVA CHARM']){g.takeSupply(kind);results.push(g.selectedItem===selected);}}return results.every(Boolean);})).toBe(true);
 await run(page,g=>{g.selectedItem=0;g.hp=40;g.supplies.potions=1;g.supplies.bigPotions=0;g.takeSupply('ANTIDOTE');g.takeSupply('PARUPUN');g.updateHud();});await page.locator('#item-use').click();await run(page,g=>g.useItems());expect(await run(page,g=>g.hp)).toBe(70);expect(await run(page,g=>g.selectedItem)).toBe(0);
 const acquisitions=await run(page,g=>{g.challenge=3;g.arsenal.reset();g.input.weapon=0;g.selectedItem=1;return ['BUBBLE MODULE','STAR MODULE','KATANA','MURASAME','ASSAULT RIFLE','CANNON','THUNDER PLUS'].map(kind=>{g.takeSupply(kind);return {weapon:g.input.weapon,item:g.selectedItem};});});expect(acquisitions.map(s=>s.weapon)).toEqual([5,6,3,3,4,5,6]);expect(acquisitions.every(s=>s.item===1)).toBe(true);
 await run(page,g=>{g.updateHud();});await expect(page.locator('#weaponname')).toHaveText('サンダーボルト かい');await page.locator('#weapon').click();expect(await run(page,g=>g.input.weapon)).toBe(3);
 await page.screenshot({path:`screenshots/nightmare-weapons/${name}-hud.png`});expect(errors).toEqual([]);await context.close();
});
test('nightmare substitutes original weapon sites and keeps chest rewards enclosed',async({page})=>{await start(page);const rows=await run(page,async g=>{const result=[];for(const mode of [0,1,2,3])for(const stage of [0,1,2]){g.challenge=mode;g.arsenal.reset();g.loadStage(stage);await g.visuals.ready;g.state='review';const weapons=g.world.items.filter((i:any)=>['CANNON','THUNDER PLUS','BUBBLE MODULE','STAR MODULE','BUBBLE UPGRADE','NOVA UPGRADE'].includes(i.kind));result.push({mode,stage,items:weapons.map((i:any)=>({kind:i.kind,x:i.x,z:i.z,chest:!!i.mesh.userData.inChest,visible:i.mesh.visible})),choices:g.arsenal.choices()});}return result;});for(const row of rows){if(row.mode===3){expect(row.choices.every((n:number)=>n>=4||n===3)).toBe(true);expect(row.items.every((i:any)=>['CANNON','THUNDER PLUS'].includes(i.kind))).toBe(true);for(const item of row.items)if(item.chest)expect(item.visible).toBe(false);}else expect(row.items.every((i:any)=>!['CANNON','THUNDER PLUS'].includes(i.kind))).toBe(true);}expect(rows.find(r=>r.mode===3&&r.stage===1)!.items.map(i=>[i.kind,i.x,i.z])).toEqual([['CANNON',30,42],['CANNON',86,54]]);expect(rows.find(r=>r.mode===3&&r.stage===2)!.items.map(i=>[i.kind,i.x,i.z])).toEqual([['THUNDER PLUS',26,58],['THUNDER PLUS',14,14]]);});
for(const touch of [false,true])test(`new weapons fire using actual ${touch?'touch':'mouse'} input`,async({browser})=>{
 const context=await browser.newContext({viewport:{width:touch?844:1280,height:touch?390:720},isMobile:touch,hasTouch:touch}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);
 await run(page,async g=>{g.challenge=3;g.loadStage(0);await g.visuals.ready;g.card.seen.add('POTION');g.card.seen.add('BIG POTION');g.card.seen.add('AMMO CELL');g.card.seen.add('PARUPUN');g.hp=1000;for(const item of g.world.items){item.taken=true;item.mesh.visible=false;}g.position.set(26,1.65,38);g.yaw=g.pitch=0;for(const e of g.enemies){e.alive=false;e.group.visible=false;}g.takeSupply('ASSAULT RIFLE');g.input.fire=false;g.state='playing';});
 const cdp=await context.newCDPSession(page);if(touch){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:7,x:180,y:250}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:7,x:210,y:230}]});}
 for(const [kind,index]of [['ASSAULT RIFLE',4],['CANNON',5],['THUNDER PLUS',6]]as const){await page.evaluate(async k=>{const {game:g}=await import(Array.from(document.scripts).find(s=>s.src.includes('/src/main.ts'))!.src);g.takeSupply(k);g.time+=1;g.shotTime=0;g.energy=100;g.clearTransient();g.testFired=0;g.testArcs=0;if(!g.shots.testOriginalPush){const original=g.shots.push.bind(g.shots);g.shots.push=(...shots:any[])=>{g.testFired+=shots.length;return original(...shots);};g.shots.testOriginalPush=true;}if(!g.lightning.testOriginalAdd){const original=g.lightning.add.bind(g.lightning);g.lightning.add=(...args:any[])=>{g.testArcs++;return original(...args);};g.lightning.testOriginalAdd=true;}},kind);
  if(touch){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:7,x:210,y:230},{id:8,x:565,y:180}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[{id:8,x:565,y:180}]});expect(await run(page,g=>g.input.mx)).toBeGreaterThan(0);}else{await page.mouse.move(860,350);await page.mouse.down();}
  await expect.poll(()=>run(page,g=>g.shotTime-g.time),{timeout:2000}).toBeGreaterThan(0);if(!touch){await page.waitForTimeout(index===4?250:30);await page.mouse.up();}
  if(index<6)expect(await run(page,g=>g.testFired>0)).toBe(true);else expect(await run(page,g=>g.testArcs)).toBeGreaterThanOrEqual(3);
  await page.screenshot({path:`screenshots/nightmare-weapons/${touch?'phone':'PC'}-${index}-fire.png`});
 }
 if(touch)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});expect(errors).toEqual([]);await context.close();
});
test('nightmare palettes differ across all stages and restore normal colors without changing enemy health',async({page})=>{
 await start(page);for(const stage of [0,1,2]){
  const normal=await page.evaluate(async stage=>{const {game:g}=await import('/src/main.ts');g.challenge=0;g.loadStage(stage);await g.visuals.ready;g.state='review';g.atmosphere.update(stage,75);return {wall:g.world.wallMaterial.color.getHex(),sky:g.atmosphere.sky.material.uniforms.top.value.getHex()};},stage);
  const alternate=await page.evaluate(async stage=>{const {game:g}=await import('/src/main.ts');g.challenge=3;g.loadStage(stage);await g.visuals.ready;g.state='review';g.atmosphere.update(stage,75,true);g.position.set(stage===2?90:26,stage===2?16:1.65,stage===0?38:stage===1?54:32);g.camera.position.copy(g.position);g.camera.lookAt(stage===2?90:30,stage===2?17:2,stage===0?26:stage===1?38:18);g.takeSupply(['ASSAULT RIFLE','CANNON','THUNDER PLUS'][stage]);g.updateHud();return {wall:g.world.wallMaterial.color.getHex(),sky:g.atmosphere.sky.material.uniforms.top.value.getHex(),health:g.enemies.filter((e:any)=>!['KING PUNI','SAMURAI'].includes(e.kind)).every((e:any)=>e.maxHp===570)};},stage);
  expect(alternate.wall).not.toBe(normal.wall);expect(alternate.sky).not.toBe(normal.sky);expect(alternate.health).toBe(true);await page.screenshot({path:`screenshots/nightmare-weapons/parallel-${stage+1}.png`});
  const restored=await page.evaluate(async stage=>{const {game:g}=await import('/src/main.ts');g.challenge=0;g.loadStage(stage);await g.visuals.ready;g.state='review';return g.world.wallMaterial.color.getHex();},stage);expect(restored).toBe(normal.wall);
 }
});
test('mobile new-weapon effects remain responsive during live nightmare combat',async({browser})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);
 await run(page,async g=>{g.challenge=3;g.loadStage(2);await g.visuals.ready;for(const i of g.world.items){i.taken=true;i.mesh.visible=false;}g.position.set(26,1.65,58);g.yaw=g.pitch=0;g.hp=2000;g.takeSupply('THUNDER PLUS');g.state='playing';for(const e of g.enemies)if(e.group.position.distanceTo(g.position)<25)e.brain.hit(g.position.x,g.position.z,g.time);const surface=document.getElementById('look')!;let n=300;(window as any).newWeaponTaps=setInterval(()=>{const pointerId=n++;for(const type of ['pointerdown','pointerup'])surface.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId,pointerType:'touch',clientX:550,clientY:190}));},180);});
 const result=await page.evaluate(async()=>{const begin=performance.now(),gaps:number[]=[];let last=begin;return new Promise<{fps:number;p95:number;max:number}>(resolve=>{const sample=(now:number)=>{gaps.push(now-last);last=now;if(now-begin<8000)requestAnimationFrame(sample);else{gaps.sort((a,b)=>a-b);resolve({fps:gaps.length*1000/(now-begin),p95:gaps[Math.floor(gaps.length*.95)],max:gaps.at(-1)!});}};requestAnimationFrame(sample);});});await page.evaluate(()=>clearInterval((window as any).newWeaponTaps));console.log('new nightmare weapon mobile',result);expect(result.fps).toBeGreaterThanOrEqual(30);expect(result.max).toBeLessThan(500);expect(errors).toEqual([]);expect(await run(page,g=>g.state)).toBe('playing');await page.screenshot({path:'screenshots/nightmare-weapons/phone-combat-performance.png'});await context.close();
});
test('boss still attacks while the new rifle is continuously fired',async({page})=>{
 await start(page);await run(page,async g=>{g.challenge=3;g.loadStage(0);await g.visuals.ready;for(const item of g.world.items){item.taken=true;item.mesh.visible=false;}for(const e of g.enemies){e.alive=e.kind==='KING PUNI';e.group.visible=e.alive;}const boss=g.enemies.find((e:any)=>e.kind==='KING PUNI');boss.hp=boss.maxHp=100000;g.position.set(62,1.65,28);g.camera.position.copy(g.position);g.camera.rotation.order='YXZ';g.camera.lookAt(boss.group.position.x,boss.floorY+boss.baseScale*2.2,boss.group.position.z);g.yaw=g.camera.rotation.y;g.pitch=g.camera.rotation.x;g.hp=500;g.takeSupply('ASSAULT RIFLE');g.state='playing';g.startBoss();});await page.mouse.move(640,360);await page.mouse.down();await expect.poll(()=>run(page,g=>g.enemies.find((e:any)=>e.kind==='KING PUNI').attackCycle),{timeout:5000}).toBeGreaterThan(0);expect(await run(page,g=>g.enemies.find((e:any)=>e.kind==='KING PUNI').hp)).toBeLessThan(100000);await page.mouse.up();
});
