import {it,expect,vi}from 'vitest';import * as T from 'three';import {Brain}from '../src/ai/Brain';import type {Game}from '../src/game/Game';import type {Enemy}from '../src/game/Enemy';import {updateBoss,cancelBossCombat,destroyIllusion}from '../src/game/boss/BossCombat';import {bossState}from '../src/game/boss/BossState';import {createIllusions,tickIllusions}from '../src/game/boss/BossIllusions';import {bossVolley}from '../src/game/boss/BossProjectiles';import {bossHealth,rulerAttack}from '../src/game/boss/BossSettings';import {configureStage,canMoveAt}from '../src/world/layout';import {nightmareHealth}from '../src/game/PowerEffects';import {challengeItems,enemySupplyDrops}from '../src/game/Challenge';import {Arsenal}from '../src/game/Progression';import {stages}from '../src/stages/Stages';
vi.mock('../src/game/Enemy',async()=>{const t=await import('three'),{Brain}=await import('../src/ai/Brain');return {Enemy:class{kind='KING PUNI';group=new t.Group();body=new t.Group();brain=new Brain();alive=true;hp=1;maxHp=1;floorY=0;baseScale=1;radius=2.3;alert=true;cooldown=0;telegraph=0;stunned=0;home:any;arms=[];constructor(_kind:string,x:number,z:number){this.home={x,z};this.group.add(this.body,new t.Group());this.group.position.set(x,0,z);}animate(){}}};});
function fixture(stage=0,mode=3){configureStage(stage);const p=stage===0?[26,22]:stage===1?[82,22]:[90,18];const e={kind:'KING PUNI',group:new T.Group(),body:new T.Group(),arms:[],brain:new Brain(),home:{x:p[0],z:p[1]},floorY:stage===2?12:0,baseScale:1,radius:2.3,hp:1000,maxHp:1000,alive:true,alert:true,cooldown:0,attackCycle:0,telegraph:0,stunned:0,dashUntil:0,dashX:0,dashZ:0}as unknown as Enemy;e.group.position.set(p[0],e.floorY,p[1]);e.group.add(e.body);const g={stageIndex:stage,challenge:mode,time:10,position:new T.Vector3(p[0],e.floorY+1.65,p[1]+4),gate:true,enemies:[e],scene:new T.Scene(),shots:[],sound:{effect:vi.fn(),impact:vi.fn()},burst:vi.fn(),hurt:vi.fn(),disposeGroup:(o:T.Object3D)=>o.removeFromParent(),input:{touch:true}}as unknown as Game;return {g,e,s:bossState(e)};}
it('increases only hard/nightmare boss health, never ordinary or samurai health',()=>{expect([0,1,2,3].map(n=>bossHealth(n,100))).toEqual([100,100,150,150]);expect(nightmareHealth('PUNI',3,100)).toBe(570);expect(nightmareHealth('SAMURAI',3,100)).toBe(5700);expect(nightmareHealth('KING PUNI',3,100,2)).toBe(8550);});
it('first boss charge has a locked direction, collides with a wall and gives a real stun opening',()=>{const {g,e,s}=fixture();g.position.set(26,1.65,18);updateBoss(g,e,.016,true);const tell=e.telegraph;g.position.x=32;g.time=tell+.01;updateBoss(g,e,.016,true);expect(e.dashX).toBe(0);for(let n=0;n<60&&s.mode==='Attack';n++){g.time+=.02;updateBoss(g,e,.02,true);}expect(s.mode).toBe('Stunned');expect(canMoveAt(e.group.position.x,e.group.position.z,1.65,true)).toBe(true);expect(s.stars).toBeDefined();expect(g.hurt).not.toHaveBeenCalled();const until=s.until;e.hp=490;updateBoss(g,e,.01,true);expect(s.second).toBe(true);expect(s.mode).toBe('Stunned');expect(s.until).toBe(until);expect(e.hp).toBe(490);});
it('a warned slam misses a player who leaves the circle and has recovery',()=>{const {g,e,s}=fixture();e.group.userData.chargerDecision=1;updateBoss(g,e,.016,true);expect(s.action).toBe('slam');g.position.x=35;g.time=s.until+.01;updateBoss(g,e,.016,true);expect(g.hurt).not.toHaveBeenCalled();expect(s.mode).toBe('Recovery');expect(s.until).toBeGreaterThan(g.time);});
it('nightmare second form has at most two committed charges, each with a fresh tell',()=>{const {g,e,s}=fixture();s.second=true;e.hp=490;g.position.set(26,1.65,30);updateBoss(g,e,.016,true);g.time=s.until+.01;updateBoss(g,e,.01,true);g.position.x=32;g.time=s.until+.01;updateBoss(g,e,0,true);expect(s.mode).toBe('Recovery');g.time=s.until+.01;updateBoss(g,e,0,true);expect(s.mode).toBe('Windup');expect(e.telegraph).toBeGreaterThan(g.time);g.time=s.until+.01;updateBoss(g,e,0,true);g.time=s.until+.01;updateBoss(g,e,0,true);expect(s.chain).toBe(0);});
it('magician illusions have no shadow, bounded lifetime and collapse to one hit without loot',()=>{const {g,e,s}=fixture(1);s.nightmare=s.second=true;createIllusions(g,e,s);expect(s.clones.length).toBeGreaterThanOrEqual(2);expect(s.clones.length).toBeLessThanOrEqual(4);for(const a of s.clones){expect(a.group.children[1].visible).toBe(false);expect(a.group.userData.bossClone).toBe(true);destroyIllusion(g,a);expect(a.hp).toBe(0);}expect(tickIllusions(g,e,s,.016)).toBe(true);});
it('illusion timeout does not grant the full player-earned vulnerability reward',()=>{const {g,e,s}=fixture(1);createIllusions(g,e,s);g.time=s.cloneExpires+.01;expect(tickIllusions(g,e,s,.016)).toBe(false);expect(s.cloneActive).toBe(false);});
it('warp checks the destination again if the player has moved into its warning',()=>{const {g,e,s}=fixture(1);e.attackCycle=2;s.nextIllusion=100;updateBoss(g,e,.016,true);expect(s.action).toBe('warp');if(s.warp)g.position.set(s.warp.x,1.65,s.warp.z);g.time=s.until+.01;updateBoss(g,e,.016,true);expect(Math.hypot(e.group.position.x-g.position.x,e.group.position.z-g.position.z)).toBeGreaterThanOrEqual(5);expect(canMoveAt(e.group.position.x,e.group.position.z,1.65,true)).toBe(true);expect(s.mode).toBe('Recovery');expect(e.group.userData.bossHidden).toBe(false);});
it('final boss commits distance-based fan, aim and blade choices and keeps a gap between shots',()=>{expect([20,12,4].map(d=>rulerAttack(d,false,false,0))).toEqual(['fan','aim','slash']);const {g,e,s}=fixture(2);g.position.z=40;updateBoss(g,e,.016,true);expect(s.action).toBe('fan');g.position.x=94;g.time=s.until+.01;updateBoss(g,e,.016,true);expect(g.shots).toHaveLength(5);expect(Math.abs(g.shots[1].v.x-g.shots[2].v.x)).toBeGreaterThan(2);expect(s.mode).toBe('Recovery');});
it('boss projectiles and clones share a fixed budget and are neutralized on death',()=>{const {g,e,s}=fixture(1);for(let n=0;n<50;n++)bossVolley(g,e,[0],{x:82,y:1.65,z:30},24);expect(g.shots).toHaveLength(24);cancelBossCombat(g,e);expect(s.mode).toBe('Dead');expect(g.shots.every(a=>a.damage===0&&a.life===0)).toBe(true);});
it('nightmare weapon sites and carried equipment never expose obsolete weapons',()=>{const a=new Arsenal();a.unlock(1);a.unlock(2);a.unlock(3);a.activateNightmare();expect(a.choices()).toEqual([4,5,6,3]);expect(a.murasame).toBe(true);expect(a.resolve(2)).toBe(6);for(const stage of stages){const items=challengeItems(stage,3);expect(items.some(([k])=>k.includes('MODULE')||k.includes('UPGRADE')||k==='KATANA')).toBe(false);expect(items.map(([,x,z])=>[x,z])).toEqual(challengeItems(stage,2).map(([,x,z])=>[x,z]));}});
it('nightmare loot budget is two thirds with a larger antidote share',()=>{for(const stage of stages){const all=(level:number)=>Array.from({length:100},(_,n)=>enemySupplyDrops(stage,level,n+1,100)).flat();const hard=all(2),night=all(3);expect(night.length).toBe(Math.round(hard.length*2/3));expect(night.filter(([k])=>k==='ANTIDOTE').length/night.length).toBeGreaterThan(hard.filter(([k])=>k==='ANTIDOTE').length/hard.length);expect(night.filter(([k])=>k==='ANTIDOTE').length).toBeGreaterThan(hard.filter(([k])=>k==='ANTIDOTE').length);}});
it('final boss retains paralysis but leaves enough recovery to prevent an unavoidable immediate follow-up',()=>{const {g,e,s}=fixture(2,0);s.second=true;s.mode='Windup';s.action='aim';s.aim={x:g.position.x,y:g.position.y,z:g.position.z};s.until=g.time-.01;e.attackCycle=3;updateBoss(g,e,.016,true);expect(g.shots[0].kind).toBe(4);expect(s.until-g.time).toBeGreaterThanOrEqual(3.4);});
it('preserves desktop 1/2/3/4 weapon roles with the nightmare replacements',()=>{const a=new Arsenal();a.unlock(1);a.unlock(2);a.unlock(3);a.activateNightmare();expect([0,1,2,3].map(n=>a.resolve(n))).toEqual([4,5,6,3]);expect(a.select(0,6)).toBe(4);a.nightmareOnly=false;a.nightmareWeapons.clear();expect(a.choices()).toEqual([2,3]);});
