import {enemySizeMultiplier,railEnemyScale} from '../src/game/EnemyScale';
import {challenges,unlockKey} from '../src/game/Challenge';
import * as T from 'three';
import {RailRide} from '../src/rail/RailRide';
import {rideDurations} from '../src/rail/RailCourse';
import {showPreview} from '../src/ui/Preview';
import {installCampaignBot} from './campaign-bot';
import {game as g} from '../src/main';
import {doors,switches} from '../src/world/Threats';
import {stages} from '../src/stages/Stages';
import {wall} from '../src/world/layout';
import {visibleTextValid} from '../src/ui/Text';
const results=document.getElementById('testresults')!;const checks:string[]=[];
function assert(name:string,b:boolean){checks.push(`${b?'PASS':'FAIL'} ${name}`);results.textContent=checks.join('\n');if(!b)throw Error(name);}
function dismiss(){if(g.card.open)g.card.close();}
function step(n=1){for(let i=0;i<n;i++)g.update(.016);}
function at(x:number,z:number){dismiss();g.state='playing';g.orientationBlocked=false;g.mapOpen=false;g.position.set(x,1.65,z);g.velocity.set(0,0,0);g.vy=0;g.hurtTime=0;step();}
function switchUse(kind:typeof switches[number]['kind']){const sw=switches.find(s=>s.kind===kind)!;at(sw.x,sw.z);g.input.interact=true;step();}
function load(n:number){dismiss();g.loadStage(n);g.keyCount=n;g.state='playing';g.orientationBlocked=false;g.hp=100;}
function trainTransfer(){const boss=g.enemies.find(e=>e.kind==='KING PUNI')!;at(boss.group.position.x,boss.group.position.z);dismiss();assert('boss battery collected',g.battery);at(...stages[g.stageIndex].exit);assert('train waits for battery interaction',!g.ride);g.input.interact=true;step();assert('battery insertion explains rail shooting',g.card.open);dismiss();assert('rail ride starts without stage warp',!!g.ride&&g.ride.targets.length>0);assert('battery is installed instead of reusable',!g.battery);const old=g.stageIndex;g.ride!.progress.elapsed=rideDurations[old]-.01;step();assert('arrival card before next stage',g.card.open&&g.stageIndex===old);dismiss();}
function down(id:string,pointerId:number,x:number,y:number){document.getElementById(id)!.dispatchEvent(new PointerEvent('pointerdown',{pointerId,clientX:x,clientY:y}));}
function up(id:string,pointerId:number){document.getElementById(id)!.dispatchEvent(new PointerEvent('pointerup',{pointerId}));}
const visibleText=()=>Array.from(document.querySelectorAll('#app *')).filter(e=>e.children.length===0&&getComputedStyle(e).display!=='none'&&e.getBoundingClientRect().width>0).map(e=>e.textContent??'').join(' ');
const qs=new URLSearchParams(location.search);
g.input.touch=!qs.has('desktop');document.body.classList.toggle('touch',g.input.touch);
setTimeout(async()=>{if(qs.has('nopointerlock'))Object.defineProperty(document,'exitPointerLock',{value:undefined,configurable:true});try{
 g.input.touch=true;document.body.classList.add('touch');g.reset();g.orientationBlocked=false;g.state='playing';document.getElementById('overlay')!.style.display='none';document.getElementById('hud')!.style.display='block';assert('three separate stages',stages.length===3);assert('fresh fog',g.fog.visited.size===0);step();
 const drag=(id:number,x:number,y:number)=>document.getElementById('look')!.dispatchEvent(new PointerEvent('pointermove',{pointerId:id,clientX:x,clientY:y}));
 down('look',1,480,200);drag(1,490,155);assert('swipe forward proportional speed',g.input.my===.5);drag(1,510,110);assert('swipe full speed and responsive turn',g.input.my===1&&g.input.lookX>.2);down('look',2,650,150);up('look',2);assert('second finger tap fires while moving',g.input.fire&&g.input.my===1&&g.input.tapAim!==null);step();assert('off center tap projectile',g.shots.length>0);up('look',1);g.input.reset();
 down('look',1,480,200);drag(1,480,245);assert('swipe backward proportional speed',g.input.my===-.5);up('look',1);g.input.reset();
 down('look',1,300,200);down('look',2,500,200);drag(1,330,200);drag(2,470,200);assert('pinch in moves forward',g.input.my>0);drag(1,270,200);drag(2,530,200);assert('pinch out moves backward',g.input.my<0);up('look',1);up('look',2);g.input.reset();
 down('look',1,300,200);down('look',2,500,200);drag(1,340,200);drag(2,540,200);assert('parallel two finger swipe strafes',g.input.mx>0&&g.input.my===0);up('look',1);up('look',2);g.input.reset();assert('all pointers release',g.input.my===0&&!g.input.fire);

 at(18,42);assert('first item freezes gameplay',g.state==='card'&&g.card.open);assert('large item explanation',document.getElementById('card-title')!.textContent!.includes('ポーション'));assert('kana item explanation',visibleTextValid(document.getElementById('card-description')!.textContent!));dismiss();g.hp=50;document.getElementById('item-select')!.click();document.getElementById('pick-potion')!.click();document.getElementById('item-use')!.click();step();assert('potion manual recovery',g.hp>50);at(34,42);g.input.interact=true;step();assert('switch opens collision gate',doors[0].open&&!wall(38,38));g.input.interact=true;step();assert('switch closes gate',!doors[0].open&&wall(38,38));
 const enemy=g.enemies[0];enemy.group.position.set(26,0,30);enemy.group.rotation.y=0;enemy.brain.reset();at(26,42);step(60);assert('back-facing idle enemy ignores room entry',enemy.brain.state==='Idle');enemy.group.position.set(26,0,30);enemy.group.rotation.y=Math.PI;step(60);assert('front-facing room enemy approaches beyond short range',enemy.brain.state!=='Idle'&&enemy.group.position.z>30);enemy.group.position.set(26,0,30);enemy.brain.reset();at(10,30);g.damage(enemy,1);assert('remote hit wakes enemy immediately',enemy.brain.state==='Alert');g.time+=.3;step();assert('remote hit searches attacker',enemy.brain.state==='Search'||enemy.brain.state==='Chase'||enemy.brain.state==='Cooldown');const ex=enemy.group.position.x;step(90);assert('wounded enemy approaches instead of standing',enemy.group.position.x!==ex);assert('memory persists without vision',enemy.brain.until>g.time);
 assert('first reward door is boss locked',!doors[stages[0].boss.exitDoor].open);at(...stages[0].key);dismiss();assert('fragment alone cannot advance stage',!g.world.portal.visible);g.damage(g.enemies.find(e=>e.kind==='KING PUNI')!,10000);assert('defeat has animated body and rings',g.defeat.entries.length>0&&g.defeat.entries[0].rings.length===2);assert('first boss opens reward room',doors[stages[0].boss.exitDoor].open);at(...stages[0].key);assert('first fragment',g.keyCount===1&&g.stageFragment);dismiss();trainTransfer();assert('transition loads stage two',g.stageIndex===1);assert('stage fog reset',g.fog.visited.size===0);assert('larger second-stage enemies',g.enemies[0].baseScale>enemy.baseScale);
 at(30,42);assert('second weapon acquired',g.arsenal.unlocked[1]);dismiss();document.getElementById('weapon')!.click();assert('weapon icon cycles owned weapons',g.input.weapon===0);at(26,58);assert('antidote explanation',g.card.open&&document.getElementById('card-title')!.textContent!.includes('どくけし'));dismiss();at(54,42);assert('toxic lingering state',g.poisonUntil>g.time);assert('poison edge effect',document.getElementById('danger')!.classList.contains('poison'));document.getElementById('item-select')!.click();document.getElementById('pick-antidote')!.click();document.getElementById('item-use')!.click();step();assert('antidote clears poison',g.poisonUntil===0);at(46,54);dismiss();const hp=g.hp;g.hurtTime=0;g.hurt(10);assert('finite armor absorbs hit',g.hp>=hp-4);switchUse('purge');assert('purge switch stops toxic flow',g.purgeUntil>g.time);switchUse('secret');assert('shortcut opens',doors[3].open);at(86,54);dismiss();assert('weapon upgrade',g.arsenal.levels[1]===1);
 assert('second reward door is boss locked',!doors[stages[1].boss.exitDoor].open);g.damage(g.enemies.find(e=>e.kind==='KING PUNI')!,10000);assert('second boss reveals fixed train but boarding waits for fragment',doors[stages[1].boss.exitDoor].open&&g.world.portal.visible&&!g.stageFragment);at(...stages[1].key);dismiss();trainTransfer();assert('transition loads stage three',g.stageIndex===2);assert('third-stage enemies visibly grow',g.enemies[0].baseScale>1.05);at(26,58);assert('final weapon acquisition',g.arsenal.unlocked[2]);dismiss();at(30,22);assert('fire protection collected',g.buffs.has('LAVA CHARM'));dismiss();g.buffs.delete('LAVA CHARM');at(46,22);assert('lava hurts without instant death',g.hp<100&&g.hp>0);assert('lava edge effect',document.getElementById('danger')!.classList.contains('lava'));switchUse('bridge');assert('bridge visible',g.world.bridges.every(b=>b.visible));g.time=g.bridgeUntil+1;step();assert('bridge timeout',g.world.bridges.every(b=>!b.visible));g.atmosphere.update(2,0);assert('sunset begins',g.atmosphere.phase===0);g.atmosphere.update(2,150);assert('night arrives',g.atmosphere.phase===1);assert('moon and stars',g.atmosphere.moon.visible&&(g.atmosphere.stars.material as any).opacity===1&&Array.from(g.atmosphere.stars.geometry.attributes.position.array).every(Number.isFinite));
 load(2);at(86,22);g.gate=true;const testBoss=g.enemies.find(e=>e.kind==='KING PUNI')!;testBoss.group.position.set(90,0,18);testBoss.brain.hit(86,22,g.time);g.time+=1;testBoss.attackCycle=1;testBoss.cooldown=0;testBoss.telegraph=g.time-.1;step();assert('boss toxic volley',g.shots.some(s=>s.enemy&&s.kind===3));g.clearTransient();testBoss.attackCycle=2;testBoss.cooldown=0;testBoss.telegraph=g.time-.1;step();assert('boss paralysis volley',g.shots.some(s=>s.enemy&&s.kind===4));const stun=g.shots.find(s=>s.enemy&&s.kind===4)!;stun.m.position.copy(g.position);stun.v.set(0,0,0);g.hurtTime=0;step();assert('paralysis lasts three seconds',Math.abs(g.paralyzedUntil-g.time-3)<.001);assert('damage triggers brief shake',g.shakeUntil>g.time);const held=g.position.clone();g.input.my=1;step(60);assert('paralysis blocks movement',held.distanceTo(g.position)<.001);step(140);assert('paralysis naturally expires',g.time>g.paralyzedUntil);g.input.reset();load(2);
 assert('final reward door is boss locked',!doors[stages[2].boss.exitDoor].open);switchUse('core');assert('boss gate unlocks',g.gate&&!g.world.gate.visible);const boss=g.enemies.find(e=>e.kind==='KING PUNI')!;assert('giant boss same species',boss.baseScale>enemy.baseScale);at(86,22);step(65);boss.cooldown=0;boss.telegraph=g.time-.1;step();assert('boss ranged and shockwave attacks',g.shots.some(s=>s.enemy)&&g.shockwaves.length>0);g.damage(boss,10000);assert('final boss reveals fixed train but boarding waits for fragment',doors[stages[2].boss.exitDoor].open&&g.world.portal.visible&&!g.stageFragment);at(...stages[2].key);dismiss();assert('all three fragments',g.keyCount===3);assert('boss defeat opens exit',g.bossClear&&g.world.portal.visible);trainTransfer();assert('ending starts',g.state==='ending');g.updateEnding(7);assert('three fragments unite',g.ending!.rainbow.visible);g.updateEnding(10);g.updateEnding(.016);assert('returns to room and clear',g.state==='clear'&&g.ending!.room.visible);assert('kana ending',visibleTextValid(document.getElementById('description')!.textContent!));
 g.reset();g.orientationBlocked=false;g.state='playing';g.hp=1;g.hurtTime=0;g.hurt(10);assert('game over',g.state==='over');g.start();assert('death cannot restart from held input',g.state==='over');assert('death offers retry or quit',!document.getElementById('quit')!.hidden&&document.getElementById('description')!.textContent==='ざんねん！もういっかい！');await new Promise(r=>setTimeout(r,750));g.start();assert('retry same stage',g.stageIndex===0&&g.hp>=80);g.hp=1;g.hurtTime=0;g.hurt(999);await new Promise(r=>setTimeout(r,750));document.getElementById('quit')!.click();assert('quit returns to stopped title',g.state==='title');g.reset();assert('restart resets fragments weapons fog',g.keyCount===0&&!g.arsenal.unlocked[1]&&g.fog.visited.size===0);g.state='playing';g.pause();assert('pause',g.state==='paused');assert('no forbidden player text',visibleTextValid(visibleText()));
 load(0);g.activateSwitch(switches.find(s=>s.door===3)!);assert('first boss wakes when entrance opens',g.gate&&g.enemies.find(e=>e.kind==='KING PUNI')!.alert);load(1);g.activateSwitch(switches.find(s=>s.door===2)!);assert('second boss wakes when entrance opens',g.gate&&g.enemies.find(e=>e.kind==='KING PUNI')!.alert);load(2);g.activateSwitch(switches.find(s=>s.kind==='core')!);assert('final boss wakes at gate opening',g.gate&&g.enemies.find(e=>e.kind==='KING PUNI')!.alert);
 load(1);const samurai=g.enemies.find(e=>e.kind==='SAMURAI')!;assert('samurai high durability and sealed room',samurai.hp===1800&&!doors[5].open);g.activateSwitch(switches.find(s=>s.kind==='samurai')!);assert('samurai warning pauses and offers cancel',g.state==='card'&&!!document.getElementById('samurai-cancel'));document.getElementById('samurai-cancel')!.click();assert('cancel leaves door sealed and katana locked',!doors[5].open&&!g.arsenal.unlocked[3]);g.activateSwitch(switches.find(s=>s.kind==='samurai')!);dismiss();assert('confirm wakes samurai and opens door',doors[5].open&&samurai.brain.state==='Alert');g.damage(samurai,2000);assert('samurai defeat drops katana without opening stage reward',g.world.items.some(i=>i.kind==='KATANA')&&!g.bossClear);at(samurai.group.position.x,samurai.group.position.z);assert('katana pickup unlocks with explanation',g.arsenal.unlocked[3]&&g.card.open);dismiss();const victim=g.enemies.find(e=>e.kind==='PUNI')!;victim.group.position.set(g.position.x+2,0,g.position.z);g.input.weapon=3;g.input.fire=true;g.shotTime=0;step();g.input.fire=false;assert('katana kills nearby normal enemy in one slash',!victim.alive);assert('katana produces slash ring',g.shockwaves.some(w=>w.hit));g.updateHud();assert('katana name is kana',document.getElementById('weaponname')!.textContent==='カタナ');
 load(0);g.bossClear=g.stageFragment=g.battery=true;g.ride=new RailRide(g);g.state='playing';g.ride.progress.elapsed=2.1;step();const railTarget=g.ride.targets[0];const aim=railTarget.enemy.group.position.clone().add(new T.Vector3(0,1.6*railEnemyScale/1.3,0)).project(g.camera);g.input.tapAim={x:aim.x,y:aim.y};g.input.fire=true;step();g.input.fire=false;assert('rail tap hits target while train moves',railTarget.hp===0&&g.ride.kills===1);assert('rail uses its own collision space',g.ride.traces.length>0);const rideCheckpoint=g.ride;g.hp=1;g.hurtTime=0;g.hurt(999);assert('rail death stops on choice screen',g.state==='over');await new Promise(r=>setTimeout(r,750));g.start();assert('rail retry preserves stage and restarts ride',g.ride===rideCheckpoint&&g.ride.progress.fraction===0&&g.hp===100);assert('rail retry restores targets',g.ride.targets.every(t=>t.hp>0&&t.enemy.group.visible));g.ride.progress.elapsed=rideDurations[0]-.01;step();assert('rail cannot advance before accepting arrival',g.stageIndex===0&&g.card.open);dismiss();assert('rail restores normal HUD after arrival',g.stageIndex===1&&!g.ride&&!((document.getElementById('weapon') as HTMLButtonElement).disabled));
 load(0);assert('normal enemies are twenty five percent larger',g.enemies.find(e=>e.kind==='PUNI')!.baseScale===.84*enemySizeMultiplier);assert('boss grows with same multiplier',g.enemies.find(e=>e.kind==='KING PUNI')!.baseScale===stages[0].boss.scale*enemySizeMultiplier);load(1);assert('samurai is larger',g.enemies.find(e=>e.kind==='SAMURAI')!.baseScale===1.5*enemySizeMultiplier);
 load(0);const stationPosition=g.world.portal.position.clone(),stationRotation=g.world.portal.rotation.clone();for(const time of [0,3,19,90])g.world.update(time);assert('station train remains fixed and upright',g.world.portal.position.equals(stationPosition)&&g.world.portal.rotation.equals(stationRotation));assert('train uses dedicated painted material sheets',g.world.portal.children[0].children.some(o=>o instanceof T.Mesh&&!!(o.material as T.MeshStandardMaterial).map));
 const unlockBefore=localStorage.getItem(unlockKey);g.challenge=0;g.loadStage(0);const baselineHp=g.enemies.find(e=>e.kind==='PUNI')!.hp;
 for(let level=0;level<4;level++){g.challenge=level;g.loadStage(0);assert(`difficulty ${level} count`,g.enemies.filter(e=>e.kind!=='KING PUNI').length===Math.ceil(27*challenges[level].count));assert(`difficulty ${level} HP`,Math.abs(g.enemies.find(e=>e.kind==='PUNI')!.hp-baselineHp*challenges[level].hp)<.001);assert(`difficulty ${level} boss HP`,g.enemies.find(e=>e.kind==='KING PUNI')!.hp===420*challenges[level].hp);}
 localStorage.removeItem(unlockKey);g.nightmare=false;g.challenge=1;g.beginEnding();assert('normal clear does not unlock nightmare',localStorage.getItem(unlockKey)===null);g.ending?.dispose();g.ending=undefined;g.challenge=2;g.beginEnding();assert('hard clear persists nightmare unlock',localStorage.getItem(unlockKey)==='1'&&g.nightmare);g.updateEnding(17);assert('nightmare option appears after hard clear',document.getElementById('challenge-options')!.textContent!.includes('あくむ'));g.ending?.dispose();g.ending=undefined;if(unlockBefore===null)localStorage.removeItem(unlockKey);else localStorage.setItem(unlockKey,unlockBefore);g.challenge=0;g.nightmare=unlockBefore==='1';g.reset();
 results.textContent=checks.join('\n')+`\n${checks.length} CHECKS COMPLETE`;
}catch(e){results.textContent+='\n'+String(e);}
 g.sound.bgm=false;g.state='review';g.input.touch=!qs.has('desktop');document.body.classList.toggle('touch',g.input.touch);g.resize();
 const scenes=['samurai','katana','title','stage1','combat1','item','switch','stage2','poison','stage3','sunset','lava','giant','boss1','boss2','boss','ending','map','infantry','train','rail','space','rail-play','space-play'];const bar=document.createElement('div');bar.id='review-scenes';bar.style.cssText='position:fixed;bottom:0;right:0;z-index:100;background:#2348;padding:5px;';
 function show(scene:string){results.style.display='none';document.getElementById('overlay')!.style.display='none';document.getElementById('card')!.hidden=true;document.getElementById('hud')!.style.display='block';g.card.open=false;g.ending?.dispose();g.ending=undefined;const stage=['samurai','katana','stage2','poison','item','boss2','space','space-play'].includes(scene)?1:['stage3','sunset','lava','giant','boss','ending'].includes(scene)?2:0;g.loadStage(stage);g.state='review';g.gate=scene.startsWith('boss')||scene==='ending';g.world.gate.visible=stage===2&&!g.gate;g.stageTime=scene==='sunset'?35:stage===2?150:0;g.atmosphere.update(stage,g.stageTime);
 const pos=scene==='poison'?[54,50]:scene==='lava'?[42,30]:scene.startsWith('boss')?[stages[stage].boss.x-8,stages[stage].boss.z+8]:scene==='giant'?[22,46]:stage===1?[54,60]:stage===2?[42,58]:[26,38];g.position.set(pos[0],1.65,pos[1]);g.camera.position.copy(g.position);const target=scene==='poison'?[54,42]:scene==='lava'?[46,22]:scene.startsWith('boss')?[stages[stage].boss.x,stages[stage].boss.z]:scene==='giant'?[26,42]:stage===1?[54,54]:stage===2?[50,58]:[26,30];g.camera.lookAt(target[0],scene.startsWith('boss')?2.2*stages[stage].boss.scale:1.2,target[1]);for(const e of g.enemies)e.group.rotation.y=Math.atan2(e.group.position.x-g.position.x,e.group.position.z-g.position.z);g.gun.position.set(0,-.18,-.6);g.input.weapon=stage;if(stage>0)g.arsenal.unlock(stage);g.updateHud();g.fog.reveal(...pos as [number,number],g.gate);g.drawMap();
 if(scene==='samurai'||scene==='katana'){g.position.set(22,1.65,22);g.camera.position.copy(g.position);g.camera.lookAt(22,2.5,14);const e=g.enemies.find(e=>e.kind==='SAMURAI')!;e.group.rotation.y=Math.PI;doors[5].open=true;g.world.doorMeshes[5].position.y=4.9;if(scene==='katana'){g.arsenal.unlock(3);g.input.weapon=3;g.gunStamp='';g.updateHud();}}
 if(scene==='title'){g.state='title';document.getElementById('overlay')!.style.display='flex';document.getElementById('hud')!.style.display='none';document.getElementById('start')!.textContent='はじめる ↗';document.getElementById('description')!.textContent='みっつの ほしを みつけて\nおもちゃのせかいを たすけよう！';document.getElementById('restart')!.hidden=true;}
 if(scene==='item'){g.card.show('どくけしを みつけた！','どくを なおせるよ\nどくになったら つかってみよう\nえを おして「つかう」を おそう','🌿');const item=g.world.items.find(i=>i.kind==='ANTIDOTE')!;showPreview(g.renderer,item.mesh);}
 if(scene==='switch'){g.position.set(34,1.65,42);g.camera.position.copy(g.position);g.camera.lookAt(38,1,38);document.getElementById('interact')!.hidden=false;}
 if(scene==='combat1'){g.yaw=g.camera.rotation.y;g.pitch=g.camera.rotation.x;g.state='playing';g.orientationBlocked=false;g.input.fire=true;for(let n=0;n<20;n++)g.update(.016);g.input.fire=false;g.state='review';}
 if(scene==='map'){document.getElementById('mapbutton')!.classList.add('expanded');g.fog.reveal(26,30);g.drawMap();}
 if(scene==='infantry'){const enemy=g.enemies.find(e=>e.kind==='INFANTRY')!;g.camera.position.copy(enemy.group.position).add(new T.Vector3(0,1.65,5));g.camera.lookAt(enemy.group.position.clone().add(new T.Vector3(0,1.2,0)));}
 if(scene==='train'){g.world.portal.visible=true;const exit=stages[stage].exit;g.camera.position.set(exit[0]-3,2.7,exit[1]+4);g.camera.lookAt(exit[0],1.2,exit[1]);}
 if(['rail','space','rail-play','space-play'].includes(scene)){g.ride=new RailRide(g);g.ride.progress.elapsed=scene.endsWith('play')?0:rideDurations[stage]*.32;g.ride.pose(g.ride.progress.fraction);g.ride.renderHud();if(scene.endsWith('play'))g.card.show('れっしゃで しゅっぱつ！','タップか クリックで てきを うとう！','🚂');}
 if(scene==='ending'){g.beginEnding();g.updateEnding(17);}
 g.resize();
 }
 for(const scene of scenes){const b=document.createElement('button');b.textContent=scene;b.onclick=()=>show(scene);bar.append(b);}document.body.append(bar);const selected=qs.get('scene');if(selected){show(selected);bar.style.display='none';}else{results.style.whiteSpace='pre';results.style.maxHeight='80vh';results.style.overflow='auto';}
 const benchmark=document.createElement('div');benchmark.id='benchmark';benchmark.style.cssText='position:fixed;top:0;left:0;z-index:500;background:#123b;color:#baffdb;font:12px monospace;';if(qs.has('bench')){document.body.append(benchmark);setInterval(()=>benchmark.textContent=`${g.fps.toFixed(1)} FPS / ${g.renderer.info.render.calls} calls / ${g.renderer.getPixelRatio()} DPR`,1000);}
installCampaignBot();if(selected){document.getElementById('campaign-run')!.style.display='none';document.getElementById('campaign-status')!.style.display='none';}
},500);
