import * as T from 'three';
import {game as g} from '../src/main';
import {route} from '../src/world/Navigation';
import {lineOfSight} from '../src/world/layout';
import {stages} from '../src/stages/Stages';
import {switches,lava} from '../src/world/Threats';
const waypoints=stages.map(s=>s.route);
export function installCampaignBot(){const button=document.createElement('button');button.id='campaign-run';button.textContent='RUN REAL-TIME CAMPAIGN';button.style.cssText='position:fixed;top:0;right:0;z-index:200;background:#263b;color:#fff;padding:8px';document.body.append(button);let running=false,stage=-1,index=0,started=0;const status=document.createElement('pre');status.id='campaign-status';status.style.cssText='position:fixed;bottom:0;left:0;z-index:200;color:#baffdb;background:#123c;padding:5px;font:11px monospace;';document.body.append(status);
 button.onclick=()=>{g.sound.bgm=true;g.input.touch=true;document.body.classList.add('touch');g.reset();g.resize();g.resume();document.getElementById('review-scenes')!.style.display='none';document.getElementById('testresults')!.style.display='none';stage=-1;index=0;running=true;started=performance.now();};
 setInterval(()=>{if(!running)return;if(g.card.open){g.card.close();return;}if(g.stageIndex!==stage){stage=g.stageIndex;index=0;}if(g.state==='over'){status.textContent+='\nRETRY';g.start();index=0;return;}if(g.state==='clear'){running=false;status.textContent=`CAMPAIGN COMPLETE · ${((performance.now()-started)/1000).toFixed(1)}s · ${g.failures} retries`;return;}if(g.state!=='playing')return;
 const point=waypoints[stage][index]??waypoints[stage].at(-1)!;const distance=Math.hypot(g.position.x-point[0],g.position.z-point[1]);if(distance<1.5){const sw=switches.find(s=>Math.hypot(s.x-point[0],s.z-point[1])<.5);if(sw)g.input.interact=true;const boss=g.enemies.find(e=>e.kind==='KING PUNI');if(!(point[0]===stages[stage].boss.x&&point[1]===stages[stage].boss.z&&boss?.alive))index++;}
 const next=route(g.position.x,g.position.z,point[0],point[1],g.gate)??{x:point[0],z:point[1]};const dir=new T.Vector3(next.x-g.position.x,0,next.z-g.position.z).normalize();const enemy=g.enemies.filter(e=>e.alive&&(e.kind!=='KING PUNI'||g.gate)&&lineOfSight(g.position.x,g.position.z,e.group.position.x,e.group.position.z,g.gate)).sort((a,b)=>a.group.position.distanceTo(g.position)-b.group.position.distanceTo(g.position))[0];let dx=dir.x,dz=dir.z,dy=0;if(enemy&&enemy.group.position.distanceTo(g.position)<22){dx=enemy.group.position.x-g.position.x;dz=enemy.group.position.z-g.position.z;dy=(enemy.kind==='KING PUNI'?2.2*enemy.baseScale:enemy.baseScale)+(enemy.kind==='BALLOONER'?enemy.group.position.y:0)-g.position.y;g.input.fire=true;if(g.arsenal.unlocked[2]&&g.energy>=12)g.input.weapon=2;else g.input.weapon=g.arsenal.unlocked[1]?1:0;}else g.input.fire=false;
 const yaw=Math.atan2(-dx,-dz),diff=T.MathUtils.euclideanModulo(g.yaw-yaw+Math.PI,Math.PI*2)-Math.PI;g.input.lookX=diff;g.input.lookY=g.pitch-Math.atan2(dy,Math.hypot(dx,dz));dir.applyAxisAngle(new T.Vector3(0,1,0),-yaw);g.input.mx=dir.x;g.input.my=-dir.z;
 if(g.hp<65)g.input.heal=true;if(g.poisonUntil>g.time)g.input.antidote=true;if(lava(g.position.x,g.position.z))g.input.jump=true;
 status.textContent=`ACTUAL INPUT PLAY · stage ${stage+1} · waypoint ${index}/${waypoints[stage].length}\n${g.position.x.toFixed(1)}, ${g.position.z.toFixed(1)} · health ${g.hp.toFixed(0)} · ${((performance.now()-started)/1000).toFixed(0)}s · ${g.failures} retries`;
 },60);
}
