import {it,expect} from 'vitest';
import {supportHeight,topHeight,castleRoute,castleDecks,floorNumber} from '../src/world/CastleFloors';
import {configureStage,canMoveAt,wallAt,sightAt} from '../src/world/layout';
import {doors} from '../src/world/Threats';
import {visibleTextValid} from '../src/ui/Text';
it('climbs both continuous stairways without precision jumps',()=>{configureStage(2);let feet=0;for(let z=56;z>=38;z-=.15)feet=supportHeight(30,z,feet);expect(feet).toBeCloseTo(6);for(let x=62;x<=82;x+=.15)feet=supportHeight(x,32,feet);expect(feet).toBeCloseTo(12,0);configureStage(0);});
it('does not lift a player walking under a gallery, and falling has a first-floor landing',()=>{expect(supportHeight(48,38,0)).toBe(0);expect(supportHeight(48,38,6)).toBe(6);expect(supportHeight(48,42,6)).toBe(0);expect(floorNumber(0)).toBe(1);expect(floorNumber(6)).toBe(2);expect(floorNumber(12)).toBe(3);});
it('crosses the low walls upstairs but gates the boss and reward rooms at their real elevation',()=>{configureStage(2);expect(canMoveAt(38,38,7.65,true)).toBe(true);expect(canMoveAt(38,38,1.65,true)).toBe(false);expect(canMoveAt(90,30,13.65,false)).toBe(true);expect(canMoveAt(90,30,13.65,true)).toBe(true);expect(canMoveAt(98,18,13.65,true)).toBe(false);doors[3].open=true;expect(canMoveAt(98,18,13.65,true)).toBe(true);expect(canMoveAt(98,10,13.65,true)).toBe(false);expect(sightAt(48,38,1.65,48,38,7.65,true)).toBe(false);configureStage(0);});
it('provides a continuous elevated route to the third-floor boss with kana landmarks',()=>{let y=0;configureStage(2);doors[3].open=true;for(let n=1;n<castleRoute.length-2;n++){const a=castleRoute[n-1],b=castleRoute[n],d=Math.hypot(b[0]-a[0],b[1]-a[1]);for(let t=0;t<=1;t+=.01){const x=a[0]+(b[0]-a[0])*t,z=a[1]+(b[1]-a[1])*t;y=supportHeight(x,z,y);expect(canMoveAt(x,z,y+1.65,true),`${x},${z},${y}`).toBe(true);}}expect(y).toBe(12);for(const d of castleDecks)expect(visibleTextValid(d.name)).toBe(true);configureStage(0);});
