import * as T from 'three';
import {game as g} from '../src/main';
import {movePlayer} from '../src/game/Player';
import {castleRoute,topHeight} from '../src/world/CastleFloors';
import {doors,switches} from '../src/world/Threats';
import {route} from '../src/world/Navigation';
import {fire,updateEnemies,updateShots} from '../src/game/Combat';
const panel=document.createElement('aside');panel.style.cssText='position:fixed;z-index:1000;bottom:0;left:0;max-height:36vh;overflow:auto;background:#123e;color:#cff;padding:8px;font:12px monospace';panel.innerHTML='<button id="vertical-run">CHECK VERTICAL ROUTE</button><button id="vertical-ground">GROUND</button><button id="vertical-gallery">GALLERY</button><button id="vertical-east">EAST ROOM</button><button id="vertical-boss">BOSS</button><button id="vertical-play">PLAY STAGE 3</button><button id="vertical-hide">HIDE CHECKS</button><pre id="vertical-results"></pre>';document.body.append(panel);
const result=panel.querySelector('pre')!,checks:string[]=[];
function check(name:string,ok:boolean){checks.push(`${ok?'PASS':'FAIL'} ${name}`);result.textContent=checks.join('\n');if(!ok)throw Error(name);}
function setup(){if(g.card.open)g.card.close();g.reset();g.loadStage(2);g.keyCount=2;g.state='review';g.orientationBlocked=false;g.input.reset();g.yaw=g.pitch=0;document.getElementById('challenge')!.hidden=true;document.getElementById('overlay')!.style.display='none';document.getElementById('hud')!.style.display='block';g.arsenal.unlock(2);g.input.weapon=2;g.hp=100;}
function view(x:number,z:number,y:number,tx:number,tz:number,ty:number){setup();g.position.set(x,y,z);g.camera.position.copy(g.position);g.camera.lookAt(tx,ty,tz);g.updateHud();g.fog.reveal(x,z,false,y);g.drawMap();}
function walk(x:number,z:number){g.yaw=0;for(let n=0;n<2000;n++){const dx=x-g.position.x,dz=z-g.position.z,d=Math.hypot(dx,dz);if(d<.18)break;g.input.mx=dx/d*Math.min(1,d);g.input.my=-dz/d*Math.min(1,d);g.time+=1/60;movePlayer(g,1/60);}g.input.reset();for(let n=0;n<20;n++)movePlayer(g,1/60);check(`walk ${x},${z}`,Math.hypot(x-g.position.x,z-g.position.z)<.6);}
const button=(id:string,fn:()=>void)=>document.getElementById(id)!.onclick=fn;
button('vertical-hide',()=>panel.hidden=true);
button('vertical-east',()=>view(106,18,1.65,90,18,1.65));button('vertical-ground',()=>view(26,66,1.65,30,38,7));button('vertical-gallery',()=>view(42,38,7.65,64,32,8));button('vertical-boss',()=>{view(88,28,13.65,90,18,16);g.gate=true;g.world.gate.visible=false;g.updateHud();});
button('vertical-play',()=>{setup();g.position.set(...[10,1.65,78] as [number,number,number]);g.card.seen=new Set(g.world.items.map(i=>i.kind));g.input.touch=true;document.body.classList.add('touch');g.resize();g.state='playing';});
button('vertical-run',()=>{try{checks.length=0;setup();g.position.set(66,1.65,18);walk(78,18);walk(90,18);walk(102,18);walk(106,10);walk(106,18);walk(90,18);walk(66,18);check('east ground rooms allow entry and exit while upper gates stay closed',!g.gate&&!doors[3].open);g.position.set(78,topHeight(78,32)+1.65,32);g.vy=0;walk(78,26);for(let n=0;n<150;n++)movePlayer(g,1/60);check('fall into east room lands safely',Math.abs(g.position.y-1.65)<.01);walk(78,18);walk(66,18);check('fallen player escapes east ground room without opening boss gate',g.position.x<72&&!g.gate);g.position.set(26,1.65,58);for(const point of castleRoute.slice(0,11))walk(...point);check('continuous ramps reach third floor',g.position.y>13.4);check('closed boss gate blocks progress',!doors[3].open&&!g.gate);walk(82,32);walk(90,32);g.activateSwitch(switches.find(s=>s.kind==='core')!);check('opening entrance wakes boss immediately',g.gate&&!g.world.gate.visible&&g.enemies.find(e=>e.kind==='KING PUNI')!.alert);walk(90,24);g.enterBossArena();check('entrance closes after player enters',g.world.gate.visible);check('third-floor boss remains elevated',g.enemies.find(e=>e.kind==='KING PUNI')!.group.position.y===12);
 g.position.set(48,7.65,38);g.vy=0;walk(48,44);for(let n=0;n<150;n++)movePlayer(g,1/60);check('fall lands on first floor without death',g.position.y===1.65&&g.hp===100);for(let n=0;n<40&&Math.hypot(g.position.x-30,g.position.z-56)>2;n++){const next=route(g.position.x,g.position.z,30,56,true);if(!next)throw Error('no return path');walk(next.x,next.z);}walk(30,56);walk(30,40);check('must climb staircase again after fall',g.position.y===7.65);
 const item=g.world.items.find(i=>i.kind==='AMMO CELL')!;g.position.set(item.x,1.65,item.z);g.collect();check('upper item cannot be collected from below',!item.taken);g.position.y=topHeight(item.x,item.z)+1.65;g.card.seen.add(item.kind);g.collect();check('upper item can be collected on its own floor',item.taken);
 g.card.open=false;document.getElementById('card')!.hidden=true;g.state='playing';g.gate=true;const boss=g.enemies.find(e=>e.kind==='KING PUNI')!;g.position.set(90,13.65,24);boss.brain.hit(90,24,g.time);g.time+=1;boss.telegraph=g.time-.1;boss.cooldown=0;updateEnemies(g,.016);check('boss attacks from third floor',g.shots.some(s=>s.enemy&&s.m.position.y>12));g.input.weapon=2;g.shotTime=0;g.camera.position.copy(g.position);g.camera.lookAt(boss.group.position.clone().add(new T.Vector3(0,2.2*boss.baseScale,0)));const hp=boss.hp;fire(g);check('thunderbolt hits elevated boss',boss.hp<hp);g.damage(boss,100000);check('remaining enemies keep reward sealed',!doors[3].open);for(const e of g.enemies)if(e.alive&&e.floorY>=10&&e.group.position.x>80&&e.group.position.x<98&&e.group.position.z<30)g.damage(e,100000);g.finishBossArena();check('all enemies defeated unlocks upper reward room',doors[3].open&&!g.world.gate.visible);g.position.set(90,13.65,24);walk(90,18);walk(98,18);walk(106,18);walk(106,10);check('walk through opened reward room entrance',g.position.x>100);g.state='review';g.position.set(106,13.65,10);g.card.seen.add('KEY');g.collect();check('third-floor fragment collectible',g.stageFragment);g.fog.reveal(90,24,true,13.65);g.drawMap();check('map labels current floor',document.getElementById('mapbutton')!.textContent!.includes('3かい'));check('no difficulty explanation node',!document.getElementById('challenge-info'));view(42,38,7.65,64,32,8);result.textContent=checks.join('\n')+'\nVERTICAL CHECKS COMPLETE';}catch(e){result.textContent+='\n'+e;g.state='review';}});
view(26,66,1.65,30,38,7);
