import {it,expect} from 'vitest';
import * as T from 'three';
import {NightmareReinforcements,nightmareSpawnWarning,nightmarePatrolInterval,nightmareWaveSize} from '../src/game/NightmareReinforcements';
import {Brain} from '../src/ai/Brain';
import {configureStage} from '../src/world/layout';
import type {Game} from '../src/game/Game';
function fixture(stage=0){configureStage(stage);const items:any[]=[];const g={challenge:3,stageIndex:stage,state:'playing',stageTime:0,time:10,position:new T.Vector3(26,1.65,stage?38:26),gate:false,scene:new T.Scene(),enemies:Array.from({length:6},(_,n)=>({kind:n%2?'BOTTY':'PUNI',home:{x:20+n,z:stage?38:26},alive:false,hp:0,maxHp:570,baseScale:1.2,floorY:0,group:new T.Group(),body:new T.Group(),brain:new Brain()})),world:{items,item(){items.push({mesh:new T.Group()});}},defeat:{entries:[]},routes:new Map(),routeTimes:new Map(),sound:{effect:()=>{}},notify:()=>{},burst:()=>{},dispose:(m:T.Mesh)=>{m.removeFromParent();m.geometry.dispose();(m.material as T.Material).dispose();}}as unknown as Game;return g;}
it('has three decreasing waves, rewards once and then sends two timed patrols without text',()=>{
 for(const stage of [0,1]){const g=fixture(stage),waves=new NightmareReinforcements();waves.update(g);const room=[...waves.rooms.values()][0];expect(room.limit).toBe(3);const notices:string[]=[];g.notify=(text:string)=>{notices.push(text);};
  while(room.wave<room.limit){g.stageTime=room.nextAt;waves.update(g);expect(waves.pending).not.toBeNull();expect(waves.pending!.spawns).toHaveLength(nightmareWaveSize(room.initial,room.wave+1));expect(g.enemies.every(e=>!e.alive)).toBe(true);g.stageTime+=nightmareSpawnWarning+.01;waves.update(g);expect(g.enemies.filter(e=>e.alive).length).toBeGreaterThan(0);for(const e of g.enemies.filter(e=>e.alive)){expect(e.hp).toBe(570);expect(e.group.position.distanceTo(g.position)).toBeGreaterThan(6);e.alive=false;}}
  waves.update(g);expect(room.cleared).toBe(true);expect(g.world.items).toHaveLength(2);expect(notices).toEqual(['へやを きりぬけた！ ほきゅうしよう']);g.stageTime=room.nextAt-.01;waves.update(g);expect(waves.pending).toBeNull();for(let n=0;n<3;n++){g.stageTime=room.nextAt;waves.update(g);expect(waves.pending!.spawns).toHaveLength(2);g.stageTime+=nightmareSpawnWarning+.01;waves.update(g);expect(g.enemies.filter(e=>e.alive)).toHaveLength(2);expect(room.nextAt-g.stageTime).toBeCloseTo(nightmarePatrolInterval);for(const e of g.enemies)e.alive=false;}expect(room.wave).toBe(3);expect(notices).toHaveLength(1);expect(g.world.items).toHaveLength(2);expect(g.scene.children).toHaveLength(0);
 }
});
it('pauses with gameplay and reset removes every pending spawn marker',()=>{const g=fixture(),waves=new NightmareReinforcements();g.challenge=2;waves.update(g);expect(waves.rooms.size).toBe(0);g.challenge=3;waves.update(g);g.stageTime=8;g.state='paused';waves.update(g);expect(waves.pending).toBeNull();g.state='playing';waves.update(g);expect(waves.pending).not.toBeNull();waves.reset(g);expect(waves.pending).toBeNull();expect(waves.rooms.size).toBe(0);expect(g.scene.children).toHaveLength(0);});
it('does not revive bosses, samurai or actors still in a defeat animation',()=>{for(const kind of ['KING PUNI','SAMURAI','PUNI']){const g=fixture(),waves=new NightmareReinforcements();for(const e of g.enemies)e.kind=kind as never;if(kind==='PUNI')g.defeat.entries=g.enemies.map(enemy=>({enemy}))as never;waves.update(g);g.stageTime=100;waves.update(g);expect(waves.pending).toBeNull();}});

it('uses half and quarter of the first wave, rounding a single remaining enemy upward',()=>{expect([2,3].map(w=>nightmareWaveSize(24,w))).toEqual([12,6]);expect([2,3].map(w=>nightmareWaveSize(6,w))).toEqual([3,2]);});

it('retries a cancelled emergence until the exact wave budget has appeared',()=>{const g=fixture(),waves=new NightmareReinforcements();waves.update(g);const room=[...waves.rooms.values()][0];g.stageTime=room.nextAt;waves.update(g);const occupied=waves.pending!.spawns[0];g.position.set(occupied.x,1.65,occupied.z);g.stageTime+=nightmareSpawnWarning+.01;waves.update(g);expect(room.wave).toBe(1);expect(room.emitted).toBeLessThan(3);const appeared=room.emitted;for(const e of g.enemies)e.alive=false;g.position.set(26,1.65,26);g.stageTime=room.nextAt;waves.update(g);expect(waves.pending!.spawns).toHaveLength(3-appeared);g.stageTime+=nightmareSpawnWarning+.01;waves.update(g);expect(room.wave).toBe(2);expect(room.emitted).toBe(0);});
