import {it,expect,vi,beforeEach} from 'vitest';
import * as T from 'three';
import type {Game} from '../src/game/Game';
import {Brain} from '../src/ai/Brain';
import {Arsenal} from '../src/game/Progression';
import {acquireWeapon} from '../src/game/WeaponPickup';
import {nightmareWeapons as config,nightmareWeaponPickups,specialDamage,weaponCooldown,weaponEnergy} from '../src/game/WeaponSettings';
import {applySpecialHit,cannonExplosion,cannonSelfDamage,tripleThunder,updateNightmareShot,fireNightmareWeapon} from '../src/game/NightmareWeapons';
import {configureStage,wallAt} from '../src/world/layout';
import {makeLayout,stages} from '../src/stages/Stages';
vi.mock('../src/world/World',async()=>{const t=await import('three');return {mesh:(geometry:T.BufferGeometry,color:number,x=0,y=0,z=0)=>{const m=new t.Mesh(geometry,new t.MeshStandardMaterial({color}));m.position.set(x,y,z);return m;}};});
function enemy(x:number,z:number,kind='PUNI'){const group=new T.Group();group.position.set(x,0,z);return {kind,group,alive:true,hp:570,maxHp:570,floorY:0,radius:.35,baseScale:1.65,alert:true,stunned:0,cooldown:0,brain:new Brain()};}
function fixture(){const arsenal=new Arsenal();const g={challenge:3,stageIndex:0,arsenal,input:{weapon:4,touch:false},time:10,buffs:new Map(),position:new T.Vector3(26,1.65,38),camera:new T.PerspectiveCamera(),scene:new T.Scene(),gate:true,enemies:[],shots:[],shockwaves:[],sound:{effect:vi.fn(),thunder:vi.fn()},lightning:{add:vi.fn()},burst:vi.fn(),hurt:vi.fn(),damage:vi.fn((e:any,n:number)=>{e.hp-=n;if(e.hp<=0)e.alive=false;})};return g as unknown as Game;}
beforeEach(()=>configureStage(0));
it('automatically equips each new weapon once, including variants, without changing consumables',()=>{const g=fixture();for(const kind of ['BUBBLE MODULE','STAR MODULE','KATANA','MURASAME','ASSAULT RIFLE','CANNON','THUNDER PLUS']){g.input.weapon=0;expect(acquireWeapon(g,kind)).toBe(true);expect(g.input.weapon).toBe({'BUBBLE MODULE':1,'STAR MODULE':2,KATANA:3,MURASAME:3,'ASSAULT RIFLE':4,CANNON:5,'THUNDER PLUS':6}[kind]);g.input.weapon=0;acquireWeapon(g,kind);expect(g.input.weapon).toBe(0);}for(const kind of ['POTION','ANTIDOTE','ELIXIR','PARUPUN'])expect(acquireWeapon(g,kind)).toBe(false);});
it('keeps special weapon ownership out of other difficulties and preserves role choices',()=>{const g=fixture();g.arsenal.reset();for(const mode of [0,1,2]){g.challenge=mode;for(const kind of ['ASSAULT RIFLE','CANNON','THUNDER PLUS'])acquireWeapon(g,kind);expect(g.arsenal.choices()).toEqual([0]);}g.challenge=3;for(const n of [4,5,6,3])g.arsenal.unlock(n);expect(g.arsenal.choices()).toEqual([0,4,5,6,3]);expect(g.arsenal.next(6)).toBe(3);g.arsenal.reset();expect(g.arsenal.nightmareWeapons.size).toBe(0);});
it('places one distinct weapon on an accessible approach in each adventure',()=>{for(const [stage,items]of nightmareWeaponPickups.entries()){expect(items).toHaveLength(1);const [kind,x,z]=items[0],layout=makeLayout(stages[stage]);expect(layout[Math.floor(z/4)][Math.floor(x/4)]).toBe('.');expect(kind).toBe(['ASSAULT RIFLE','CANNON','THUNDER PLUS'][stage]);expect(stages[stage].items.some(([k])=>k===kind)).toBe(false);}});
it('fires rifle shots with separate boss damage and sweeps collision without tunnelling',()=>{const g=fixture(),e=enemy(26,34);g.enemies=[e]as never;for(let n=0;n<2;n++){fireNightmareWeapon(g,new T.Vector3(0,0,-1));const s=g.shots.pop()!,previous=s.m.position.clone();s.m.position.z=30;expect(updateNightmareShot(g,s,previous)).toBe(true);expect(s.bossDamage).toBe(config.rifle.bossDamage);if(n===0)expect(e.alive).toBe(true);}expect(e.alive).toBe(false);expect(weaponCooldown(4)).toBeLessThan(.19);});
it('cannon kills an entire nearby group, deals bounded distance-based self damage and does not hit distant actors',()=>{const g=fixture(),a=enemy(26,34),b=enemy(28,34),far=enemy(30,46);g.enemies=[a,b,far]as never;cannonExplosion(g,new T.Vector3(26,1.65,36),{damage:config.cannon.damage,bossDamage:config.cannon.bossDamage});expect(a.alive||b.alive).toBe(false);expect(far.alive).toBe(true);expect(g.hurt).toHaveBeenCalledWith(14);expect(cannonSelfDamage(0)).toBe(28);expect(cannonSelfDamage(4)).toBe(0);expect(cannonSelfDamage(10)).toBe(0);});
it('cannon explodes before entering a wall and blast does not cross it',()=>{const g=fixture();g.position.set(26,1.65,22);const blocked=enemy(26,14);g.enemies=[blocked]as never;g.input.weapon=5;fireNightmareWeapon(g,new T.Vector3(0,0,-1));const s=g.shots[0],previous=s.m.position.clone();s.m.position.z=12;expect(updateNightmareShot(g,s,previous)).toBe(true);expect(blocked.alive).toBe(true);expect(g.hurt).toHaveBeenCalled();});
it('three independent penetrating rays hit all three lanes and multiple enemies in one lane',()=>{const g=fixture();g.position.set(26,1.65,38);const enemies=[enemy(26,32),enemy(26,27),enemy(24.2,30),enemy(27.8,30)];g.enemies=enemies as never;tripleThunder(g,new T.Vector3(0,0,-1));expect(g.lightning.add).toHaveBeenCalledTimes(3);expect(enemies.every(e=>!e.alive)).toBe(true);expect(g.damage).toHaveBeenCalledTimes(4);expect(weaponCooldown(6)).toBe(.42);expect(weaponEnergy(6)).toBe(3);});
it('thunder stops at walls and gives a large boss one capped hit instead of three',()=>{const g=fixture(),boss=enemy(26,30,'KING PUNI'),behind=enemy(26,14);boss.hp=5700;boss.radius=3;g.enemies=[boss,behind]as never;g.position.y=boss.baseScale*2.2;tripleThunder(g,new T.Vector3(0,0,-1));expect(boss.hp).toBe(5700-config.thunder.bossDamage);expect(behind.hp).toBe(570);expect(specialDamage('PUNI',760,285)).toBe(760);expect(specialDamage('KING PUNI',760,285)).toBe(285);});

it('lets a newly acquired legacy weapon be tried immediately even with a stronger carried weapon, then restores normal filtering',()=>{const g=fixture();g.arsenal.unlock(2);acquireWeapon(g,'BUBBLE MODULE');expect(g.arsenal.resolve(g.input.weapon)).toBe(1);expect(g.arsenal.next(1)).toBe(2);expect(g.arsenal.resolve(1)).toBe(2);});

it('preserves an alert elite attack cooldown during repeated new-weapon hits',()=>{const g=fixture(),boss=enemy(26,30,'KING PUNI');boss.hp=5700;boss.cooldown=.1;boss.brain.surprisedUntil=0;g.damage=(e,n)=>{e.hp-=n;e.cooldown=.4;e.brain.hit(26,38,g.time);};applySpecialHit(g,boss as never,45,4);expect(boss.cooldown).toBe(.1);expect(boss.brain.surprisedUntil).toBe(0);expect(boss.hp).toBe(5655);});
