import {it,expect,vi} from 'vitest';
import * as T from 'three';
import type {Game} from '../src/game/Game';
import type {Enemy} from '../src/game/Enemy';
import {configureStage} from '../src/world/layout';
import {bossPhase,nightmareAttackers,nightmarePreferredRange} from '../src/game/NightmareTactics';
import {updateNightmareBoss} from '../src/game/NightmareBoss';
import {updateSamurai,samuraiCanStrike} from '../src/game/SamuraiCombat';
function enemy(kind='PUNI'){const group=new T.Group();group.position.set(26,0,26);return {kind,group,body:new T.Group(),arms:[],radius:2.3,brain:{state:'Chase',last:{x:26,z:30}},alive:true,alert:true,floorY:0,baseScale:1,hp:2850,maxHp:2850,attackCycle:0,cooldown:0,telegraph:0,dashUntil:0,dashHit:false}as unknown as Enemy;}
function game(){configureStage(0);return {challenge:3,stageIndex:0,time:10,position:new T.Vector3(26,1.65,30),scene:new T.Scene(),gate:true,enemies:[] as Enemy[],shots:[],hurt:vi.fn(),burst:vi.fn(),notify:vi.fn(),sound:{effect:vi.fn(),impact:vi.fn()},input:{touch:true},disposeGroup:(o:T.Object3D)=>o.removeFromParent()}as unknown as Game;}
it('reserves readable tells and limits the attack budget to three even in a crowd',()=>{const g=game();g.enemies=Array.from({length:15},(_,n)=>{const e=enemy(n%3?'PUNI':'BOTTY');e.group.position.x=24+n*.2;return e;});g.enemies[0].telegraph=12;g.enemies[1].kind='SAMURAI';for(let n=0;n<30;n++){g.time=n*.2;const selected=nightmareAttackers(g);expect(selected.size).toBeLessThanOrEqual(3);expect(selected.has(g.enemies[0])).toBe(true);expect(selected.has(g.enemies[1])).toBe(true);}expect(nightmarePreferredRange(enemy('BOTTY'),true)).toBe(10);expect(nightmarePreferredRange(enemy(),false)).toBeGreaterThan(nightmarePreferredRange(enemy(),true));});
it('changes boss form at half health without increasing health',()=>expect([100,61,60,51,50,1].map(h=>bossPhase(h,100))).toEqual([0,0,0,0,1,1]));
it('final boss aimed shots have a tell, committed target and recovery',()=>{const g=game(),e=enemy('KING PUNI');configureStage(2);g.stageIndex=2;g.position.set(90,13.65,32);e.group.position.set(90,12,18);e.floorY=12;g.enemies=[e];updateNightmareBoss(g,e,.016,true,true);expect(e.telegraph).toBe(10.75);g.position.x=94;g.time=10.76;updateNightmareBoss(g,e,.016,true,true);expect(g.shots).toHaveLength(1);expect(g.shots[0].v.x).toBe(0);expect(e.group.userData.bossCombat.mode).toBe('Recovery');});
it('first boss charge locks direction and leaves a recovery',()=>{const g=game(),e=enemy('KING PUNI');g.enemies=[e];updateNightmareBoss(g,e,.016,true,true);expect(e.telegraph).toBe(10.75);g.position.x=32;g.time=10.76;updateNightmareBoss(g,e,.016,true,true);expect(e.dashX).toBe(0);expect(e.dashZ).toBe(17.5);g.time=10.9;updateNightmareBoss(g,e,.05,true,true);expect(g.hurt).not.toHaveBeenCalled();g.time=e.dashUntil+.01;updateNightmareBoss(g,e,0,true,true);expect(e.group.userData.bossCombat.mode).toBe('Recovery');});
it('samurai melee has a front arc rather than unavoidable damage all around its body',()=>{expect(samuraiCanStrike(0,0,0,3,0,4,4.2)).toBe(true);expect(samuraiCanStrike(0,0,3,0,0,4,4.2)).toBe(false);expect(samuraiCanStrike(0,0,0,-3,0,4,5.6,true)).toBe(false);expect(samuraiCanStrike(0,0,0,8,0,4,5.6,true)).toBe(false);});
it('nightmare samurai commits during stance and leaves a real recovery after its dash',()=>{configureStage(1);const g=game();configureStage(1);g.position.set(22,1.65,18);const e=enemy('SAMURAI');e.group.position.set(22,0,14);e.attackCycle=1;e.sword=new T.Group();updateSamurai(g,e,.016,true,4);expect(e.telegraph).toBe(10.7);g.position.x=26;g.time=10.71;updateSamurai(g,e,.016,true,6);expect(e.dashX).toBe(0);expect(e.dashZ).toBe(23);const recovery=e.group.userData.samuraiRecoveryUntil;g.time=e.dashUntil+.01;expect(updateSamurai(g,e,.016,true,6)).toBe(true);expect(recovery).toBeGreaterThan(g.time);expect(g.hurt).not.toHaveBeenCalled();});

it('keeps ordinary boss spacing outside its body so tells remain visible',()=>{const boss=enemy('KING PUNI');boss.radius=2.3;boss.baseScale=2.625;expect(nightmarePreferredRange(boss,true)).toBeGreaterThan(boss.radius*boss.baseScale+3);});
