import {it,expect} from 'vitest';
import {Vector3} from 'three';
import {RailProgress,railCurve,railFrame,canBoard,rideDurations,originalRideDurations,railLengthMultiplier,railSpeedMultiplier} from '../src/rail/RailCourse';
it('requires the boss reward battery and star before boarding',()=>{expect(canBoard(true,true,true)).toBe(true);for(const flags of [[false,true,true],[true,false,true],[true,true,false]])expect(canBoard(...flags as [boolean,boolean,boolean])).toBe(false);});
it('arrives once, never skips the ride, and resets after a retry',()=>{const ride=new RailProgress(0);expect(ride.update(rideDurations[0]-1)).toBe(false);expect(ride.fraction).toBeLessThan(1);expect(ride.update(1)).toBe(true);expect(ride.update(100)).toBe(false);ride.restart();expect(ride.fraction).toBe(0);expect(ride.arrived).toBe(false);expect(ride.update(-5)).toBe(false);expect(ride.fraction).toBe(0);});
it('all courses have continuous curves, hills, speed and a safe station approach',()=>{for(let stage=0;stage<3;stage++){const curve=railCurve(stage);expect(curve.getLength()/rideDurations[stage]).toBeGreaterThan(25);for(let n=0;n<100;n++){const p=curve.getPointAt(n/100),q=curve.getPointAt((n+1)/100);expect(Number.isFinite(p.x+p.y+p.z)).toBe(true);expect(p.distanceTo(q)).toBeLessThan(curve.getLength()*.014);expect(p.y).toBeGreaterThan(0);}expect(curve.getPointAt(1).y).toBe(5);}});

it('extends course distance fourfold and actual travel speed by one and a half',()=>{for(let stage=0;stage<3;stage++){const curve=railCurve(stage),origin=new Vector3(0,5,0),baseline=curve.clone();baseline.points=curve.points.map(p=>p.clone().sub(origin).divideScalar(railLengthMultiplier).add(origin));baseline.updateArcLengths();expect(curve.getLength()/baseline.getLength()).toBeCloseTo(4,6);expect((curve.getLength()/rideDurations[stage])/(baseline.getLength()/originalRideDurations[stage])).toBeCloseTo(railSpeedMultiplier,6);expect(rideDurations[stage]).toBeCloseTo(originalRideDurations[stage]*4/1.5);}});

it('provides hairpins and a real inverted loop with continuous camera frames',()=>{for(const stage of [0,2]){const c=railCurve(stage);expect(c.points.some((p,n)=>n>0&&p.z>c.points[n-1].z)).toBe(true);}for(const stage of [1,2]){const c=railCurve(stage);let inverted=false;let previous=railFrame(c,0).q;for(let n=1;n<=1000;n++){const f=railFrame(c,n/1000);if(f.up.y<-.7)inverted=true;expect(Math.abs(previous.dot(f.q))).toBeGreaterThan(.93);previous=f.q;}expect(inverted).toBe(true);}});
