import * as T from 'three';
import type {Game}from '../Game';import type {Enemy}from '../Enemy';import type {BossState}from './BossState';
const glow=(color:number)=>new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.7,roughness:.35});
function part(g:T.Group,geometry:T.BufferGeometry,color:number,x=0,y=0,z=0){const m=new T.Mesh(geometry,glow(color));m.position.set(x,y,z);g.add(m);return m;}
export function prepareBossAppearance(e:Enemy,stage:number){if(e.group.userData.bossAppearance)return;const g=new T.Group();e.body.add(g);e.group.userData.bossAppearance=g;
 if(stage===0){for(const side of [-1,1]){const fist=new T.Group();fist.position.set(side*2.15,2.1,0);part(fist,new T.CapsuleGeometry(.22,.65,4,12),0xf1bf76,0,0,0);part(fist,new T.TorusGeometry(.35,.07,6,16),0xa8ffef,0,-.42,-.1).rotation.x=Math.PI/2;g.add(fist);e.arms.push(fist);}const core=part(g,new T.OctahedronGeometry(.32,1),0x8cfff3,0,2.3,-2.2);core.visible=false;e.group.userData.exposedBossCore=core;e.group.userData.bossArmor=[-1,1].map(side=>part(g,new T.BoxGeometry(.38,.7,.12),0xffd797,side*.2,2.3,-2.25));}
 if(stage===1){const crest=part(g,new T.OctahedronGeometry(.32,0),0xffed92,0,5.8,0);crest.rotation.z=Math.PI/4;const rim=part(g,new T.TorusGeometry(.85,.035,5,24),0x89ffdd,0,5.6,0);rim.rotation.x=Math.PI/2;g.userData.realCrest=crest;part(g,new T.TorusGeometry(.5,.055,6,24),0x8affdf,0,2.35,-2.15);part(g,new T.OctahedronGeometry(.28,0),0xffed92,0,2.35,-2.22).rotation.z=Math.PI/4;}
 if(stage===2){const blade=new T.Group();blade.position.set(2.5,1.6,-.2);part(blade,new T.BoxGeometry(.16,3.4,.07),0xd5f7ff,0,1.7,0).rotation.z=-.15;part(blade,new T.TorusGeometry(.32,.07,6,16),0xffd782).rotation.x=Math.PI/2;part(blade,new T.CylinderGeometry(.08,.08,.55,10),0x706da7,0,-.3);g.add(blade);const blaster=new T.Group();blaster.position.set(-2.4,2,-.5);part(blaster,new T.CylinderGeometry(.3,.35,1.3,16),0x98e4ff).rotation.x=Math.PI/2;part(blaster,new T.TorusGeometry(.35,.05,6,20),0xffd782,0,0,-.7);g.add(blaster);e.group.userData.bossBlade=blade;e.group.userData.bossBlaster=blaster;}
}
export function clearTell(g:Game,s:BossState){if(s.tell){g.disposeGroup(s.tell);s.tell=undefined;}}
export function floorTell(g:Game,e:Enemy,s:BossState,kind:'circle'|'line'|'warp',radius=6,point?:{x:number;z:number}){clearTell(g,s);const group=new T.Group(),p=point??e.group.position,mat=new T.MeshBasicMaterial({color:kind==='warp'?0x9feeff:kind==='line'?0xffc272:0xffa7d8,transparent:true,opacity:.6,depthWrite:false});
 if(kind==='line'){const dx=s.aim.x-e.group.position.x,dz=s.aim.z-e.group.position.z,angle=Math.atan2(dx,dz);for(const side of [-1,1]){const v=new T.Vector3(Math.sin(angle)*12,e.floorY+.1,Math.cos(angle)*12);const line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(e.group.position.x+side*.7,e.floorY+.1,e.group.position.z),new T.Vector3(e.group.position.x+v.x+side*.7,e.floorY+.1,e.group.position.z+v.z)]),new T.LineBasicMaterial({color:0xffc272,transparent:true,opacity:.6}));group.add(line);}mat.dispose();}
 else{const ring=new T.Mesh(new T.TorusGeometry(radius,.07,6,40),mat);ring.position.set(p.x,e.floorY+.1,p.z);ring.rotation.x=Math.PI/2;group.add(ring);}g.scene.add(group);s.tell=group;
}
export function stunnedStars(e:Enemy,s:BossState){if(s.stars)return;const group=new T.Group();for(let n=0;n<3;n++){const m=part(group,new T.OctahedronGeometry(.22,0),0xffdc7c,Math.sin(n*2.094),0,Math.cos(n*2.094));m.rotation.z=Math.PI/4;}group.position.y=5.8;e.body.add(group);s.stars=group;}
export function bossPose(e:Enemy,s:BossState,time:number){if(s.tell)s.tell.children.forEach(o=>{if(o instanceof T.Mesh)(o.material as T.MeshBasicMaterial).opacity=.4+Math.sin(time*7)*.16;});if(s.stars){s.stars.visible=s.mode==='Stunned';s.stars.rotation.y=time*3;}
 if(s.mode==='Windup'){e.body.rotation.x=s.action==='charge'?-.16:s.action==='slam'?.1:0;for(const arm of e.arms)arm.rotation.x=s.action==='slam'?-1.9:-.7;}
 if(s.mode==='Stunned'){e.body.rotation.z=Math.sin(time*9)*.06;for(const arm of e.arms)arm.rotation.x=.3;}
 const blade=e.group.userData.bossBlade as T.Group|undefined,blaster=e.group.userData.bossBlaster as T.Group|undefined;if(blade){blade.visible=s.action==='slash'||s.action==='advance';blade.rotation.z=s.mode==='Windup'||e.telegraph>time?-.9:s.mode==='Attack'?1.1:-.15;}if(blaster)blaster.visible=!blade?.visible;
 const core=e.group.userData.exposedBossCore as T.Mesh|undefined;if(core){core.visible=s.second&&s.nightmare;for(const armor of e.group.userData.bossArmor??[])armor.visible=!core.visible;}
}
