import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GraphicsQuality,graphicsBudget} from './GraphicsQuality';
import {ShaderWarmup} from './ShaderWarmup';
import {gpuReady} from './GpuReady';
/** Direct rendering with baked AO prioritizes consistent input response. */
export class RenderPipeline{
 quality:GraphicsQuality;environment:T.WebGLRenderTarget;width=1;height=1;preparing=false;ready:Promise<void>=Promise.resolve();private generation=0;private jobs=new Set<ShaderWarmup>();private badge?:HTMLDivElement;onContextLoss=()=>{};beforeDraw=()=>{};onReady=()=>{};
 constructor(public renderer:T.WebGLRenderer,public scene:T.Scene,public camera:T.PerspectiveCamera,touch:boolean){this.quality=new GraphicsQuality(touch,innerWidth,innerHeight,navigator.hardwareConcurrency);const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();this.environment=pmrem.fromScene(room,.04);room.dispose();pmrem.dispose();scene.environment=this.environment.texture;scene.environmentIntensity=.4;renderer.toneMappingExposure=1.05;renderer.info.autoReset=false;this.resize(innerWidth,innerHeight);renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();this.cancelPreparation();this.preparing=true;this.onContextLoss();if(this.badge){this.badge.hidden=false;this.badge.firstElementChild!.textContent='がめんを なおしているよ…';}for(const id of ['start','practice']){const button=document.getElementById(id) as HTMLButtonElement|null;if(button)button.disabled=true;}});renderer.domElement.addEventListener('webglcontextrestored',()=>{this.quality.tier='low';this.environment.dispose();const generator=new T.PMREMGenerator(renderer),room=new RoomEnvironment();this.environment=generator.fromScene(room,.04);this.scene.environment=this.environment.texture;room.dispose();generator.dispose();this.resize(this.width,this.height);this.prepare();});}
 resize(w:number,h:number){this.width=w;this.height=h;const budget=graphicsBudget[this.quality.tier];this.renderer.setPixelRatio(Math.min(devicePixelRatio,budget.pixelRatio));this.renderer.setSize(w,h);this.renderer.shadowMap.enabled=budget.shadow>0;}
 cancelPreparation(){this.generation++;for(const job of this.jobs)job.cancel();this.jobs.clear();this.preparing=false;}
 prepare(){this.cancelPreparation();const generation=this.generation;this.preparing=true;
  if(!this.badge){this.badge=document.createElement('div');this.badge.id='render-loading';this.badge.setAttribute('role','status');this.badge.style.cssText='position:fixed;left:50%;bottom:max(18px,env(safe-area-inset-bottom));transform:translateX(-50%);z-index:150;padding:10px 18px;border-radius:14px;background:#18354be8;color:#efffff;font:600 16px sans-serif;pointer-events:none';const label=document.createElement('div');label.textContent='じゅんびちゅう…';const bar=document.createElement('div');bar.style.cssText='height:3px;background:#9affd4;margin-top:7px;transform-origin:left';this.badge.append(label,bar);document.body.append(this.badge);}
  this.badge.firstElementChild!.textContent='じゅんびちゅう…';this.badge.hidden=false;for(const id of ['start','practice']){const button=document.getElementById(id) as HTMLButtonElement|null;if(button)button.disabled=true;}
  const job=new ShaderWarmup(this.renderer,this.scene,this.camera);this.jobs.add(job);
  this.ready=job.prepare(n=>{if(generation===this.generation)(this.badge!.lastElementChild as HTMLElement).style.transform=`scaleX(${n})`;}).then(async ready=>{if(generation!==this.generation){job.dispose();this.jobs.delete(job);return;}if(!ready&&this.renderer.getContext().isContextLost())return;this.renderer.compile(this.scene,this.camera);this.beforeDraw();this.renderer.render(this.scene,this.camera);await gpuReady(this.renderer);if(generation!==this.generation)return;for(const prepared of this.jobs)prepared.dispose();this.jobs.clear();this.preparing=false;this.onReady();this.badge!.hidden=true;for(const id of ['start','practice']){const button=document.getElementById(id) as HTMLButtonElement|null;if(button)button.disabled=false;}});
 }

 sample(fps:number){if(this.quality.sample(fps)){this.resize(this.width,this.height);this.prepare();return true;}return false;}
 render(){if(this.preparing)return;this.renderer.info.reset();this.renderer.render(this.scene,this.camera);for(const job of this.jobs)job.dispose();this.jobs.clear();}
}
