import {midi} from '../music/score';
export class Synth {
noise:AudioBuffer; master:GainNode; music:GainNode; effects:GainNode; duck:GainNode; reverb:ConvolverNode; delay:DelayNode;delayWet:GainNode;delayFeedback:GainNode;active=0;sources=new Set<AudioScheduledSourceNode>();private tempo=0;
constructor(public ctx:AudioContext){this.master=ctx.createGain();this.master.gain.value=.72;const comp=ctx.createDynamicsCompressor();comp.threshold.value=-14;comp.knee.value=16;comp.ratio.value=5;comp.attack.value=.006;comp.release.value=.15;this.master.connect(comp);comp.connect(ctx.destination);this.music=ctx.createGain();this.music.gain.value=.6;this.duck=ctx.createGain();this.duck.gain.value=1;this.music.connect(this.duck);this.duck.connect(this.master);this.effects=ctx.createGain();this.effects.gain.value=.7;this.effects.connect(this.master);
this.noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);const data=this.noise.getChannelData(0);let seed=821;for(let n=0;n<data.length;n++){seed=(seed*16807)%2147483647;data[n]=seed/1073741824-1;}
const impulse=ctx.createBuffer(2,Math.floor(ctx.sampleRate*1.1),ctx.sampleRate);for(let ch=0;ch<2;ch++){const a=impulse.getChannelData(ch);for(let n=0;n<a.length;n++)a[n]=(Math.random()*2-1)*(1-n/a.length)**3*.22;}this.reverb=ctx.createConvolver();this.reverb.buffer=impulse;const wet=ctx.createGain();wet.gain.value=.22;this.reverb.connect(wet);wet.connect(this.music);this.delay=ctx.createDelay(.8);this.delay.delayTime.value=.246;this.delayFeedback=ctx.createGain();this.delayFeedback.gain.value=.23;const echoFilter=ctx.createBiquadFilter();echoFilter.type='lowpass';echoFilter.frequency.value=2800;this.delay.connect(echoFilter);echoFilter.connect(this.delayFeedback);this.delayFeedback.connect(this.delay);this.delayWet=ctx.createGain();this.delayWet.gain.value=.15;echoFilter.connect(this.delayWet);this.delayWet.connect(this.music);}
setTiming(tempo:number,clearMix:boolean,time:number){
 const wet=clearMix?.045:.075,feedback=clearMix?.1:.14;
 if(this.tempo!==tempo){
  // Moving a live delay tap bends pitch. Change it only after fading the echo.
  this.delayWet.gain.cancelScheduledValues(time);this.delayWet.gain.setTargetAtTime(0,time,.015);
  this.delayFeedback.gain.setTargetAtTime(0,time,.015);
  this.delay.delayTime.setValueAtTime(30/tempo,time+.12);
  this.delayWet.gain.setTargetAtTime(wet,time+.2,.06);
  this.delayFeedback.gain.setTargetAtTime(feedback,time+.2,.06);this.tempo=tempo;
 }
}
voice(note:number,time:number,duration:number,kind:'bass'|'pluck'|'chord'|'lead',volume:number,pan=0){const ctx=this.ctx;const g=ctx.createGain(),filter=ctx.createBiquadFilter(),p=ctx.createStereoPanner();p.pan.value=pan;filter.type='lowpass';const cutoff={bass:750,pluck:3800,chord:1700,lead:4100}[kind];filter.frequency.setValueAtTime(cutoff,time);filter.frequency.exponentialRampToValueAtTime(kind==='bass'?220:700,time+duration);filter.Q.value=kind==='bass'?1.2:.5;const attack=kind==='chord'?.035:kind==='lead'?.012:.006;g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(volume,time+attack);g.gain.exponentialRampToValueAtTime(Math.max(.001,volume*.35),time+duration*.7);g.gain.exponentialRampToValueAtTime(.001,time+duration+.09);filter.connect(g);g.connect(p);p.connect(this.music);if(kind!=='bass'){g.connect(this.reverb);if(kind==='lead'||kind==='pluck')g.connect(this.delay);}const count=kind==='bass'?2:3;let finished=0;for(let n=0;n<count;n++){const o=ctx.createOscillator();o.type=kind==='bass'?(n?'triangle':'sine'):kind==='pluck'?(n?'sine':'triangle'):kind==='chord'?'sawtooth':(n===0?'triangle':'sawtooth');o.frequency.value=midi(note)*(kind==='bass'&&n===1?.5:kind==='pluck'&&n>0?n+1:1);o.detune.value=(n-(count-1)/2)*(kind==='chord'?8:kind==='lead'?5:2);const v=ctx.createGain();v.gain.value=kind==='pluck'?[.65,.25,.1][n]:kind==='bass'?[.65,.35][n]:1/count;o.connect(v);v.connect(filter);this.active++;this.sources.add(o);o.onended=()=>{this.sources.delete(o);this.active--;o.disconnect();v.disconnect();if(++finished===count){filter.disconnect();g.disconnect();p.disconnect();}};o.start(time);o.stop(time+duration+.12);}}
kick(time:number,volume=.45){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.frequency.setValueAtTime(145,time);o.frequency.exponentialRampToValueAtTime(45,time+.12);g.gain.setValueAtTime(volume,time);g.gain.exponentialRampToValueAtTime(.001,time+.25);o.connect(g);g.connect(this.music);o.start(time);o.stop(time+.26);this.sources.add(o);o.onended=()=>{this.sources.delete(o);o.disconnect();g.disconnect();};}
noiseHit(time:number,kind:'snare'|'hat'|'clap'|'fx',volume:number,pan=0){const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner();s.buffer=this.noise;f.type=kind==='snare'?'bandpass':'highpass';f.frequency.value=kind==='hat'?7500:kind==='fx'?2200:1800;f.Q.value=.6;const dur=kind==='hat'?.06:kind==='fx'?1.3:.18;p.pan.value=pan;g.gain.setValueAtTime(kind==='fx'?.001:volume,time);if(kind==='fx')g.gain.linearRampToValueAtTime(volume,time+dur*.75);g.gain.exponentialRampToValueAtTime(.001,time+dur);s.connect(f);f.connect(g);g.connect(p);p.connect(this.music);s.start(time);s.stop(time+dur+.02);this.sources.add(s);s.onended=()=>{this.sources.delete(s);s.disconnect();f.disconnect();g.disconnect();p.disconnect();};if(kind==='snare')this.kick(time,volume*.12);}
stopAll(){for(const s of this.sources){try{s.stop(this.ctx.currentTime+.03);}catch{}}}
percussion(time:number,volume=.04){this.noiseHit(time,'clap',volume,-.55);}
}
