import {configureSurface} from './PBRMaterial';
import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
const maps=new Map<string,T.CanvasTexture>();
export type ToySurface='panel'|'wood'|'tile'|'armor'|'sticker'|'rubber';
function star(c:CanvasRenderingContext2D,x:number,y:number,r:number){c.beginPath();for(let n=0;n<10;n++){const a=n*Math.PI/5-Math.PI/2,d=n%2?r*.46:r;n?c.lineTo(x+Math.cos(a)*d,y+Math.sin(a)*d):c.moveTo(x+Math.cos(a)*d,y+Math.sin(a)*d);}c.closePath();c.fill();}
/** Original illustrated sheets; shared across all scenery to bound texture memory. */
export function toySheet(kind:ToySurface){if(maps.has(kind))return maps.get(kind)!;const a=document.createElement('canvas');a.width=a.height=512;const c=a.getContext('2d')!;const gradient=c.createLinearGradient(0,0,512,512);gradient.addColorStop(0,kind==='wood'?'#ffdf9d':'#fff8e7');gradient.addColorStop(1,kind==='wood'?'#bd854a':'#b2dfe8');c.fillStyle=gradient;c.fillRect(0,0,512,512);
 if(kind==='wood'){for(let n=0;n<55;n++){c.strokeStyle=n%3?'#9e67252a':'#ffffff38';c.lineWidth=2+n%3;c.beginPath();for(let x=0;x<=512;x+=8){const y=n*10+Math.sin(x*.018+n)*4;x?c.lineTo(x,y):c.moveTo(x,y);}c.stroke();}}
 else if(kind==='rubber'){c.fillStyle='#c5d5df';c.fillRect(0,0,512,512);for(let y=0;y<512;y+=16)for(let x=0;x<512;x+=16){c.fillStyle='#ffffff70';c.beginPath();c.arc(x+4,y+4,3,0,7);c.fill();}}
 else{const step=128;for(let y=0;y<512;y+=step)for(let x=0;x<512;x+=step){c.fillStyle=kind==='armor'?['#3d8ea0','#225c83','#76bec1'][(x/step+y/step)%3]:['#ffe4ad','#b9eae0','#d4c7f2','#fbc5d7'][(x/step+2*y/step)%4];c.beginPath();c.roundRect(x+4,y+4,step-8,step-8,kind==='tile'?12:18);c.fill();c.strokeStyle='#ffffffbd';c.lineWidth=3;c.stroke();c.strokeStyle='#497b8738';c.lineWidth=2;c.strokeRect(x+12,y+12,step-24,step-24);if(kind==='armor'){c.fillStyle='#ffe9a8';for(let k=0;k<3;k++)c.fillRect(x+15,y+18+k*12,step-30,3);}else{c.fillStyle='#ffffffbb';star(c,x+step*.5,y+step*.48,step*.19);c.fillStyle='#f1bb60';c.beginPath();c.arc(x+20,y+20,4,0,7);c.fill();}}}
 if(kind==='sticker'){c.fillStyle='#ffefd1';c.beginPath();c.roundRect(32,32,448,448,70);c.fill();c.strokeStyle='#50b6c6';c.lineWidth=12;c.stroke();c.fillStyle='#ffbd53';star(c,256,208,108);c.fillStyle='#385879';c.beginPath();c.arc(225,198,9,0,7);c.arc(285,198,9,0,7);c.fill();c.lineWidth=7;c.strokeStyle='#385879';c.beginPath();c.arc(256,215,28,.15,Math.PI-.15);c.stroke();for(let n=0;n<6;n++){c.fillStyle=n%2?'#e99cc6':'#77cfc6';c.beginPath();c.arc(90+n*66,390,14,0,7);c.fill();}}
 const t=new T.CanvasTexture(a);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=4;maps.set(kind,t);return t;}
export function toyMaterial(color:number,kind:ToySurface='panel',emissive=0){return configureSurface(new T.MeshStandardMaterial({color,map:toySheet(kind),emissive,emissiveIntensity:.28}),kind==='wood'?'wood':kind==='rubber'?'rubber':kind==='armor'?'metal':'plastic');}
export function toyPart(g:T.Group,geometry:T.BufferGeometry,material:T.Material,x=0,y=0,z=0){const m=new T.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;g.add(m);return m;}
/** Batch one scenery cluster, retaining local bounds so distant chunks are culled. */
export function batchToy(g:T.Group){g.updateMatrixWorld(true);const buckets=new Map<T.Material,T.Mesh[]>();for(const o of g.children)if(o instanceof T.Mesh&&!Array.isArray(o.material)){const list=buckets.get(o.material)??[];list.push(o);buckets.set(o.material,list);}for(const [mat,parts]of buckets){if(parts.length<2)continue;const geometries=parts.map(p=>{p.updateMatrix();return(p.geometry.index?p.geometry.toNonIndexed():p.geometry.clone()).applyMatrix4(p.matrix);});const geometry=mergeGeometries(geometries);if(geometry){const m=new T.Mesh(geometry,mat);m.castShadow=m.receiveShadow=true;g.add(m);for(const p of parts){g.remove(p);p.geometry.dispose();}}for(const geo of geometries)geo.dispose();}}
export function toyLandmark(theme:number,variant:number){const g=new T.Group(),pink=toyMaterial(0xffb7d2),blue=toyMaterial(0x99deed),gold=toyMaterial(0xffda88,'wood'),white=toyMaterial(0xffffff,'sticker'),metal=toyMaterial(0xaacbff,'armor',theme?0x385eaf:0);const mats=[pink,blue,gold];
 if(theme===0&&variant%3===0){toyPart(g,new T.CylinderGeometry(.55,.8,12,20),gold,0,6);const wheel=toyPart(g,new T.TorusGeometry(7,.38,10,64),blue,0,12);for(let n=0;n<10;n++){const a=n*Math.PI/5,x=Math.cos(a)*7,y=12+Math.sin(a)*7;const bar=toyPart(g,new T.CylinderGeometry(.1,.1,7,8),gold,x/2,(y+12)/2);bar.rotation.z=a-Math.PI/2;toyPart(g,new RoundedBoxGeometry(1.7,1.8,1.4,2,.2),mats[n%3],x,y-.6);toyPart(g,new T.PlaneGeometry(.8,.8),white,x,y-.5,-.73);}wheel.rotation.y=.05;}
 else if(theme===0&&variant%3===1){toyPart(g,new T.CylinderGeometry(5,6,.7,32),blue,0,.4);toyPart(g,new T.ConeGeometry(6,3,32),pink,0,7);for(let n=0;n<6;n++){const a=n*Math.PI/3,x=Math.sin(a)*4,z=Math.cos(a)*4;toyPart(g,new T.CylinderGeometry(.12,.12,6,10),gold,x,3.6,z);const horse=toyPart(g,new T.CapsuleGeometry(.55,1,6,16),mats[n%3],x,2,z);horse.rotation.z=Math.PI/2;toyPart(g,new T.SphereGeometry(.45,20,12),white,x-.6,2.7,z);}toyPart(g,new T.SphereGeometry(.6,20,16),gold,0,8.8);}
 else if(theme===0){for(let n=0;n<3;n++){const x=(n-1)*3.7;toyPart(g,new RoundedBoxGeometry(3.5,5+n*2,3.5,3,.3),mats[n],x,(5+n*2)/2);toyPart(g,new T.ConeGeometry(2.7,3,24),white,x,6.5+n*2);for(let k=0;k<3;k++)toyPart(g,new T.PlaneGeometry(.9,1.1),metal,x,1.5+k*1.8,-1.78);}}
 else if(variant%3===0){toyPart(g,new T.SphereGeometry(3,32,24),blue,0,6);const orbit=toyPart(g,new T.TorusGeometry(6,.35,12,64),pink,0,6);orbit.rotation.x=.9;for(const x of [-1,1]){toyPart(g,new T.CylinderGeometry(.6,.6,9,16),gold,x*5,5);toyPart(g,new RoundedBoxGeometry(5,.25,4,2,.15),metal,x*6,8);toyPart(g,new T.PlaneGeometry(2,2),white,x*6,8.2,-2.1);}toyPart(g,new T.ConeGeometry(1,4,24),gold,0,11);}
 else if(variant%3===1){const body=toyPart(g,new T.LatheGeometry([new T.Vector2(0,0),new T.Vector2(2.2,.3),new T.Vector2(2.2,6),new T.Vector2(1.4,8),new T.Vector2(0,10)],32),white,0,1);for(const x of [-1,1]){const fin=toyPart(g,new T.CapsuleGeometry(.5,3,6,16),pink,x*2,3);fin.rotation.z=-x*.4;}toyPart(g,new T.TorusGeometry(.9,.16,10,32),gold,0,6,-2.1);toyPart(g,new T.SphereGeometry(.7,24,16),metal,0,6,-2.2);body.rotation.z=.12;}
 else{for(let n=0;n<3;n++){const ring=toyPart(g,new T.TorusGeometry(5+n*1.5,.2,10,64),mats[n],0,8+n*2);ring.rotation.x=Math.PI/2;}toyPart(g,new T.CylinderGeometry(2,3,5,24),metal,0,6);toyPart(g,new T.SphereGeometry(1.3,24,16),white,0,12);}
 batchToy(g);return g;}
