import {toyTrain,stationTrack} from '../rail/TrainModel';
import {applyItemTextures} from './ObjectTextures';
import {candyTexture} from './CandyTexture';
import {hazardParticles} from '../effects/HazardVfx';
import {activeStage,stages} from '../stages/Stages';import {decorate} from './StageDecor';
import * as T from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {layout,cell,keys} from './layout';import {paintTexture,glow,fluidTexture} from './Art';import {areaAt} from '../game/Progression';import {doors,switches,pools,lavaPools,resetDoors} from './Threats';
export const material=(color:number)=>new T.MeshStandardMaterial({color,roughness:.42,metalness:.3});
export function mesh(g:T.BufferGeometry,c:number,x=0,y=0,z=0){const m=new T.Mesh(g,material(c));m.position.set(x,y,z);return m;}
export type Item={kind:string,mesh:T.Object3D,x:number,z:number,taken:boolean};
export class World {
 disposed=false;fx:T.Points[]=[];group=new T.Group();items:Item[]=[];gate:T.Object3D;portal:T.Mesh;pad:T.Object3D;platform:T.Object3D;doorMeshes:T.Group[]=[];switchMeshes:T.Mesh[]=[];liquids:T.Mesh[]=[];spinners:T.Mesh[]=[];wallMaterial:T.MeshStandardMaterial;floorMaterial:T.MeshStandardMaterial;bridges:T.Mesh[]=[];chest=new T.Group();
 constructor(scene:T.Scene){const stage=stages[activeStage];resetDoors();scene.add(this.group);const wallMap=activeStage===1?candyTexture('icing'):paintTexture(activeStage===0?'stone':'panel');this.wallMaterial=new T.MeshStandardMaterial({color:activeStage===0?0xffe7bb:activeStage===1?0xffbdd1:0xc9c5e5,map:wallMap,bumpMap:wallMap,bumpScale:.07,roughness:.47,metalness:.35,emissive:0x24223c,emissiveIntensity:.2});this.floorMaterial=new T.MeshStandardMaterial({color:0xc5d0df,map:paintTexture('floor'),roughness:.58,metalness:.35});if(activeStage!==1)new T.TextureLoader().load(`${import.meta.env.BASE_URL}assets/${activeStage===0?'toy-wall-v3.png':'citadel-wall.png'}`,t=>{if(this.disposed){t.dispose();return;}t.colorSpace=T.SRGBColorSpace;t.anisotropy=4;this.wallMaterial.map=t;this.wallMaterial.bumpMap=t;this.wallMaterial.needsUpdate=true;},undefined,()=>{});
 const wallCells:{x:number,z:number}[]=[],floorCells:{x:number,z:number}[]=[];for(let r=0;r<layout.length;r++)for(let c=0;c<layout[r].length;c++)(layout[r][c]==='#'?wallCells:floorCells).push({x:c*cell+2,z:r*cell+2});
 const walls=new T.InstancedMesh(new RoundedBoxGeometry(3.97,5,3.97,2,.14),this.wallMaterial,wallCells.length);walls.castShadow=true;walls.receiveShadow=true;const floors=new T.InstancedMesh(new T.BoxGeometry(3.98,.25,3.98),this.floorMaterial,floorCells.length);floors.receiveShadow=true;const matrix=new T.Matrix4();wallCells.forEach((p,n)=>walls.setMatrixAt(n,matrix.makeTranslation(p.x,2.5,p.z)));const types=activeStage===0?['stone','stone','stone','stone','stone'] as const:activeStage===1?['circuit','circuit','circuit','circuit','circuit'] as const:['floor','floor','lavafloor','floor','floor'] as const;for(let area=0;area<5;area++){const cells=floorCells.filter(p=>areaAt(p.x,p.z)===area),mat=new T.MeshStandardMaterial({map:activeStage===1?candyTexture('wafer'):paintTexture(types[area]),emissive:activeStage===2?0x242147:0,emissiveIntensity:.18,color:activeStage===0?0xe0dbaf:activeStage===1?0xffedcb:[0xbab1cf,0xaecbd6,0xc1a0a3,0xaeb98c,0xadb0d0][area],roughness:area===0?.85:area===3?.25:.55,metalness:area===0?.05:.4});const tile=new T.InstancedMesh(floors.geometry,mat,cells.length);tile.receiveShadow=true;cells.forEach((p,n)=>tile.setMatrixAt(n,matrix.makeTranslation(p.x,-.15,p.z)));this.group.add(tile);}wallCells.forEach((p,n)=>walls.setColorAt(n,new T.Color(activeStage===0?[0xffffff,0xeafffa,0xfff1dc][n%3]:activeStage===1?[0xfad4cf,0xb8e7db,0xd1c2ed][n%3]:0xc6afdb)));this.group.add(walls);
 const trims=new T.InstancedMesh(new T.BoxGeometry(3.99,.18,3.99),new T.MeshStandardMaterial({color:0xb28e58,metalness:.65,roughness:.3}),wallCells.length*2);wallCells.forEach((p,n)=>{trims.setMatrixAt(n*2,matrix.makeTranslation(p.x,.35,p.z));trims.setMatrixAt(n*2+1,matrix.makeTranslation(p.x,4.65,p.z));});this.group.add(trims);
 for(let r=1;r<layout.length-1;r++)for(let c=1;c<layout[r].length-1;c++)if(layout[r][c]==='#'&&(r+c)%3===0){for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]])if(layout[r+dz]?.[c+dx]!=='#'){const p=mesh(new T.BoxGeometry(.15,2.2,.12),0x72ddd8,c*4+2+dx*2.04,2.5,r*4+2+dz*2.04);if(dx)p.rotation.y=Math.PI/2;p.material=glow(0x48cbd2);this.group.add(p);}}
 for(const k of keys)this.item('KEY',k.x,k.z,0xffcf61);
 for(const [k,x,z,c]of stage.items)this.item(k,x,z,c);
 this.gate=new T.Group();for(let a=0;a<7;a++){const m=mesh(new T.BoxGeometry(.48,5,.6),[0xff7189,0xffba64,0xffe277,0x86dfbc,0x67cfe5,0x8997e9,0xd9a0f2][a],a*.5-1.5,2.5,0);this.gate.add(m);}const bg=stage.bossGate??[18,14];this.gate.position.set(bg[0]*4+2,0,bg[1]*4+2);this.gate.rotation.y=Math.PI/2;this.gate.visible=activeStage===2;this.group.add(this.gate);if(activeStage===2)this.arch(bg[0]*4+2,bg[1]*4+2,Math.PI/2,5.5);
 for(const d of doors){const [dc,dr]=d.cells[0],vertical=layout[dr-1]?.[dc]==='#'||layout[dr+1]?.[dc]==='#';const group=new T.Group();const width=d.cells.length*4;const m=mesh(new RoundedBoxGeometry(width,4.6,.45,2,.1),0x533870,0,2.3,0);(m.material as T.MeshStandardMaterial).map=wallMap;group.add(m);for(const a of [-1,1]){const stripe=mesh(new T.BoxGeometry(.14,3,.5),0xffac6c,a*width*.3,2.4,0);stripe.material=glow(0xed9665);group.add(stripe);}group.position.set(d.x,0,d.z);if(vertical)group.rotation.y=Math.PI/2;this.group.add(group);this.doorMeshes.push(group);this.arch(d.x,d.z,vertical?Math.PI/2:0,width+1);}
 for(const s of switches){const base=mesh(new T.CylinderGeometry(.38,.48,1.1,10),0x9f7b57,s.x,.55,s.z);this.group.add(base);const b=mesh(new T.CylinderGeometry(.25,.25,.18,16),0xffcc76,s.x,1.16,s.z);b.material=glow(0xf19a64);this.group.add(b);this.switchMeshes.push(b);}
 for(const p of pools){const liquid=mesh(new T.CircleGeometry(1,48),0x8bdd6e,p.x,.012,p.z);liquid.rotation.x=-Math.PI/2;liquid.scale.set(p.rx,p.rz,1);liquid.material=new T.MeshStandardMaterial({map:fluidTexture('toxic'),emissiveMap:fluidTexture('toxic'),color:0xaddf8a,emissive:0x78bc6c,emissiveIntensity:.7,transparent:true,opacity:.86,metalness:.6,roughness:.16});this.group.add(liquid);this.liquids.push(liquid);const edge=mesh(new T.TorusGeometry(1,.045,6,48),0xddb559,p.x,.045,p.z);edge.rotation.x=-Math.PI/2;edge.scale.set(p.rx,p.rz,1);this.group.add(edge);for(let n=0;n<6;n++){const bubble=mesh(new T.SphereGeometry(.1,8,6),0xd4f86c,p.x+Math.sin(n*8)*p.rx*.65,.08,p.z+Math.cos(n*5)*p.rz*.65);this.group.add(bubble);this.spinners.push(bubble);}}
 for(const p of lavaPools){const liquid=mesh(new T.CircleGeometry(1,48),0xff9c35,p.x,.035,p.z);liquid.rotation.x=-Math.PI/2;liquid.scale.set(p.rx,p.rz,1);liquid.material=new T.MeshStandardMaterial({map:fluidTexture('lava'),emissiveMap:fluidTexture('lava'),color:0xffd1ab,emissive:0xff653d,emissiveIntensity:.8,roughness:.2,metalness:.2});this.group.add(liquid);this.liquids.push(liquid);const light=new T.PointLight(0xff7336,18,12,2);light.position.set(p.x,1,p.z);scene.add(light);for(let n=0;n<8;n++){const stone=mesh(new T.DodecahedronGeometry(.3),0x523444,p.x+Math.cos(n*.785)*p.rx,.2,p.z+Math.sin(n*.785)*p.rz);this.group.add(stone);}}
 for(const p of [...pools,...lavaPools]){const fx=hazardParticles(p.x,p.z,p.rx,p.rz,lavaPools.includes(p));this.fx.push(fx);this.group.add(fx);}
 for(let n=0;n<3;n++){const bridge=mesh(new RoundedBoxGeometry(2.5,.35,2.5,2,.1),0xd9b577,stage.bridge[0]-6+n*6,.55,stage.bridge[1]);bridge.visible=false;this.group.add(bridge);this.bridges.push(bridge);}
 const base=mesh(new RoundedBoxGeometry(1.5,.8,1,2,.1),0x523352,0,.4,0);const lid=mesh(new T.CylinderGeometry(.53,.53,1.5,12,1,false,0,Math.PI),0xc8975d,0,.8,0);lid.rotation.z=Math.PI/2;this.chest.add(base,lid);this.chest.add(mesh(new T.BoxGeometry(.25,.3,.08),0xffdf79,0,.65,-.54));this.chest.position.set(activeStage===2?14:activeStage===1?86:66,0,activeStage===2?14:activeStage===1?54:42);this.group.add(this.chest);
 for(let n=0;n<3;n++){const stair=mesh(new RoundedBoxGeometry(1.8,.18*(n+1),2.2,2,.06),0xb69877,65+n*1.8,.09*(n+1),18);this.group.add(stair);}
 this.portal=mesh(new T.BoxGeometry(.01,.01,.01),0x96ffda,stage.exit[0],0,stage.exit[1]);this.portal.add(toyTrain());stationTrack(this.group,...stage.exit);this.portal.visible=false;this.group.add(this.portal);this.arch(stage.exit[0],stage.exit[1]+1,0,6);
 this.pad=mesh(new T.CylinderGeometry(1.5,1.5,.3,24),0x734695,stage.start[0]+12,.15,stage.start[1]+2);this.group.add(this.pad);const ring=mesh(new T.TorusGeometry(1.1,.06,8,32),0xf9b979,stage.start[0]+12,.33,stage.start[1]+2);ring.rotation.x=Math.PI/2;ring.material=glow(0xef9cb8);this.group.add(ring);this.platform=mesh(new RoundedBoxGeometry(3,.5,3,2,.15),0x849bbf,stage.bridge[0],.7,stage.bridge[1]);this.group.add(this.platform);
 for(const [x,z]of [[14,8],[50,8],[86,8],[14,50],[54,46],[94,60]]){this.arch(x,z,0,6);const light=new T.PointLight(z>32?0x95d98c:x>64?0xff9a65:0xb8bcff,12,15,2);light.position.set(x,4.5,z);scene.add(light);}
 const engine=new T.Group();engine.position.set(54,0,14);engine.add(mesh(new T.CylinderGeometry(1.1,1.3,.6,12),0x5c536f,0,.3));const core=mesh(new T.OctahedronGeometry(.7,1),0x6bdbdd,0,2.5);core.material=glow(0x65b8ed);engine.add(core);for(let n=0;n<3;n++){const orbit=mesh(new T.TorusGeometry(1.3,.12,8,36),0xd8b677,0,2.5);orbit.rotation.set(n*.9,.6+n*.7,0);engine.add(orbit);this.spinners.push(orbit);}for(const a of [-1,1]){engine.add(mesh(new T.CylinderGeometry(.18,.28,3.7,10),0x708995,a*1.1,1.85));}this.group.add(engine);
 const vat=new T.Group();vat.position.set(64,0,46);const glass=mesh(new T.CylinderGeometry(1,1,3.7,24),0x65b88d,0,2.2);glass.material=new T.MeshPhysicalMaterial({color:0x80ddae,transparent:true,opacity:.27,roughness:.13,metalness:.2,side:T.DoubleSide});vat.add(glass);const goo=mesh(new T.CylinderGeometry(.85,.85,2.5,20),0x839e35,0,1.7);goo.material=new T.MeshStandardMaterial({color:0x87bd51,map:fluidTexture('toxic'),emissive:0x4b9a47,emissiveIntensity:.4});vat.add(goo);for(const y of [.45,4.1])vat.add(mesh(new T.CylinderGeometry(1.25,1.25,.3,16),0xaa8770,0,y));const pipe=mesh(new T.TorusGeometry(1.3,.17,10,24,Math.PI),0x797593,0,4.5);pipe.rotation.y=Math.PI/2;vat.add(pipe);this.group.add(vat);
 const furnace=new T.Group();furnace.position.set(96,0,20);furnace.add(mesh(new T.CylinderGeometry(1.3,1.5,3.5,10),0x74314e,0,1.75));for(let n=0;n<8;n++){const a=n*Math.PI/4,m=mesh(new T.BoxGeometry(.12,2.5,.18),0xff8f48,Math.sin(a)*1.3,1.9,Math.cos(a)*1.3);m.material=glow(0xff7a35);furnace.add(m);}for(const y of [.3,3.6]){const rim=mesh(new T.TorusGeometry(1.35,.15,8,24),0xdab67c,0,y);rim.rotation.x=Math.PI/2;furnace.add(rim);}furnace.add(mesh(new T.CylinderGeometry(.6,.9,3,12),0x40314a,0,5));this.group.add(furnace);engine.visible=activeStage>0;vat.visible=activeStage===1;furnace.visible=activeStage===2;decorate(this.group,activeStage,stage.w,stage.h);
 for(let n=0;n<12;n++){const x=8+n*9,z=n%2?-10:83;const tower=new T.Group();const pts=[new T.Vector2(3,0),new T.Vector2(3.5,1),new T.Vector2(2.8,2),new T.Vector2(2.5,12),new T.Vector2(3,13),new T.Vector2(1.7,14),new T.Vector2(.5,20),new T.Vector2(0,23)];tower.add(mesh(new T.LatheGeometry(pts,16),n%2?0x473570:0x315e69));for(let a=0;a<3;a++){const hoop=mesh(new T.TorusGeometry(2.7,.15,8,24),0xe2ae70,0,4+a*4,0);hoop.rotation.x=Math.PI/2;tower.add(hoop);}tower.position.set(x,0,z);this.group.add(tower);}
 for(let n=0;n<5;n++){const gear=mesh(new T.TorusGeometry(3,.22,8,12),0xdbb977,20+n*19,13+n%2*4,30);gear.rotation.x=.5;this.group.add(gear);this.spinners.push(gear);for(let a=0;a<8;a++){const tooth=mesh(new T.BoxGeometry(.7,.5,.5),0xdbb977,Math.cos(a*Math.PI/4)*3,Math.sin(a*Math.PI/4)*3,0);tooth.rotation.z=a*Math.PI/4;gear.add(tooth);}}
 }
 arch(x:number,z:number,yaw:number,width:number){const g=new T.Group();for(const a of [-1,1]){g.add(mesh(new T.CylinderGeometry(.3,.45,5.8,12),0x846c94,a*width/2,2.9,0));const trim=mesh(new T.TorusGeometry(.42,.08,6,16),0xeac37c,a*width/2,4.5,0);trim.rotation.x=Math.PI/2;g.add(trim);}const arc=mesh(new T.TorusGeometry(width/2,.24,8,28,Math.PI),0xcc9f6d,0,5.7,0);g.add(arc);g.position.set(x,0,z);g.rotation.y=yaw;this.group.add(g);}
 item(kind:string,x:number,z:number,color:number){const group=new T.Group();let geometry:T.BufferGeometry;if(kind==='BATTERY'){geometry=new T.CylinderGeometry(.25,.25,.95,20);const cap=mesh(new T.CylinderGeometry(.12,.12,.12,12),0xffe5a1,0,.52,0);group.add(cap);const band=mesh(new T.CylinderGeometry(.255,.255,.2,20),0x6adcac,0,.1,0);group.add(band);}else if(kind==='KATANA'){const blade=mesh(new T.CylinderGeometry(.035,.08,1.8,4),0xa9ffee,0,.55,0);blade.material=glow(0x77e6dc);group.add(blade);const grip=mesh(new T.CylinderGeometry(.07,.07,.4,12),0x293b58,0,-.55,0);group.add(grip);const guard=mesh(new T.TorusGeometry(.2,.04,8,24),0xffdc80,0,-.3,0);guard.rotation.x=Math.PI/2;group.add(guard);geometry=new T.SphereGeometry(.01,4,4);}else if(kind==='KEY'||kind.includes('STAR')){const s=new T.Shape();for(let n=0;n<10;n++){const a=n*Math.PI/5+Math.PI/2,r=n%2?.28:.65;const x=Math.cos(a)*r,y=Math.sin(a)*r;n?s.lineTo(x,y):s.moveTo(x,y);}s.closePath();geometry=new T.ExtrudeGeometry(s,{depth:.16,bevelEnabled:true,bevelThickness:.05,bevelSize:.04,bevelSegments:2});}else if(kind.includes('POTION')||kind==='ANTIDOTE'){geometry=new T.LatheGeometry([new T.Vector2(.12,0),new T.Vector2(.28,.06),new T.Vector2(.28,.42),new T.Vector2(.12,.55),new T.Vector2(.12,.7)],16);}else if(kind.includes('CELL'))geometry=new RoundedBoxGeometry(.5,.7,.35,2,.07);else if(kind.includes('MODULE')||kind.includes('UPGRADE'))geometry=new T.TorusKnotGeometry(.3,.1,48,8,2,3);else geometry=new T.TorusKnotGeometry(.3,.09,40,8,2,3);const item=mesh(geometry,color);group.add(item);if(kind.includes('POTION')||kind==='ANTIDOTE'){const stopper=mesh(new T.CylinderGeometry(.15,.15,.14,10),0xc6a474,0,.73,0);group.add(stopper);const label=mesh(new T.TorusGeometry(.29,.035,6,24),0xffedbe,0,.26,0);label.rotation.x=Math.PI/2;group.add(label);}applyItemTextures(group,kind);const halo=mesh(new T.TorusGeometry(.82,.025,6,32),color);halo.material=glow(color);group.add(halo);group.position.set(x,1.3,z);this.group.add(group);this.items.push({kind,mesh:group,x,z,taken:false});}
 reset(){resetDoors();for(const b of this.bridges)b.visible=false;for(const d of this.doorMeshes)d.position.y=0;}
 update(t:number){for(const fx of this.fx)(fx.material as T.ShaderMaterial).uniforms.clock.value=t;for(const i of this.items)if(!i.taken){i.mesh.rotation.y=t*.6;i.mesh.position.y=1.3+Math.sin(t*2+i.x)*.16;}doors.forEach((d,n)=>this.doorMeshes[n].position.y=T.MathUtils.lerp(this.doorMeshes[n].position.y,d.open?4.9:0,.12));switches.forEach((s,n)=>(this.switchMeshes[n].material as T.MeshStandardMaterial).emissive.setHex(s.door>=0&&doors[s.door].open?0x58eab8:0xeb945b));this.platform.position.y=.7+Math.sin(t)*.6;for(const l of this.liquids){const mat=l.material as T.MeshStandardMaterial;if(mat.map){mat.map.offset.x=t*.012;mat.map.offset.y=t*.007;}}for(const o of this.spinners){if(o.geometry instanceof T.TorusGeometry)o.rotation.z=t*.12;else o.position.y=.08+Math.abs(Math.sin(t*1.5+o.position.x))*.23;}}
}
