import {railEnemyScale} from '../game/EnemyScale';
import {challenges} from '../game/Challenge';
import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import type {Game} from '../game/Game';
import {Enemy} from '../game/Enemy';
import {mesh} from '../world/World';
import {paintTexture} from '../world/Art';
import {railCurve,RailProgress,railLengthMultiplier,rideDurations} from './RailCourse';
import {toyTrain} from './TrainModel';
import {railTexture} from './RailArt';
type Target={enemy:Enemy;fraction:number;hp:number;cooldown:number;side:number;origin:T.Vector3};
type Bullet={mesh:T.Mesh;v:T.Vector3;life:number};
/** Separate collision space: dungeon walls never block a shot on the sky railway. */
export class RailRide {
 group=new T.Group();progress:RailProgress;curve:T.CatmullRomCurve3;targets:Target[]=[];bullets:Bullet[]=[];traces:{line:T.Line;life:number}[]=[];sky:T.Mesh;train:T.Group;shotAt=0;kills=0;lookYaw=0;lookPitch=0;disposed=false;
 oldShadows:boolean;oldWeapon:number;oldFog:T.Fog|T.FogExp2|null;oldFov:number;
 constructor(public g:Game){this.progress=new RailProgress(g.stageIndex);this.curve=railCurve(g.stageIndex);this.oldShadows=g.renderer.shadowMap.enabled;this.oldWeapon=g.input.weapon;this.oldFog=g.scene.fog;this.oldFov=g.camera.fov;g.camera.fov=82;g.camera.updateProjectionMatrix();g.input.weapon=0;g.scene.fog=new T.Fog(g.stageIndex>0?0x514575:0xcce5ef,80,185);g.renderer.shadowMap.enabled=false;g.scene.add(this.group);g.worldScene.visible=false;g.atmosphere.group.visible=false;for(const e of g.enemies)e.group.visible=false;
  const skyMaterial=new T.MeshBasicMaterial({map:railTexture('sky',g.stageIndex>0),side:T.BackSide,depthWrite:false,fog:false});
  this.sky=new T.Mesh(new T.SphereGeometry(200,24,16),skyMaterial);this.group.add(this.sky);
  if(g.stageIndex>0){const positions=[];for(let n=0;n<850;n++){const a=n*2.399963,y=((n*137)%850)/850*1.7-.7,r=Math.sqrt(1-y*y)*180;positions.push(Math.cos(a)*r,y*180,Math.sin(a)*r);}const stars=new T.Points(new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(positions,3)),new T.PointsMaterial({color:0xdbeaff,size:.8,depthWrite:false}));this.sky.add(stars);}

  const left:T.Vector3[]=[],right:T.Vector3[]=[];const points=360*railLengthMultiplier,supportCount=45*railLengthMultiplier,islandCount=60*railLengthMultiplier,landmarkCount=30*railLengthMultiplier;
  const sleepers=new T.InstancedMesh(new RoundedBoxGeometry(2.5,.18,.38,1,.035),new T.MeshStandardMaterial({color:0xffffff,map:railTexture('metal'),roughness:.34,metalness:.12}),points);
  const supports=new T.InstancedMesh(new T.CylinderGeometry(.23,.4,1,8),new T.MeshStandardMaterial({color:0xc29c75,roughness:.6}),supportCount);const dummy=new T.Object3D();
  for(let n=0;n<points;n++){const f=n/(points-1),p=this.curve.getPointAt(f),t=this.curve.getTangentAt(f),side=new T.Vector3(-t.z,0,t.x).normalize();left.push(p.clone().addScaledVector(side,.83));right.push(p.clone().addScaledVector(side,-.83));dummy.position.copy(p);dummy.rotation.set(0,Math.atan2(-t.x,-t.z),0);dummy.scale.set(1,1,1);dummy.updateMatrix();sleepers.setMatrixAt(n,dummy.matrix);}
  for(const path of [left,right])this.group.add(new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(path),points,.11,6,false),new T.MeshStandardMaterial({color:0xbdefff,roughness:.22,metalness:.4})));
  for(let n=0;n<supportCount;n++){const p=this.curve.getPointAt(n/(supportCount-1)),height=p.y+13;dummy.position.set(p.x,p.y-height/2,p.z);dummy.rotation.set(0,0,0);dummy.scale.set(1,height,1);dummy.updateMatrix();supports.setMatrixAt(n,dummy.matrix);}this.group.add(sleepers,supports);
  const islands=new T.InstancedMesh(new T.DodecahedronGeometry(1,1),new T.MeshStandardMaterial({color:g.stageIndex===1?0xe1adbd:0x86bfa9,map:paintTexture('stone'),roughness:.7}),islandCount);
  const trees=new T.InstancedMesh(new T.SphereGeometry(1,16,12),new T.MeshStandardMaterial({color:g.stageIndex>0?0xb4a8ed:0xffffff,map:railTexture('meadow'),emissive:g.stageIndex>0?0x493175:0x18331b,emissiveIntensity:.3,roughness:.8}),islandCount);
  for(let n=0;n<islandCount;n++){const f=n/(islandCount-1),p=this.curve.getPointAt(f),t=this.curve.getTangentAt(f),side=new T.Vector3(-t.z,0,t.x).normalize();p.addScaledVector(side,(n%2?1:-1)*(13+n%5*5));const size=5+n%4*2;dummy.position.set(p.x,p.y-8,p.z);dummy.scale.set(size,3,size);dummy.updateMatrix();islands.setMatrixAt(n,dummy.matrix);dummy.position.y=p.y-3;dummy.scale.set(3+n%2,2+n%3,3);dummy.updateMatrix();trees.setMatrixAt(n,dummy.matrix);}this.group.add(islands,trees);
  const towerPaint=railTexture('metal');
  const meadow=new T.MeshStandardMaterial({map:railTexture('meadow'),roughness:.9,color:g.stageIndex>0?0xb8aae3:0xffffff});
  for(let n=0;n<landmarkCount;n++){const p=this.curve.getPointAt(n/(landmarkCount-1)),t=this.curve.getTangentAt(n/(landmarkCount-1)),side=new T.Vector3(-t.z,0,t.x).normalize();p.addScaledVector(side,(n%2?1:-1)*(18+n%4*7));const top=new T.Mesh(new T.CylinderGeometry(6,7,.7,24),meadow);top.position.copy(p).add(new T.Vector3(0,-5,0));this.group.add(top);if(g.stageIndex===0){const tower=mesh(new RoundedBoxGeometry(2,6+n%4,2,2,.18),[0xffb493,0x8ac9eb,0xffdf7f][n%3],p.x,p.y-1,p.z);(tower.material as T.MeshStandardMaterial).map=towerPaint;this.group.add(tower);const roof=mesh(new T.ConeGeometry(2.2,2,12),0xf5a5bb,p.x,p.y+3+n%4*.5,p.z);this.group.add(roof);}}
  const cloudMat=new T.MeshBasicMaterial({color:g.stageIndex>0?0x9e91dd:0xfff9ef});const clouds=new T.InstancedMesh(new T.SphereGeometry(1,12,10),cloudMat,landmarkCount*3);for(let n=0;n<landmarkCount*3;n++){const f=Math.floor(n/3)/(landmarkCount-1),p=this.curve.getPointAt(f),t=this.curve.getTangentAt(f);p.addScaledVector(new T.Vector3(-t.z,0,t.x).normalize(),(n%2?1:-1)*(30+n%5*5));dummy.position.set(p.x+(n%3-1)*4,p.y+18+n%4*3,p.z);dummy.scale.set(6,2,4);dummy.updateMatrix();clouds.setMatrixAt(n,dummy.matrix);}this.group.add(clouds);
  if(g.stageIndex>0){for(let n=0;n<12;n++){const p=this.curve.getPointAt(.06+n*.08);p.add(new T.Vector3((n%2?1:-1)*40,30,-35));const planet=mesh(new T.SphereGeometry(7,28,20),[0xb9d9ff,0xffb6d2,0xb29aee][n],p.x,p.y,p.z);const mat=planet.material as T.MeshStandardMaterial;mat.map=railTexture('planet');mat.roughness=.78;mat.emissive.setHex(0x463875);mat.emissiveIntensity=.5;this.group.add(planet);const ring=mesh(new T.TorusGeometry(10,.28,8,64),0xf1d4ff,p.x,p.y,p.z);ring.rotation.set(.7,.3,n*.5);this.group.add(ring);}}

  for(let n=1;n<(g.stageIndex>0?30:9)*railLengthMultiplier;n++){const f=n/((g.stageIndex>0?31:10)*railLengthMultiplier),p=this.curve.getPointAt(f),t=this.curve.getTangentAt(f),hoop=mesh(new T.TorusGeometry(5,.15,8,40),[0xffc875,0x9effdc,0xff93bc][n%3],p.x,p.y+2,p.z);(hoop.material as T.MeshStandardMaterial).emissive.copy((hoop.material as T.MeshStandardMaterial).color);(hoop.material as T.MeshStandardMaterial).emissiveIntensity=g.stageIndex>0?1.3:.3;hoop.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),t);this.group.add(hoop);}
  // Spaced encounters give time to aim between hills, without covering the rails.
  const count=Math.ceil([10,14,18][g.stageIndex]*railLengthMultiplier*challenges[g.challenge].count);for(let n=0;n<count;n++){const fraction=.13+n*(.76/(count-1)),p=this.curve.getPointAt(fraction),t=this.curve.getTangentAt(fraction),side=n%2?-1:1;p.addScaledVector(new T.Vector3(-t.z,0,t.x).normalize(),side*(4.3+n%3));const kind=n%3===0?'BALLOONER':'BOTTY';const enemy=new Enemy(kind,p.x,p.z);enemy.baseScale=railEnemyScale;enemy.group.scale.setScalar(enemy.baseScale);enemy.group.position.y=p.y+.1;this.group.add(enemy.group);this.targets.push({enemy,fraction,hp:(kind==='BOTTY'?3:1)*challenges[g.challenge].hp,cooldown:1.2,side,origin:enemy.group.position.clone()});const platform=mesh(new T.CylinderGeometry(2.4,1.7,.45,16),0xe8c586,p.x,p.y-.25,p.z);this.group.add(platform);}
  this.train=toyTrain(true);this.train.scale.setScalar(.95);this.group.add(this.train);
  const destination=this.curve.getPointAt(1);const platform=mesh(new RoundedBoxGeometry(12,.6,12,2,.15),0xf5d496,destination.x,destination.y-.3,destination.z-4);this.group.add(platform);
  for(const side of [-1,1]){this.group.add(mesh(new T.CylinderGeometry(.3,.45,7,12),0x9ddce0,destination.x+side*4,destination.y+3,destination.z-4));}
  this.group.add(mesh(new RoundedBoxGeometry(9,.7,1.2,2,.15),0xffb990,destination.x,destination.y+6.7,destination.z-4));
  g.clearTransient();g.hp=Math.max(65,g.hp);g.poisonUntil=g.paralyzedUntil=0;document.getElementById('danger')!.className='';document.getElementById('threat')!.textContent='';g.mapOpen=false;g.input.reset();g.sound.music?.restart();g.sound.music?.setStage(g.stageIndex);g.sound.music?.setCombat(3);this.setUi(true);this.pose(0);this.renderHud();
 }
 setUi(active:boolean){for(const id of ['mapbutton']){const element=document.getElementById(id);if(element)element.style.display=active?'none':'';}const weapon=document.getElementById('weapon') as HTMLButtonElement;weapon.disabled=active;weapon.style.pointerEvents=active?'none':'';document.getElementById('interact')!.hidden=true;document.getElementById('bossbar')!.hidden=true;}
 pose(f:number){const p=this.curve.getPointAt(f),t=this.curve.getTangentAt(f);this.g.position.copy(p).add(new T.Vector3(0,3.05,0));this.g.camera.position.copy(this.g.position);const baseYaw=Math.atan2(-t.x,-t.z),basePitch=Math.atan2(t.y,Math.hypot(t.x,t.z));const shake=Math.max(0,(this.g.shakeUntil-this.g.time)/.32)*.05;const turn=(this.curve.getTangentAt(Math.min(1,f+.02)).x-t.x)*.45;this.g.camera.rotation.order='YXZ';this.g.camera.rotation.set(basePitch+this.lookPitch+Math.sin(this.g.time*95)*shake,baseYaw+this.lookYaw+Math.cos(this.g.time*83)*shake,T.MathUtils.clamp(turn,-.12,.12));this.g.yaw=baseYaw+this.lookYaw;this.g.pitch=basePitch+this.lookPitch;this.train.position.copy(p).add(new T.Vector3(0,.12,0));this.train.rotation.set(0,baseYaw,0);this.sky.position.copy(p);this.g.gun.position.set(0,-.18,-.6);this.g.gun.rotation.z=-.03;this.g.camera.updateMatrixWorld();}
 fire(){const g=this.g;if(g.time<this.shotAt)return;this.shotAt=g.time+.17;const aim=g.input.tapAim;g.input.tapAim=null;const direction=aim?new T.Vector3(aim.x,aim.y,.5).unproject(g.camera).sub(g.camera.position).normalize():new T.Vector3(0,0,-1).applyQuaternion(g.camera.quaternion);let target:Target|undefined,nearest=110;
  for(const enemy of this.targets){if(enemy.hp<=0)continue;const center=enemy.enemy.group.position.clone().add(new T.Vector3(0,1.6*railEnemyScale/1.3,0)),delta=center.sub(g.position),distance=delta.dot(direction);if(distance<=0||distance>nearest)continue;const off=delta.clone().addScaledVector(direction,-distance).length();if(off<(g.input.touch?2.35:1.8)*railEnemyScale/1.3){target=enemy;nearest=distance;}}
  const end=g.position.clone().addScaledVector(direction,nearest);if(target){target.hp--;g.burst(target.enemy.group.position.clone().add(new T.Vector3(0,1.5*railEnemyScale/1.3,0)),0xffdd80);if(target.hp<=0){this.kills++;g.score+=100;target.enemy.alive=false;g.defeat.add(g,target.enemy);g.sound.effect(980);}}
  const start=g.position.clone().add(new T.Vector3(0,-.3,0));const line=new T.Line(new T.BufferGeometry().setFromPoints([start,end]),new T.LineBasicMaterial({color:0xffef96,transparent:true,opacity:.85}));this.group.add(line);this.traces.push({line,life:.12});g.sound.effect(850);
 }
 update(dt:number){const g=this.g;g.input.weapon=0;this.lookYaw=T.MathUtils.clamp(this.lookYaw-g.input.lookX,-.85,.85);this.lookPitch=T.MathUtils.clamp(this.lookPitch-g.input.lookY,-.55,.65);g.input.lookX=g.input.lookY=0;const arrived=this.progress.update(dt);this.pose(this.progress.fraction);if(g.input.fire)this.fire();g.input.interact=false;
  for(const target of this.targets){if(target.hp<=0)continue;const enemy=target.enemy;enemy.group.rotation.y=Math.atan2(enemy.group.position.x-g.position.x,enemy.group.position.z-g.position.z);enemy.animate(g.time,true);if(enemy.kind==='BALLOONER'){const tangent=this.curve.getTangentAt(target.fraction);enemy.group.position.x=target.origin.x-tangent.z*Math.sin(g.time*2.2+target.fraction*10)*3;enemy.group.position.z=target.origin.z+tangent.x*Math.sin(g.time*2.2+target.fraction*10)*3;}if(enemy.kind==='BALLOONER')enemy.group.position.y=target.origin.y+2+Math.sin(g.time*2)*.5;const distance=enemy.group.position.distanceTo(g.position);if(target.fraction<this.progress.fraction-.04||distance>55)continue;target.cooldown-=dt;if(target.cooldown<=0){target.cooldown=1.8;const origin=enemy.group.position.clone().add(new T.Vector3(0,1.5*railEnemyScale/1.3,0)),future=this.curve.getPointAt(Math.min(1,this.progress.fraction+.35/rideDurations[g.stageIndex])).add(new T.Vector3(0,3.05,0));const bullet=mesh(new T.SphereGeometry(.32,12,8),0xff85a2);bullet.position.copy(origin);this.group.add(bullet);this.bullets.push({mesh:bullet,v:future.sub(origin).normalize().multiplyScalar(36),life:2});}}
  for(let n=this.bullets.length-1;n>=0;n--){const b=this.bullets[n];b.life-=dt;const previous=b.mesh.position.clone();b.mesh.position.addScaledVector(b.v,dt);const segment=new T.Line3(previous,b.mesh.position),closest=segment.closestPointToPoint(g.position,true,new T.Vector3()),hit=closest.distanceTo(g.position)<1.25;if(hit)g.hurt(7+g.stageIndex*2);if(hit||b.life<=0){b.mesh.removeFromParent();b.mesh.geometry.dispose();(b.mesh.material as T.Material).dispose();this.bullets.splice(n,1);}}
  for(let n=this.traces.length-1;n>=0;n--){const x=this.traces[n];x.life-=dt;if(x.life<=0){x.line.removeFromParent();x.line.geometry.dispose();(x.line.material as T.Material).dispose();this.traces.splice(n,1);}}
  if(g.input.heal){g.hp=g.supplies.heal(g.hp);g.input.heal=false;}g.input.antidote=false;g.updateParticles(dt);if(g.time>g.hudTime||arrived){g.hudTime=g.time+.1;this.renderHud();}
  if(arrived&&g.state==='playing')g.arriveTrain();
 }
 renderHud(){const g=this.g;g.updateHud();document.getElementById('objective')!.textContent=`えきまで ${Math.ceil((1-this.progress.fraction)*100)} · たおした ${this.kills}`;document.getElementById('area')!.textContent=['そらいろ レール','ほしぞら レール','にじの レール'][g.stageIndex];document.getElementById('weaponname')!.textContent='れっしゃブラスター';document.getElementById('bossbar')!.hidden=true;}
 restart(){this.g.clearTransient();for(const x of this.traces){x.line.removeFromParent();x.line.geometry.dispose();(x.line.material as T.Material).dispose();}this.traces=[];this.progress.restart();this.kills=0;this.shotAt=0;for(const target of this.targets){target.hp=(target.enemy.kind==='BOTTY'?3:1)*challenges[this.g.challenge].hp;target.enemy.alive=true;target.enemy.group.visible=true;target.enemy.body.visible=true;target.enemy.body.rotation.set(0,0,0);target.enemy.group.scale.setScalar(target.enemy.baseScale);target.enemy.group.position.copy(target.origin);target.cooldown=1.2;}for(const b of this.bullets){b.mesh.removeFromParent();b.mesh.geometry.dispose();(b.mesh.material as T.Material).dispose();}this.bullets=[];this.g.hp=100;this.g.hurtTime=0;this.lookYaw=this.lookPitch=0;this.pose(0);}
 dispose(){if(this.disposed)return;this.disposed=true;this.setUi(false);this.g.renderer.shadowMap.enabled=this.oldShadows;this.g.scene.fog=this.oldFog;this.g.input.weapon=this.oldWeapon;this.g.camera.fov=this.oldFov;this.g.camera.updateProjectionMatrix();for(const x of this.traces){x.line.geometry.dispose();(x.line.material as T.Material).dispose();}this.traces=[];this.g.clearTransient();this.g.disposeGroup(this.group);this.g.worldScene.visible=true;this.g.atmosphere.group.visible=true;for(const e of this.g.enemies)e.group.visible=e.alive;}
}
