import * as T from 'three';
export class Atmosphere {
 group=new T.Group();sun:T.DirectionalLight;ambient:T.HemisphereLight;sky:T.Mesh;stars:T.Points;moonLight:T.DirectionalLight;moon:T.Mesh;sunOrb:T.Mesh;clouds:T.InstancedMesh;meteors:T.Line[]=[];phase=0;
 constructor(public scene:T.Scene){scene.add(this.group);this.ambient=new T.HemisphereLight(0xb3ddff,0x6c8a69,2.4);this.sun=new T.DirectionalLight(0xffebbc,3);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-80,right:80,top:65,bottom:-65,far:200});this.sun.shadow.bias=-.001;this.sun.shadow.normalBias=.05;this.sun.target.position.set(50,0,30);scene.add(this.ambient,this.sun,this.sun.target);
 const mat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color()},bottom:{value:new T.Color()},clock:{value:0}},vertexShader:'varying vec3 v; void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;uniform float clock;varying vec3 v; void main(){float h=clamp(normalize(v).y*.8+.25,0.,1.);float bands=sin(v.x*.025+v.z*.016+clock*.006)*sin(v.z*.031-v.x*.008);vec3 c=mix(bottom,top,pow(h,.65));c+=vec3(.06,.07,.085)*smoothstep(.45,.9,bands)*(1.-h)*.5;gl_FragColor=vec4(c,1.);}'});
 this.sky=new T.Mesh(new T.SphereGeometry(175,24,16),mat);this.sky.position.set(50,0,30);this.group.add(this.sky);
 const positions=[];let seed=518;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};for(let n=0;n<500;n++){const a=rand()*Math.PI*2,y=rand()*.83+.12,r=Math.sqrt(1-y*y);positions.push(50+Math.cos(a)*r*145,y*145,30+Math.sin(a)*r*145);}this.stars=new T.Points(new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(positions,3)),new T.PointsMaterial({color:0xfff0cf,size:.6,transparent:true,opacity:0,depthWrite:false}));this.group.add(this.stars);
 this.moonLight=new T.DirectionalLight(0xc8dcff,0);this.moonLight.position.set(115,65,-55);this.moonLight.target.position.set(50,0,35);scene.add(this.moonLight,this.moonLight.target);
 this.moon=new T.Mesh(new T.SphereGeometry(6,24,16),new T.MeshBasicMaterial({color:0xf7eed0}));this.moon.position.set(115,65,-55);this.group.add(this.moon);this.sunOrb=new T.Mesh(new T.SphereGeometry(4,20,12),new T.MeshBasicMaterial({color:0xffe5a2}));this.group.add(this.sunOrb);
 this.clouds=new T.InstancedMesh(new T.SphereGeometry(1,12,8),new T.MeshStandardMaterial({color:0xfff5eb,roughness:1,transparent:true,opacity:.7,depthWrite:false}),30);for(let n=0;n<30;n++){const m=new T.Matrix4().compose(new T.Vector3((n%10)*21-50,30+(n%3)*5,n<15?-34:96),new T.Quaternion(),new T.Vector3(5+n%4,1.8,3));this.clouds.setMatrixAt(n,m);}this.group.add(this.clouds);
 for(let n=0;n<3;n++){const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(-7,2,0)]);const line=new T.Line(geo,new T.LineBasicMaterial({color:0xbffaff,transparent:true,opacity:0}));this.meteors.push(line);this.group.add(line);}
 scene.fog=new T.Fog(0xaad7ea,45,150);this.update(0,0);
 }
 update(stage:number,elapsed:number){this.phase=stage===2?Math.min(1,elapsed/150):0;const night=this.phase;const sky=this.sky.material as T.ShaderMaterial;sky.uniforms.top.value.set(stage===0?0x75c9ee:stage===1?0x51bcea:0x945aab).lerp(new T.Color(0x182356),night);sky.uniforms.bottom.value.set(stage===0?0xd4f1ec:stage===1?0xffecc4:0xffb386).lerp(new T.Color(0x7a75ac),night);sky.uniforms.clock.value=elapsed;
 this.sun.position.set(30+night*95,70*(1-night)+8,5);this.sun.color.set(stage===2?0xffb98c:0xffeed1).lerp(new T.Color(0x96aafa),night);this.sun.intensity=(stage===1?3.2:2.5)*(1-night)+1.1*night;this.ambient.color.set(0xbce7f6).lerp(new T.Color(0xa2b4e4),night);this.ambient.groundColor.set(stage===0?0x82a278:0x9e7975).lerp(new T.Color(0x635584),night);this.ambient.intensity=2.5+night*.4;this.moonLight.intensity=night*1.7;this.sunOrb.position.copy(this.sun.position).multiplyScalar(1.5);this.sunOrb.visible=night<.75;this.moon.visible=stage===2;this.moon.scale.setScalar(.5+.5*night);(this.stars.material as T.PointsMaterial).opacity=stage===2?Math.max(0,(night-.28)/.72):0;this.clouds.position.x=Math.sin(elapsed*.005)*8;(this.clouds.material as T.MeshStandardMaterial).color.set(0xfff4dc).lerp(new T.Color(0xb3b2e1),night);(this.scene.fog as T.Fog).color.copy(sky.uniforms.bottom.value);for(let n=0;n<this.meteors.length;n++){const l=this.meteors[n],t=(elapsed+n*12)%40;l.visible=stage===2&&night>.5&&t<2;l.position.set(70-t*10+n*15,65-t*4,-20);(l.material as T.LineBasicMaterial).opacity=Math.sin(t/2*Math.PI)*night;}}
}
