import {NightmareHomecoming} from './NightmareHomecoming';
import * as T from 'three';
import {Homecoming} from './Homecoming';
import {mesh} from '../world/World';
import {glow} from '../world/Art';
export class Ending {
 group=new T.Group();stars:T.Mesh[]=[];rainbow:T.Mesh;room=new T.Group();returned=false;home:Homecoming;originY=0;nightmareHome?:NightmareHomecoming;
 constructor(public scene:T.Scene,public camera:T.PerspectiveCamera,origin:T.Vector3,nightmare=false){this.originY=origin.y;for(let n=0;n<3;n++){const star=mesh(new T.OctahedronGeometry(.8,1),[0xffdf74,0x8deccf,0xeab5ff][n],origin.x+(n-1)*3,origin.y+2,origin.z);star.material=glow([0xffd47c,0x8deccf,0xeab5ff][n]);this.group.add(star);this.stars.push(star);}this.rainbow=mesh(new T.OctahedronGeometry(2,1),0xffdf74,origin.x,origin.y+9,origin.z);this.rainbow.material=new T.MeshStandardMaterial({color:0xffdf74,emissive:0xffcc55,emissiveIntensity:1.2,roughness:.15});this.rainbow.visible=false;this.group.add(this.rainbow);for(let n=0;n<7;n++){const arc=mesh(new T.TorusGeometry(3+n*.3,.12,6,48,Math.PI),[0xff92aa,0xffbf7b,0xffe986,0xa0e4ba,0x9bdbec,0xaab5ed,0xdbacf0][n],0,0,0);arc.material=glow([0xff92aa,0xffbf7b,0xffe986,0xa0e4ba,0x9bdbec,0xaab5ed,0xdbacf0][n]);this.rainbow.add(arc);}scene.add(this.group);
 const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const c=canvas.getContext('2d')!;c.fillStyle='#dfba82';c.fillRect(0,0,512,512);for(let n=0;n<300;n++){c.strokeStyle=n%3?'#b8884529':'#fff1c936';c.lineWidth=1+n%3;c.beginPath();c.moveTo(0,n*29%512);for(let x=0;x<=512;x+=16)c.lineTo(x,n*29%512+Math.sin(x*.03+n)*3);c.stroke();}const wood=new T.CanvasTexture(canvas);wood.colorSpace=T.SRGBColorSpace;wood.wrapS=wood.wrapT=T.RepeatWrapping;wood.repeat.set(4,3);
 const floor=mesh(new T.BoxGeometry(14,.3,12),0xffffff,0,-.2,0);(floor.material as T.MeshStandardMaterial).map=wood;this.room.add(floor);
 for(const [x,z,w,d]of [[0,-5,14,.3],[-7,0,.3,12],[7,0,.3,12]]){const wall=mesh(new T.BoxGeometry(w,8,d),0xb5dfeb,x,3,z);this.room.add(wall);}const roomLight=new T.PointLight(0xffe4bf,35,20,1);roomLight.position.set(0,5,3);this.room.add(roomLight);
 const rug=mesh(new T.CylinderGeometry(3.2,3.2,.04,48),0x86c9bf,0,.01,0);this.room.add(rug);const rugTrim=mesh(new T.TorusGeometry(3,.06,8,64),0xffdf9c,0,.05,0);rugTrim.rotation.x=Math.PI/2;this.room.add(rugTrim);
 const bed=mesh(new T.BoxGeometry(3,.6,5),0xc4a3de,-3,.5,-1);this.room.add(bed,mesh(new T.BoxGeometry(3,.3,4),0xcbe9db,-3,.95,-.4));const pillow=mesh(new T.CapsuleGeometry(.4,1,8,24),0xffe9bd,-3,1.3,-2);pillow.rotation.z=Math.PI/2;this.room.add(pillow);for(const x of [-4.4,-1.6])for(const z of [-3.4,1.3])this.room.add(mesh(new T.CylinderGeometry(.13,.13,1.7,16),0xebca8b,x,.9,z));
 const chest=new T.Group();chest.position.set(1,0,0);this.room.add(chest);const box=mesh(new T.BoxGeometry(2,1.3,1.4),0xffffff,0,.65,0);const chestWood=wood.clone();chestWood.repeat.set(1,1);(box.material as T.MeshStandardMaterial).map=chestWood;chest.add(box);for(const y of [.14,1.12])chest.add(mesh(new T.BoxGeometry(2.08,.13,1.48),0x96d4bf,0,y,0));for(const x of [-.87,.87])chest.add(mesh(new T.BoxGeometry(.12,1.3,1.49),0xf4d183,x,.65,0));chest.add(mesh(new T.TorusGeometry(.18,.04,12,24),0xe9bd68,0,.7,.76));const lid=mesh(new T.BoxGeometry(2,.18,1.4),0xebca8b,0,1.6,-.4);(lid.material as T.MeshStandardMaterial).map=chestWood;lid.rotation.x=-.6;chest.add(lid);const tiny=mesh(new T.OctahedronGeometry(.3,1),0xffe274,0,1.5,0);tiny.material=glow(0xffd57b);chest.add(tiny);
 const windowPane=mesh(new T.PlaneGeometry(3,2.4),0xffffff,3,3.4,-4.8);windowPane.material.color.setHex(0x97ddeb);windowPane.material.emissive.setHex(0x97ddeb);windowPane.material.emissiveIntensity=.6;this.room.add(windowPane);for(const x of [1.4,3,4.6])this.room.add(mesh(new T.BoxGeometry(.12,2.7,.1),0xffedc6,x,3.4,-4.7));for(const y of [2,3.4,4.8])this.room.add(mesh(new T.BoxGeometry(3.3,.12,.1),0xffedc6,3,y,-4.7));for(let n=0;n<8;n++){const tile=mesh(new T.BoxGeometry(.4,.5,.4),[0xffbb98,0x9fe0d5,0xf3da85][n%3],4+n%3*.5,.25+Math.floor(n/3)*.4,-1);tile.rotation.y=n*.35;this.room.add(tile);}this.room.visible=false;scene.add(this.room);this.home=new Homecoming(this.room,camera);if(nightmare)this.nightmareHome=new NightmareHomecoming(this.home,camera);

 }
 update(t:number){const target=this.rainbow.position;for(let n=0;n<3;n++){const star=this.stars[n];star.position.y=this.originY+2+Math.min(7,t*1.2);if(t>4)star.position.lerp(target,.03);star.rotation.set(t*.6,t,0);star.visible=t<7;}this.rainbow.visible=t>=6&&t<13;this.rainbow.rotation.y=t*.3;if(t>=13&&!this.returned){this.returned=true;this.group.visible=false;this.room.visible=true;this.camera.position.set(0,3,7);this.camera.lookAt(0,1,0);}if(this.nightmareHome)this.nightmareHome.update(t);else this.home.update(t);}
 dispose(){if(this.nightmareHome&&'speechSynthesis'in window)speechSynthesis.cancel();for(const group of [this.group,this.room]){this.scene.remove(group);group.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(o.material as T.Material).dispose();}});}}
}
