import * as T from 'three';
/** Low-detail skyline beyond playable boundaries; six batches, no colliders. */
export class HorizonScenery{
 group=new T.Group();blades:T.InstancedMesh;flags:T.InstancedMesh;stage=-1;train=new T.Group();matrix=new T.Matrix4();colors=[0x8fd6cd,0xffcaa0,0xafb9e8,0xeab6d5];
 constructor(){const locations=Array.from({length:48},(_,n)=>({x:n<24?-35+n*7:-24+n%2*180,z:n<24?n%2?-32:112: -20+(n-24)*10}));const materials=[new T.MeshStandardMaterial({color:0xb6d1e8,roughness:.86}),new T.MeshStandardMaterial({color:0xdda1b9,roughness:.65}),new T.MeshStandardMaterial({color:0x86c5b6,roughness:.8})];const boxes=new T.InstancedMesh(new T.BoxGeometry(1,1,1),materials[0],48),roofs=new T.InstancedMesh(new T.ConeGeometry(1,1,16),materials[1],48),hills=new T.InstancedMesh(new T.SphereGeometry(1,16,8),materials[2],20);locations.forEach((p,n)=>{const h=9+n%5*3;boxes.setMatrixAt(n,this.matrix.makeScale(5+n%3,h,5).setPosition(p.x,h/2,p.z));boxes.setColorAt(n,new T.Color(this.colors[n%4]));roofs.setMatrixAt(n,this.matrix.makeScale(5,6,5).setPosition(p.x,h+3,p.z));});for(let n=0;n<20;n++){const p=locations[n*2];hills.setMatrixAt(n,this.matrix.makeScale(15+n%4*3,8+n%3*2,12).setPosition(p.x-8,-3,p.z+12));}this.group.add(boxes,roofs,hills);
 this.blades=new T.InstancedMesh(new T.BoxGeometry(.65,9,.16),new T.MeshStandardMaterial({color:0xffe8b6,roughness:.6}),16);this.flags=new T.InstancedMesh(new T.PlaneGeometry(2.5,1.3),new T.MeshStandardMaterial({color:0xffbac8,roughness:.9,side:T.DoubleSide}),16);this.group.add(this.blades,this.flags);const poles=new T.InstancedMesh(new T.CylinderGeometry(.09,.12,5,8),materials[0],16);for(let n=0;n<16;n++){const p=locations[n*3];poles.setMatrixAt(n,this.matrix.makeTranslation(p.x+3,17,p.z));}this.group.add(poles);
 const material=new T.MeshStandardMaterial({color:0xf8b57f,roughness:.35,metalness:.25});for(let n=0;n<4;n++){const car=new T.Mesh(new T.BoxGeometry(2.5,1.3,1.5),material);car.position.x=n*3;this.train.add(car);}this.group.add(this.train);this.group.userData.skyline=true;
 }
 update(stage:number,t:number){this.group.visible=stage!==1;this.group.position.y=stage===2?3:0;const q=new T.Quaternion();for(let n=0;n<16;n++){const x=-35+(n%8)*24,z=n<8?-32:112;q.setFromAxisAngle(new T.Vector3(0,0,1),t*.17+n);this.blades.setMatrixAt(n,this.matrix.compose(new T.Vector3(x,20,z),q,new T.Vector3(1,1,1)));q.setFromAxisAngle(new T.Vector3(0,1,0),Math.sin(t*.7+n)*.2);this.flags.setMatrixAt(n,this.matrix.compose(new T.Vector3(x+3,19,z),q,new T.Vector3(1,1,1)));}this.blades.instanceMatrix.needsUpdate=true;this.flags.instanceMatrix.needsUpdate=true;this.train.position.set(50+Math.sin(t*.027)*65,14,-23);this.train.rotation.y=Math.sin(t*.027)>0?0:Math.PI;}
}
