import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
type Arc={group:T.Group;life:number;materials:T.MeshBasicMaterial[];flash:T.Mesh};
function flashMap(){const a=document.createElement('canvas');a.width=a.height=64;const c=a.getContext('2d')!,g=c.createRadialGradient(32,32,1,32,32,31);g.addColorStop(0,'rgba(244,255,255,1)');g.addColorStop(.17,'rgba(140,238,255,.8)');g.addColorStop(.48,'rgba(70,177,255,.18)');g.addColorStop(1,'rgba(50,160,255,0)');c.fillStyle=g;c.fillRect(0,0,64,64);return new T.CanvasTexture(a);}
export class LightningEffects{
 private arcs:Arc[]=[];
 private glowMap:T.CanvasTexture|undefined;
 add(scene:T.Scene,from:T.Vector3,to:T.Vector3){if(this.arcs.length>=4){this.dispose(this.arcs.shift()!);}const group=new T.Group(),direction=to.clone().sub(from),side=new T.Vector3(0,1,0).cross(direction).normalize();if(side.lengthSq()<.1)side.set(1,0,0);const up=direction.clone().normalize().cross(side),cores:T.BufferGeometry[]=[],glows:T.BufferGeometry[]=[];
 for(let strand=0;strand<3;strand++){const points:T.Vector3[]=[];for(let n=0;n<=24;n++){const p=from.clone().lerp(to,n/24),spread=n===0||n===24?0:.12+strand*.07;p.addScaledVector(side,(Math.random()-.5)*spread*2).addScaledVector(up,(Math.random()-.5)*spread*2);points.push(p);}const curve=new T.CatmullRomCurve3(points);cores.push(new T.TubeGeometry(curve,48,strand===0?.032:.017,5,false));glows.push(new T.TubeGeometry(curve,32,.085,4,false));if(strand===0)for(let n=5;n<23;n+=6){const start=points[n],end=start.clone().addScaledVector(side,(n%2?1:-1)*(.4+Math.random()*.5)).addScaledVector(direction,.018),branch=new T.CatmullRomCurve3([start,start.clone().lerp(end,.5).addScaledVector(up,.13),end]);cores.push(new T.TubeGeometry(branch,8,.011,4,false));}}
 const coreMaterial=new T.MeshBasicMaterial({color:0xdafaff,transparent:true,opacity:.88,depthWrite:false}),haloMaterial=new T.MeshBasicMaterial({color:0x48bfff,transparent:true,opacity:.13,depthWrite:false,blending:T.AdditiveBlending});for(const [geometries,material]of [[cores,coreMaterial],[glows,haloMaterial]] as const){const joined=mergeGeometries(geometries);if(joined)group.add(new T.Mesh(joined,material));for(const geometry of geometries)geometry.dispose();}
 if(!this.glowMap)this.glowMap=flashMap();const flash=new T.Mesh(new T.PlaneGeometry(.34,.34),new T.MeshBasicMaterial({map:this.glowMap,transparent:true,opacity:.38,depthWrite:false,blending:T.AdditiveBlending,side:T.DoubleSide}));flash.position.copy(from);flash.lookAt(to);group.add(flash);const impact=new T.Mesh(new T.OctahedronGeometry(.18,1),new T.MeshBasicMaterial({color:0x9aeaff,transparent:true,opacity:.55,depthWrite:false}));impact.position.copy(to);group.add(impact);scene.add(group);this.arcs.push({group,life:.3,materials:[coreMaterial,haloMaterial,flash.material as T.MeshBasicMaterial,impact.material as T.MeshBasicMaterial],flash});}
 update(dt:number){for(let n=this.arcs.length-1;n>=0;n--){const arc=this.arcs[n];arc.life-=dt;const fade=Math.max(0,arc.life/.3),shimmer=.8+Math.sin(arc.life*100)*.2;arc.materials[0].opacity=.88*fade*shimmer;arc.materials[1].opacity=.13*fade;arc.materials[2].opacity=.38*fade;arc.materials[3].opacity=.55*fade;arc.flash.scale.setScalar(1+(1-fade)*.5);if(arc.life<=0){this.dispose(arc);this.arcs.splice(n,1);}}}
 private dispose(arc:Arc){arc.group.removeFromParent();arc.group.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(o.material as T.Material).dispose();}});}
 clear(){for(const arc of this.arcs)this.dispose(arc);this.arcs=[];}
}
