import * as T from 'three';
import type {Homecoming} from './Homecoming';
import {mesh} from '../world/World';
/** An earned, warm epilogue: wake, gratitude, school, and an invitation. */
export class NightmareHomecoming {
 sweat=new T.Group();classroom=new T.Group();friend:T.Group;spoken=new Set<number>();
 constructor(public home:Homecoming,public camera:T.PerspectiveCamera){home.spoken=true;home.head.add(this.sweat);for(let n=0;n<7;n++){const drop=mesh(new T.SphereGeometry(.045,10,8),0x8eddeb,(n%2?1:-1)*(.28+n%3*.035),.16-n%3*.09,.29);drop.scale.set(.65,1.9,.65);this.sweat.add(drop);}this.classroom.position.x=45;home.room.add(this.classroom);const room=this.classroom;for(const side of [-1,1])room.add(mesh(new T.BoxGeometry(.2,6,14),0xffe4c5,side*7.5,3,0));room.add(mesh(new T.BoxGeometry(15,.2,14),0xfff3d9,0,6,0));room.add(mesh(new T.BoxGeometry(15,.2,14),0xf0d5a8,0,-.13,0));room.add(mesh(new T.BoxGeometry(15,6,.2),0xd5e5c5,0,3,-6));room.add(mesh(new T.BoxGeometry(6,2.2,.12),0x447c6b,0,3,-5.8));for(let n=0;n<6;n++){const x=(n%3-1)*3.4,z=-3+Math.floor(n/3)*3;room.add(mesh(new T.BoxGeometry(2,.18,1.3),0xe9bc7b,x,1.1,z));for(const side of [-1,1])room.add(mesh(new T.CylinderGeometry(.065,.065,1.1,10),0x8fb8c2,x+side*.8,.5,z));room.add(mesh(new T.BoxGeometry(1.1,.15,1),0xb3d3d7,x,.65,z+1.1));}for(const x of [-5,5]){room.add(mesh(new T.BoxGeometry(2.1,2.8,.15),0xb3e9fa,x,3.5,-5.75));room.add(mesh(new T.BoxGeometry(.09,2.9,.18),0xfff0d1,x,3.5,-5.6));}room.add(new T.HemisphereLight(0xe2f5ff,0xd5c09d,2.5));const light=new T.PointLight(0xffefd1,25,20);light.position.set(0,5,3);room.add(light);this.friend=home.child.clone(true);this.friend.traverse(o=>{if(o instanceof T.Mesh){const material=(o.material as T.MeshStandardMaterial).clone();if(material.color.getHex()===0xffffff)material.color.setHex(0xffb6b4);o.material=material;}});this.friend.position.set(1.2,0,3);this.friend.rotation.y=-.8;this.friend.scale.setScalar(.94);room.add(this.friend);room.visible=false;}
 say(id:number,text:string){if(this.spoken.has(id))return;this.spoken.add(id);if(!('speechSynthesis'in window))return;const line=new SpeechSynthesisUtterance(text);line.lang='ja-JP';line.rate=.92;line.pitch=id===3?1.3:1.12;line.volume=.8;const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('ja'));if(voice)line.voice=voice;speechSynthesis.speak(line);}
 update(t:number){if(t<13)return;const local=t-13,h=this.home;for(const part of h.child.children)if(part instanceof T.Mesh&&(part.position.z<-.3||Math.abs(part.position.x)===.21))part.visible=local>=14;this.sweat.visible=local<6;this.classroom.visible=local>=22;
 if(local<6){h.child.position.set(-3,1.12,-.5);h.child.rotation.set(-.65*(1-T.MathUtils.smoothstep(local,0,2)),0,0);for(const leg of h.legs)leg.rotation.x=-1.1;h.arms[0].rotation.x=-.9;h.arms[1].rotation.x=-.7;h.head.rotation.x=Math.sin(local*3)*.035;for(const [n,drop]of this.sweat.children.entries())drop.position.y=.18-((local*.3+n*.07)%.38);this.camera.position.set(.5,3,3.8);this.camera.lookAt(-3,2.4,-.5);}
 else if(local<14){h.child.rotation.set(0,Math.PI,0);h.child.position.set(1,0,1.8);h.legs.forEach(l=>l.rotation.x=0);h.arms[0].rotation.x=-.35;h.arms[1].rotation.x=-.5;h.head.rotation.x=.15;this.camera.position.set(4.2,2.7,-2.8);this.camera.lookAt(1,1.35,.5);this.say(1,'ぼくは、きみたちのおかげで、つよくなれた。');}
 else if(local<22){h.update(23+local-14);this.say(2,'いってきます！');}
 else{for(const object of h.room.children)object.visible=object===this.classroom||object===h.child;this.classroom.visible=true;h.child.position.set(43.7,0,3);h.child.rotation.set(0,.8,0);h.head.rotation.x=0;h.legs.forEach(l=>l.rotation.x=0);h.arms[0].rotation.set(-.2,0,0);h.arms[1].rotation.set(local>=29?-.9:-.1,0,local>=29?-.3:0);this.friend.rotation.y=-.8+Math.sin(local)*.025;this.camera.position.set(45,3,9);this.camera.lookAt(45,1.5,3);if(local<29)this.say(3,'ねえ、なにかあったの？');else if(local<37)this.say(4,'うん！こんど、ぼくのへやに、あそびにおいでよ！');}
 }
}
